/* Erzeugt von pflege/baue-werte.js - NICHT von Hand aendern. */
/* Stand 2026-08-28. Zum Aktualisieren die Zahlen im Pflegeskript ersetzen. */
const WERTE = {
 "stand": "2026-08-28",
 "eurUsd": 1.1643,
 "hinweis": "Startkurse und Kennzahlen sind echte Marktdaten vom angegebenen Stand. Der Kursverlauf im Spiel ist simuliert und hat keinen Bezug zur Wirklichkeit.",
 "quellen": [
  "stockanalysis.com (Kurse, KGV, Dividendenrendite, ETF-Kennzahlen)",
  "CoinGecko (Kryptokurse)",
  "frankfurter.dev / EZB (Wechselkurse)"
 ],
 "werte": [
  {
   "id": "sap",
   "art": "aktie",
   "name": "SAP",
   "kuerzel": "SAP",
   "kurs": 191.32,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 28.64,
   "gewinnJeAktie": 6.6802,
   "dividende": 2.6211,
   "divRendite": 1.37,
   "sektor": "Technologie",
   "land": "Deutschland"
  },
  {
   "id": "sie",
   "art": "aktie",
   "name": "Siemens",
   "kuerzel": "SIE",
   "kurs": 289.85,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 28.68,
   "gewinnJeAktie": 10.1063,
   "dividende": 5.5941,
   "divRendite": 1.93,
   "sektor": "Industrie",
   "land": "Deutschland"
  },
  {
   "id": "alv",
   "art": "aktie",
   "name": "Allianz",
   "kuerzel": "ALV",
   "kurs": 453,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 14.84,
   "gewinnJeAktie": 30.5256,
   "dividende": 17.5311,
   "divRendite": 3.87,
   "sektor": "Versicherung",
   "land": "Deutschland"
  },
  {
   "id": "rhm",
   "art": "aktie",
   "name": "Rheinmetall",
   "kuerzel": "RHM",
   "kurs": 1154.6,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 44.96,
   "gewinnJeAktie": 25.6806,
   "dividende": 11.3151,
   "divRendite": 0.98,
   "sektor": "Ruestung",
   "land": "Deutschland"
  },
  {
   "id": "mbg",
   "art": "aktie",
   "name": "Mercedes-Benz Group",
   "kuerzel": "MBG",
   "kurs": 46.945,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 8.9,
   "gewinnJeAktie": 5.2747,
   "dividende": 3.6476,
   "divRendite": 7.77,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "bmw",
   "art": "aktie",
   "name": "BMW",
   "kuerzel": "BMW",
   "kurs": 62.64,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 5.7,
   "gewinnJeAktie": 10.9895,
   "dividende": 4.5978,
   "divRendite": 7.34,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "vow3",
   "art": "aktie",
   "name": "Volkswagen Vorzuege",
   "kuerzel": "VOW3",
   "kurs": 77.42,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 7.17,
   "gewinnJeAktie": 10.7978,
   "dividende": 5.4426,
   "divRendite": 7.03,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "dbk",
   "art": "aktie",
   "name": "Deutsche Bank",
   "kuerzel": "DBK",
   "kurs": 34.905,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 11.12,
   "gewinnJeAktie": 3.1389,
   "dividende": 1.0716,
   "divRendite": 3.07,
   "sektor": "Banken",
   "land": "Deutschland"
  },
  {
   "id": "cbk",
   "art": "aktie",
   "name": "Commerzbank",
   "kuerzel": "CBK",
   "kurs": 40.48,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 15.29,
   "gewinnJeAktie": 2.6475,
   "dividende": 1.1415,
   "divRendite": 2.82,
   "sektor": "Banken",
   "land": "Deutschland"
  },
  {
   "id": "ads",
   "art": "aktie",
   "name": "adidas",
   "kuerzel": "ADS",
   "kurs": 154.2,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 19.67,
   "gewinnJeAktie": 7.8393,
   "dividende": 2.791,
   "divRendite": 1.81,
   "sektor": "Konsum",
   "land": "Deutschland"
  },
  {
   "id": "zal",
   "art": "aktie",
   "name": "Zalando",
   "kuerzel": "ZAL",
   "kurs": 24.16,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 65.09,
   "gewinnJeAktie": 0.371178,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Handel",
   "land": "Deutschland"
  },
  {
   "id": "ifx",
   "art": "aktie",
   "name": "Infineon",
   "kuerzel": "IFX",
   "kurs": 57.08,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 62.12,
   "gewinnJeAktie": 0.918867,
   "dividende": 0.359604,
   "divRendite": 0.63,
   "sektor": "Halbleiter",
   "land": "Deutschland"
  },
  {
   "id": "bas",
   "art": "aktie",
   "name": "BASF",
   "kuerzel": "BAS",
   "kurs": 52.52,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 21.77,
   "gewinnJeAktie": 2.4125,
   "dividende": 2.3161,
   "divRendite": 4.41,
   "sektor": "Chemie",
   "land": "Deutschland"
  },
  {
   "id": "bayn",
   "art": "aktie",
   "name": "Bayer",
   "kuerzel": "BAYN",
   "kurs": 48.67,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0.107074,
   "divRendite": 0.22,
   "sektor": "Pharma",
   "land": "Deutschland"
  },
  {
   "id": "mrk1",
   "art": "aktie",
   "name": "Merck",
   "kuerzel": "MRK1",
   "kurs": 140.25,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 25.71,
   "gewinnJeAktie": 5.4551,
   "dividende": 2.23,
   "divRendite": 1.59,
   "sektor": "Pharma",
   "land": "Deutschland"
  },
  {
   "id": "dte",
   "art": "aktie",
   "name": "Deutsche Telekom",
   "kuerzel": "DTE",
   "kurs": 28.52,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 15.78,
   "gewinnJeAktie": 1.8074,
   "dividende": 0.978236,
   "divRendite": 3.43,
   "sektor": "Telekom",
   "land": "Deutschland"
  },
  {
   "id": "dhl",
   "art": "aktie",
   "name": "DHL Group",
   "kuerzel": "DHL",
   "kurs": 56.52,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 17.18,
   "gewinnJeAktie": 3.2899,
   "dividende": 1.9443,
   "divRendite": 3.44,
   "sektor": "Logistik",
   "land": "Deutschland"
  },
  {
   "id": "eoan",
   "art": "aktie",
   "name": "E.ON",
   "kuerzel": "EOAN",
   "kurs": 17.83,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 13.95,
   "gewinnJeAktie": 1.2781,
   "dividende": 0.579475,
   "divRendite": 3.25,
   "sektor": "Versorger",
   "land": "Deutschland"
  },
  {
   "id": "rwe",
   "art": "aktie",
   "name": "RWE",
   "kuerzel": "RWE",
   "kurs": 59.1,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 13.07,
   "gewinnJeAktie": 4.5218,
   "dividende": 1.2411,
   "divRendite": 2.1,
   "sektor": "Versorger",
   "land": "Deutschland"
  },
  {
   "id": "enr",
   "art": "aktie",
   "name": "Siemens Energy",
   "kuerzel": "ENR",
   "kurs": 149.7,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 48.87,
   "gewinnJeAktie": 3.0632,
   "dividende": 0.67365,
   "divRendite": 0.45,
   "sektor": "Versorger",
   "land": "Deutschland"
  },
  {
   "id": "muv2",
   "art": "aktie",
   "name": "Muenchener Rueck",
   "kuerzel": "MUV2",
   "kurs": 518,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 9.58,
   "gewinnJeAktie": 54.071,
   "dividende": 23.7244,
   "divRendite": 4.58,
   "sektor": "Versicherung",
   "land": "Deutschland"
  },
  {
   "id": "hnr1",
   "art": "aktie",
   "name": "Hannover Rueck",
   "kuerzel": "HNR1",
   "kurs": 257.4,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 11.3,
   "gewinnJeAktie": 22.7788,
   "dividende": 12.5611,
   "divRendite": 4.88,
   "sektor": "Versicherung",
   "land": "Deutschland"
  },
  {
   "id": "db1",
   "art": "aktie",
   "name": "Deutsche Boerse",
   "kuerzel": "DB1",
   "kurs": 291.2,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 24.91,
   "gewinnJeAktie": 11.6901,
   "dividende": 4.3971,
   "divRendite": 1.51,
   "sektor": "Finanzen",
   "land": "Deutschland"
  },
  {
   "id": "bei",
   "art": "aktie",
   "name": "Beiersdorf",
   "kuerzel": "BEI",
   "kurs": 80.42,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 18.75,
   "gewinnJeAktie": 4.2891,
   "dividende": 1.0294,
   "divRendite": 1.28,
   "sektor": "Konsum",
   "land": "Deutschland"
  },
  {
   "id": "hen3",
   "art": "aktie",
   "name": "Henkel Vorzuege",
   "kuerzel": "HEN3",
   "kurs": 75.82,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 16.14,
   "gewinnJeAktie": 4.6976,
   "dividende": 2.0775,
   "divRendite": 2.74,
   "sektor": "Konsum",
   "land": "Deutschland"
  },
  {
   "id": "con",
   "art": "aktie",
   "name": "Continental",
   "kuerzel": "CON",
   "kurs": 70,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 2.786,
   "divRendite": 3.98,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "dtg",
   "art": "aktie",
   "name": "Daimler Truck",
   "kuerzel": "DTG",
   "kurs": 46.77,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 33.3,
   "gewinnJeAktie": 1.4045,
   "dividende": 1.9643,
   "divRendite": 4.2,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "mtx",
   "art": "aktie",
   "name": "MTU Aero Engines",
   "kuerzel": "MTX",
   "kurs": 359.6,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 20.77,
   "gewinnJeAktie": 17.3134,
   "dividende": 3.596,
   "divRendite": 1,
   "sektor": "Luftfahrt",
   "land": "Deutschland"
  },
  {
   "id": "hei",
   "art": "aktie",
   "name": "Heidelberg Materials",
   "kuerzel": "HEI",
   "kurs": 170.05,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 14.62,
   "gewinnJeAktie": 11.6313,
   "dividende": 3.8771,
   "divRendite": 2.28,
   "sektor": "Bau",
   "land": "Deutschland"
  },
  {
   "id": "vna",
   "art": "aktie",
   "name": "Vonovia",
   "kuerzel": "VNA",
   "kurs": 19.85,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 4.65,
   "gewinnJeAktie": 4.2688,
   "dividende": 1.2446,
   "divRendite": 6.27,
   "sektor": "Immobilien",
   "land": "Deutschland"
  },
  {
   "id": "asml",
   "art": "aktie",
   "name": "ASML",
   "kuerzel": "ASML",
   "kurs": 1494.4,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 53.98,
   "gewinnJeAktie": 27.6843,
   "dividende": 7.472,
   "divRendite": 0.5,
   "sektor": "Halbleiter",
   "land": "Niederlande"
  },
  {
   "id": "mc",
   "art": "aktie",
   "name": "LVMH",
   "kuerzel": "MC",
   "kurs": 458.15,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 20.89,
   "gewinnJeAktie": 21.9315,
   "dividende": 13.2864,
   "divRendite": 2.9,
   "sektor": "Luxus",
   "land": "Frankreich"
  },
  {
   "id": "rms",
   "art": "aktie",
   "name": "Hermes",
   "kuerzel": "RMS",
   "kurs": 1598,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 36.35,
   "gewinnJeAktie": 43.9615,
   "dividende": 18.2172,
   "divRendite": 1.14,
   "sektor": "Luxus",
   "land": "Frankreich"
  },
  {
   "id": "or",
   "art": "aktie",
   "name": "LOreal",
   "kuerzel": "OR",
   "kurs": 388.5,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 32.67,
   "gewinnJeAktie": 11.8916,
   "dividende": 7.3038,
   "divRendite": 1.88,
   "sektor": "Konsum",
   "land": "Frankreich"
  },
  {
   "id": "tte",
   "art": "aktie",
   "name": "TotalEnergies",
   "kuerzel": "TTE",
   "kurs": 74.67,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 10.56,
   "gewinnJeAktie": 7.071,
   "dividende": 3.6215,
   "divRendite": 4.85,
   "sektor": "Energie",
   "land": "Frankreich"
  },
  {
   "id": "san",
   "art": "aktie",
   "name": "Sanofi",
   "kuerzel": "SAN",
   "kurs": 77.25,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 23.79,
   "gewinnJeAktie": 3.2472,
   "dividende": 4.0479,
   "divRendite": 5.24,
   "sektor": "Pharma",
   "land": "Frankreich"
  },
  {
   "id": "ai",
   "art": "aktie",
   "name": "Air Liquide",
   "kuerzel": "AI",
   "kurs": 169.8,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 30.01,
   "gewinnJeAktie": 5.6581,
   "dividende": 3.43,
   "divRendite": 2.02,
   "sektor": "Chemie",
   "land": "Frankreich"
  },
  {
   "id": "su",
   "art": "aktie",
   "name": "Schneider Electric",
   "kuerzel": "SU",
   "kurs": 301.75,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 36.3,
   "gewinnJeAktie": 8.3127,
   "dividende": 4.2848,
   "divRendite": 1.42,
   "sektor": "Industrie",
   "land": "Frankreich"
  },
  {
   "id": "saf",
   "art": "aktie",
   "name": "SAFRAN",
   "kuerzel": "SAF",
   "kurs": 344.2,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 36.86,
   "gewinnJeAktie": 9.338,
   "dividende": 3.3043,
   "divRendite": 0.96,
   "sektor": "Luftfahrt",
   "land": "Frankreich"
  },
  {
   "id": "cs",
   "art": "aktie",
   "name": "AXA",
   "kuerzel": "CS",
   "kurs": 43.61,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 11.58,
   "gewinnJeAktie": 3.766,
   "dividende": 2.3026,
   "divRendite": 5.28,
   "sektor": "Versicherung",
   "land": "Frankreich"
  },
  {
   "id": "bnp",
   "art": "aktie",
   "name": "BNP Paribas",
   "kuerzel": "BNP",
   "kurs": 102.56,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 8.72,
   "gewinnJeAktie": 11.7615,
   "dividende": 4.9126,
   "divRendite": 4.79,
   "sektor": "Banken",
   "land": "Frankreich"
  },
  {
   "id": "dg",
   "art": "aktie",
   "name": "VINCI",
   "kuerzel": "DG",
   "kurs": 114.35,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 12.73,
   "gewinnJeAktie": 8.9827,
   "dividende": 4.7455,
   "divRendite": 4.15,
   "sektor": "Bau",
   "land": "Frankreich"
  },
  {
   "id": "bn",
   "art": "aktie",
   "name": "Danone",
   "kuerzel": "BN",
   "kurs": 64.4,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 21.43,
   "gewinnJeAktie": 3.0051,
   "dividende": 2.2154,
   "divRendite": 3.44,
   "sektor": "Nahrung",
   "land": "Frankreich"
  },
  {
   "id": "el",
   "art": "aktie",
   "name": "EssilorLuxottica",
   "kuerzel": "EL",
   "kurs": 161.35,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 29.43,
   "gewinnJeAktie": 5.4825,
   "dividende": 3.9531,
   "divRendite": 2.45,
   "sektor": "Konsum",
   "land": "Frankreich"
  },
  {
   "id": "air",
   "art": "aktie",
   "name": "Airbus",
   "kuerzel": "AIR",
   "kurs": 203.05,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 27.09,
   "gewinnJeAktie": 7.4954,
   "dividende": 3.127,
   "divRendite": 1.54,
   "sektor": "Luftfahrt",
   "land": "Niederlande"
  },
  {
   "id": "race",
   "art": "aktie",
   "name": "Ferrari",
   "kuerzel": "RACE",
   "kurs": 362.65,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 38.56,
   "gewinnJeAktie": 9.4048,
   "dividende": 3.6265,
   "divRendite": 1,
   "sektor": "Automobil",
   "land": "Italien"
  },
  {
   "id": "adyen",
   "art": "aktie",
   "name": "Adyen",
   "kuerzel": "ADYEN",
   "kurs": 1090.4,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 30.35,
   "gewinnJeAktie": 35.9275,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Finanzen",
   "land": "Niederlande"
  },
  {
   "id": "inga",
   "art": "aktie",
   "name": "ING Group",
   "kuerzel": "INGA",
   "kurs": 30.46,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 10.09,
   "gewinnJeAktie": 3.0188,
   "dividende": 1.3402,
   "divRendite": 4.4,
   "sektor": "Banken",
   "land": "Niederlande"
  },
  {
   "id": "abi",
   "art": "aktie",
   "name": "AB InBev",
   "kuerzel": "ABI",
   "kurs": 68.28,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 16.57,
   "gewinnJeAktie": 4.1207,
   "dividende": 1.1812,
   "divRendite": 1.73,
   "sektor": "Nahrung",
   "land": "Belgien"
  },
  {
   "id": "itx",
   "art": "aktie",
   "name": "Inditex",
   "kuerzel": "ITX",
   "kurs": 58.32,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 28.91,
   "gewinnJeAktie": 2.0173,
   "dividende": 1.7496,
   "divRendite": 3,
   "sektor": "Handel",
   "land": "Spanien"
  },
  {
   "id": "san2",
   "art": "aktie",
   "name": "Banco Santander",
   "kuerzel": "SAN2",
   "kurs": 12.712,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 14.22,
   "gewinnJeAktie": 0.893952,
   "dividende": 0.250426,
   "divRendite": 1.97,
   "sektor": "Banken",
   "land": "Spanien"
  },
  {
   "id": "ibe",
   "art": "aktie",
   "name": "Iberdrola",
   "kuerzel": "IBE",
   "kurs": 20.28,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 24.58,
   "gewinnJeAktie": 0.825061,
   "dividende": 0.683436,
   "divRendite": 3.37,
   "sektor": "Versorger",
   "land": "Spanien"
  },
  {
   "id": "enel",
   "art": "aktie",
   "name": "Enel",
   "kuerzel": "ENEL",
   "kurs": 9.46,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 22.46,
   "gewinnJeAktie": 0.421193,
   "dividende": 0.489082,
   "divRendite": 5.17,
   "sektor": "Versorger",
   "land": "Italien"
  },
  {
   "id": "eni",
   "art": "aktie",
   "name": "Eni",
   "kuerzel": "ENI",
   "kurs": 22.79,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 11.96,
   "gewinnJeAktie": 1.9055,
   "dividende": 1.0802,
   "divRendite": 4.74,
   "sektor": "Energie",
   "land": "Italien"
  },
  {
   "id": "ucg",
   "art": "aktie",
   "name": "UniCredit",
   "kuerzel": "UCG",
   "kurs": 84.71,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 12.03,
   "gewinnJeAktie": 7.0416,
   "dividende": 3.2359,
   "divRendite": 3.82,
   "sektor": "Banken",
   "land": "Italien"
  },
  {
   "id": "isp",
   "art": "aktie",
   "name": "Intesa Sanpaolo",
   "kuerzel": "ISP",
   "kurs": 6.78,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 12.15,
   "gewinnJeAktie": 0.558025,
   "dividende": 0.37968,
   "divRendite": 5.6,
   "sektor": "Banken",
   "land": "Italien"
  },
  {
   "id": "nvda",
   "art": "aktie",
   "name": "NVIDIA",
   "kuerzel": "NVDA",
   "kurs": 187.73,
   "kursOriginal": 218.57,
   "waehrungOriginal": "USD",
   "kgv": 28.83,
   "gewinnJeAktie": 6.5116,
   "dividende": 0.863558,
   "divRendite": 0.46,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "aapl",
   "art": "aktie",
   "name": "Apple",
   "kuerzel": "AAPL",
   "kurs": 274.56,
   "kursOriginal": 319.67,
   "waehrungOriginal": "USD",
   "kgv": 36.09,
   "gewinnJeAktie": 7.6076,
   "dividende": 0.933504,
   "divRendite": 0.34,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "googl",
   "art": "aktie",
   "name": "Alphabet",
   "kuerzel": "GOOGL",
   "kurs": 297.93,
   "kursOriginal": 346.88,
   "waehrungOriginal": "USD",
   "kgv": 17.09,
   "gewinnJeAktie": 17.433,
   "dividende": 0.744825,
   "divRendite": 0.25,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "msft",
   "art": "aktie",
   "name": "Microsoft",
   "kuerzel": "MSFT",
   "kurs": 442.33,
   "kursOriginal": 515.01,
   "waehrungOriginal": "USD",
   "kgv": 28.14,
   "gewinnJeAktie": 15.7189,
   "dividende": 3.1405,
   "divRendite": 0.71,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "amzn",
   "art": "aktie",
   "name": "Amazon",
   "kuerzel": "AMZN",
   "kurs": 227.69,
   "kursOriginal": 265.095,
   "waehrungOriginal": "USD",
   "kgv": 20.61,
   "gewinnJeAktie": 11.0475,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Handel",
   "land": "USA"
  },
  {
   "id": "avgo",
   "art": "aktie",
   "name": "Broadcom",
   "kuerzel": "AVGO",
   "kurs": 316.27,
   "kursOriginal": 368.23,
   "waehrungOriginal": "USD",
   "kgv": 61.83,
   "gewinnJeAktie": 5.1152,
   "dividende": 2.2455,
   "divRendite": 0.71,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "meta",
   "art": "aktie",
   "name": "Meta Platforms",
   "kuerzel": "META",
   "kurs": 494.72,
   "kursOriginal": 576,
   "waehrungOriginal": "USD",
   "kgv": 21.52,
   "gewinnJeAktie": 22.9888,
   "dividende": 1.781,
   "divRendite": 0.36,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "tsla",
   "art": "aktie",
   "name": "Tesla",
   "kuerzel": "TSLA",
   "kurs": 297.6,
   "kursOriginal": 346.49,
   "waehrungOriginal": "USD",
   "kgv": 368.19,
   "gewinnJeAktie": 0.808278,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Automobil",
   "land": "USA"
  },
  {
   "id": "brkb",
   "art": "aktie",
   "name": "Berkshire Hathaway",
   "kuerzel": "BRK.B",
   "kurs": 434.27,
   "kursOriginal": 505.62,
   "waehrungOriginal": "USD",
   "kgv": 12.57,
   "gewinnJeAktie": 34.5481,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Finanzen",
   "land": "USA"
  },
  {
   "id": "mu",
   "art": "aktie",
   "name": "Micron Technology",
   "kuerzel": "MU",
   "kurs": 799.48,
   "kursOriginal": 930.83,
   "waehrungOriginal": "USD",
   "kgv": 21.11,
   "gewinnJeAktie": 37.8721,
   "dividende": 0.479688,
   "divRendite": 0.06,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "jpm",
   "art": "aktie",
   "name": "JPMorgan Chase",
   "kuerzel": "JPM",
   "kurs": 305.62,
   "kursOriginal": 355.83,
   "waehrungOriginal": "USD",
   "kgv": 15.2,
   "gewinnJeAktie": 20.1066,
   "dividende": 5.165,
   "divRendite": 1.69,
   "sektor": "Banken",
   "land": "USA"
  },
  {
   "id": "wmt",
   "art": "aktie",
   "name": "Walmart",
   "kuerzel": "WMT",
   "kurs": 88.4222,
   "kursOriginal": 102.95,
   "waehrungOriginal": "USD",
   "kgv": 37.19,
   "gewinnJeAktie": 2.3776,
   "dividende": 0.848853,
   "divRendite": 0.96,
   "sektor": "Handel",
   "land": "USA"
  },
  {
   "id": "amd",
   "art": "aktie",
   "name": "AMD",
   "kuerzel": "AMD",
   "kurs": 403.85,
   "kursOriginal": 470.2,
   "waehrungOriginal": "USD",
   "kgv": 121.66,
   "gewinnJeAktie": 3.3195,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "v",
   "art": "aktie",
   "name": "Visa",
   "kuerzel": "V",
   "kurs": 328.36,
   "kursOriginal": 382.31,
   "waehrungOriginal": "USD",
   "kgv": 32.32,
   "gewinnJeAktie": 10.1597,
   "dividende": 2.2985,
   "divRendite": 0.7,
   "sektor": "Finanzen",
   "land": "USA"
  },
  {
   "id": "jnj",
   "art": "aktie",
   "name": "Johnson & Johnson",
   "kuerzel": "JNJ",
   "kurs": 228.14,
   "kursOriginal": 265.625,
   "waehrungOriginal": "USD",
   "kgv": 30.81,
   "gewinnJeAktie": 7.4047,
   "dividende": 4.6084,
   "divRendite": 2.02,
   "sektor": "Pharma",
   "land": "USA"
  },
  {
   "id": "csco",
   "art": "aktie",
   "name": "Cisco",
   "kuerzel": "CSCO",
   "kurs": 94.7522,
   "kursOriginal": 110.32,
   "waehrungOriginal": "USD",
   "kgv": 33.68,
   "gewinnJeAktie": 2.8133,
   "dividende": 1.4402,
   "divRendite": 1.52,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "cost",
   "art": "aktie",
   "name": "Costco",
   "kuerzel": "COST",
   "kurs": 813.58,
   "kursOriginal": 947.25,
   "waehrungOriginal": "USD",
   "kgv": 47.01,
   "gewinnJeAktie": 17.3065,
   "dividende": 5.0442,
   "divRendite": 0.62,
   "sektor": "Handel",
   "land": "USA"
  },
  {
   "id": "amat",
   "art": "aktie",
   "name": "Applied Materials",
   "kuerzel": "AMAT",
   "kurs": 398.06,
   "kursOriginal": 463.46,
   "waehrungOriginal": "USD",
   "kgv": 41.61,
   "gewinnJeAktie": 9.5665,
   "dividende": 1.8311,
   "divRendite": 0.46,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "cat",
   "art": "aktie",
   "name": "Caterpillar",
   "kuerzel": "CAT",
   "kurs": 689.52,
   "kursOriginal": 802.81,
   "waehrungOriginal": "USD",
   "kgv": 35.21,
   "gewinnJeAktie": 19.5831,
   "dividende": 5.5851,
   "divRendite": 0.81,
   "sektor": "Industrie",
   "land": "USA"
  },
  {
   "id": "lrcx",
   "art": "aktie",
   "name": "Lam Research",
   "kuerzel": "LRCX",
   "kurs": 262.35,
   "kursOriginal": 305.45,
   "waehrungOriginal": "USD",
   "kgv": 55.31,
   "gewinnJeAktie": 4.7433,
   "dividende": 0.89199,
   "divRendite": 0.34,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "pltr",
   "art": "aktie",
   "name": "Palantir",
   "kuerzel": "PLTR",
   "kurs": 159.58,
   "kursOriginal": 185.8,
   "waehrungOriginal": "USD",
   "kgv": 159.02,
   "gewinnJeAktie": 1.0035,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "ko",
   "art": "aktie",
   "name": "Coca-Cola",
   "kuerzel": "KO",
   "kurs": 77.115,
   "kursOriginal": 89.785,
   "waehrungOriginal": "USD",
   "kgv": 26.77,
   "gewinnJeAktie": 2.8806,
   "dividende": 1.8199,
   "divRendite": 2.36,
   "sektor": "Nahrung",
   "land": "USA"
  },
  {
   "id": "cvx",
   "art": "aktie",
   "name": "Chevron",
   "kuerzel": "CVX",
   "kurs": 173.11,
   "kursOriginal": 201.55,
   "waehrungOriginal": "USD",
   "kgv": 19.19,
   "gewinnJeAktie": 9.0208,
   "dividende": 6.1108,
   "divRendite": 3.53,
   "sektor": "Energie",
   "land": "USA"
  },
  {
   "id": "unh",
   "art": "aktie",
   "name": "UnitedHealth",
   "kuerzel": "UNH",
   "kurs": 338.85,
   "kursOriginal": 394.52,
   "waehrungOriginal": "USD",
   "kgv": 25.43,
   "gewinnJeAktie": 13.3248,
   "dividende": 7.963,
   "divRendite": 2.35,
   "sektor": "Gesundheit",
   "land": "USA"
  },
  {
   "id": "hd",
   "art": "aktie",
   "name": "Home Depot",
   "kuerzel": "HD",
   "kurs": 282.27,
   "kursOriginal": 328.65,
   "waehrungOriginal": "USD",
   "kgv": 22.99,
   "gewinnJeAktie": 12.2779,
   "dividende": 8.0165,
   "divRendite": 2.84,
   "sektor": "Handel",
   "land": "USA"
  },
  {
   "id": "pg",
   "art": "aktie",
   "name": "Procter & Gamble",
   "kuerzel": "PG",
   "kurs": 123.07,
   "kursOriginal": 143.29,
   "waehrungOriginal": "USD",
   "kgv": 21.61,
   "gewinnJeAktie": 5.695,
   "dividende": 3.7413,
   "divRendite": 3.04,
   "sektor": "Konsum",
   "land": "USA"
  },
  {
   "id": "mrk",
   "art": "aktie",
   "name": "Merck & Co",
   "kuerzel": "MRK",
   "kurs": 126.73,
   "kursOriginal": 147.55,
   "waehrungOriginal": "USD",
   "kgv": 117.49,
   "gewinnJeAktie": 1.0786,
   "dividende": 2.9148,
   "divRendite": 2.3,
   "sektor": "Pharma",
   "land": "USA"
  },
  {
   "id": "gs",
   "art": "aktie",
   "name": "Goldman Sachs",
   "kuerzel": "GS",
   "kurs": 887.23,
   "kursOriginal": 1033,
   "waehrungOriginal": "USD",
   "kgv": 16.1,
   "gewinnJeAktie": 55.1075,
   "dividende": 17.2123,
   "divRendite": 1.94,
   "sektor": "Banken",
   "land": "USA"
  },
  {
   "id": "nflx",
   "art": "aktie",
   "name": "Netflix",
   "kuerzel": "NFLX",
   "kurs": 69.9991,
   "kursOriginal": 81.5,
   "waehrungOriginal": "USD",
   "kgv": 25.15,
   "gewinnJeAktie": 2.7833,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Medien",
   "land": "USA"
  },
  {
   "id": "txn",
   "art": "aktie",
   "name": "Texas Instruments",
   "kuerzel": "TXN",
   "kurs": 221.27,
   "kursOriginal": 257.62,
   "waehrungOriginal": "USD",
   "kgv": 40.49,
   "gewinnJeAktie": 5.4648,
   "dividende": 4.8901,
   "divRendite": 2.21,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "klac",
   "art": "aktie",
   "name": "KLA",
   "kuerzel": "KLAC",
   "kurs": 151.23,
   "kursOriginal": 176.08,
   "waehrungOriginal": "USD",
   "kgv": 50.21,
   "gewinnJeAktie": 3.0119,
   "dividende": 0.786396,
   "divRendite": 0.52,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "axp",
   "art": "aktie",
   "name": "American Express",
   "kuerzel": "AXP",
   "kurs": 286.18,
   "kursOriginal": 333.2,
   "waehrungOriginal": "USD",
   "kgv": 20.29,
   "gewinnJeAktie": 14.1045,
   "dividende": 3.2625,
   "divRendite": 1.14,
   "sektor": "Finanzen",
   "land": "USA"
  },
  {
   "id": "panw",
   "art": "aktie",
   "name": "Palo Alto Networks",
   "kuerzel": "PANW",
   "kurs": 317.45,
   "kursOriginal": 369.61,
   "waehrungOriginal": "USD",
   "kgv": 346.83,
   "gewinnJeAktie": 0.91529,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "intc",
   "art": "aktie",
   "name": "Intel",
   "kuerzel": "INTC",
   "kurs": 76.7414,
   "kursOriginal": 89.35,
   "waehrungOriginal": "USD",
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "ma",
   "art": "aktie",
   "name": "Mastercard",
   "kuerzel": "MA",
   "kurs": 511.92,
   "kursOriginal": 596.03,
   "waehrungOriginal": "USD",
   "kgv": 32.54,
   "gewinnJeAktie": 15.732,
   "dividende": 2.9691,
   "divRendite": 0.58,
   "sektor": "Finanzen",
   "land": "USA"
  },
  {
   "id": "lly",
   "art": "aktie",
   "name": "Eli Lilly",
   "kuerzel": "LLY",
   "kurs": 1003.18,
   "kursOriginal": 1168,
   "waehrungOriginal": "USD",
   "kgv": 39.48,
   "gewinnJeAktie": 25.4098,
   "dividende": 5.9188,
   "divRendite": 0.59,
   "sektor": "Pharma",
   "land": "USA"
  },
  {
   "id": "xom",
   "art": "aktie",
   "name": "ExxonMobil",
   "kuerzel": "XOM",
   "kurs": 133.75,
   "kursOriginal": 155.73,
   "waehrungOriginal": "USD",
   "kgv": 20.17,
   "gewinnJeAktie": 6.6311,
   "dividende": 3.5444,
   "divRendite": 2.65,
   "sektor": "Energie",
   "land": "USA"
  },
  {
   "id": "orcl",
   "art": "aktie",
   "name": "Oracle",
   "kuerzel": "ORCL",
   "kurs": 129.33,
   "kursOriginal": 150.58,
   "waehrungOriginal": "USD",
   "kgv": 26.06,
   "gewinnJeAktie": 4.9628,
   "dividende": 1.7201,
   "divRendite": 1.33,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "ge",
   "art": "aktie",
   "name": "GE Aerospace",
   "kuerzel": "GE",
   "kurs": 293.94,
   "kursOriginal": 342.24,
   "waehrungOriginal": "USD",
   "kgv": 40.4,
   "gewinnJeAktie": 7.2757,
   "dividende": 1.6167,
   "divRendite": 0.55,
   "sektor": "Luftfahrt",
   "land": "USA"
  },
  {
   "id": "bac",
   "art": "aktie",
   "name": "Bank of America",
   "kuerzel": "BAC",
   "kurs": 53.5257,
   "kursOriginal": 62.32,
   "waehrungOriginal": "USD",
   "kgv": 14.13,
   "gewinnJeAktie": 3.7881,
   "dividende": 1.1026,
   "divRendite": 2.06,
   "sektor": "Banken",
   "land": "USA"
  },
  {
   "id": "tsm",
   "art": "aktie",
   "name": "TSMC",
   "kuerzel": "TSM",
   "kurs": 360.63,
   "kursOriginal": 419.88,
   "waehrungOriginal": "USD",
   "kgv": 28.43,
   "gewinnJeAktie": 12.6848,
   "dividende": 2.7769,
   "divRendite": 0.77,
   "sektor": "Halbleiter",
   "land": "Taiwan"
  },
  {
   "id": "skhy",
   "art": "aktie",
   "name": "SK hynix",
   "kuerzel": "SKHY",
   "kurs": 1032.87,
   "kursOriginal": 1653000,
   "waehrungOriginal": "KRW",
   "kgv": 7.26,
   "gewinnJeAktie": 142.27,
   "dividende": 1.8592,
   "divRendite": 0.18,
   "sektor": "Halbleiter",
   "land": "Suedkorea"
  },
  {
   "id": "baba",
   "art": "aktie",
   "name": "Alibaba",
   "kuerzel": "BABA",
   "kurs": 101.55,
   "kursOriginal": 118.24,
   "waehrungOriginal": "USD",
   "kgv": 26.55,
   "gewinnJeAktie": 3.8249,
   "dividende": 0.903795,
   "divRendite": 0.89,
   "sektor": "Handel",
   "land": "China"
  },
  {
   "id": "mufg",
   "art": "aktie",
   "name": "Mitsubishi UFJ",
   "kuerzel": "MUFG",
   "kurs": 19.6083,
   "kursOriginal": 22.83,
   "waehrungOriginal": "USD",
   "kgv": 21.08,
   "gewinnJeAktie": 0.930185,
   "dividende": 0.380401,
   "divRendite": 1.94,
   "sektor": "Banken",
   "land": "Japan"
  },
  {
   "id": "arm",
   "art": "aktie",
   "name": "Arm Holdings",
   "kuerzel": "ARM",
   "kurs": 207.34,
   "kursOriginal": 241.41,
   "waehrungOriginal": "USD",
   "kgv": 260.5,
   "gewinnJeAktie": 0.795931,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Halbleiter",
   "land": "Grossbritannien"
  },
  {
   "id": "shel",
   "art": "aktie",
   "name": "Shell",
   "kuerzel": "SHEL",
   "kurs": 77.9095,
   "kursOriginal": 90.71,
   "waehrungOriginal": "USD",
   "kgv": 9.59,
   "gewinnJeAktie": 8.124,
   "dividende": 2.5944,
   "divRendite": 3.33,
   "sektor": "Energie",
   "land": "Grossbritannien"
  },
  {
   "id": "azn",
   "art": "aktie",
   "name": "AstraZeneca",
   "kuerzel": "AZN",
   "kurs": 138.95,
   "kursOriginal": 161.785,
   "waehrungOriginal": "USD",
   "kgv": 24.1,
   "gewinnJeAktie": 5.7656,
   "dividende": 2.779,
   "divRendite": 2,
   "sektor": "Pharma",
   "land": "Grossbritannien"
  },
  {
   "id": "hsbc",
   "art": "aktie",
   "name": "HSBC",
   "kuerzel": "HSBC",
   "kurs": 88.8259,
   "kursOriginal": 103.42,
   "waehrungOriginal": "USD",
   "kgv": 16.6,
   "gewinnJeAktie": 5.351,
   "dividende": 3.2066,
   "divRendite": 3.61,
   "sektor": "Banken",
   "land": "Grossbritannien"
  },
  {
   "id": "nvs",
   "art": "aktie",
   "name": "Novartis",
   "kuerzel": "NVS",
   "kurs": 131.49,
   "kursOriginal": 153.09,
   "waehrungOriginal": "USD",
   "kgv": 23.11,
   "gewinnJeAktie": 5.6897,
   "dividende": 2.6429,
   "divRendite": 2.01,
   "sektor": "Pharma",
   "land": "Schweiz"
  },
  {
   "id": "ry",
   "art": "aktie",
   "name": "Royal Bank of Canada",
   "kuerzel": "RY",
   "kurs": 175.46,
   "kursOriginal": 204.29,
   "waehrungOriginal": "USD",
   "kgv": 18.07,
   "gewinnJeAktie": 9.71,
   "dividende": 4.2286,
   "divRendite": 2.41,
   "sektor": "Banken",
   "land": "Kanada"
  },
  {
   "id": "p911",
   "art": "aktie",
   "name": "Porsche AG",
   "kuerzel": "P911",
   "kurs": 45.95,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 49.53,
   "gewinnJeAktie": 0.927721,
   "dividende": 1.0385,
   "divRendite": 2.26,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "fre",
   "art": "aktie",
   "name": "Fresenius",
   "kuerzel": "FRE",
   "kurs": 45.855,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 16.65,
   "gewinnJeAktie": 2.7541,
   "dividende": 1.0363,
   "divRendite": 2.26,
   "sektor": "Gesundheit",
   "land": "Deutschland"
  },
  {
   "id": "fme",
   "art": "aktie",
   "name": "Fresenius Medical Care",
   "kuerzel": "FME",
   "kurs": 39.92,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 12,
   "gewinnJeAktie": 3.3267,
   "dividende": 1.4611,
   "divRendite": 3.66,
   "sektor": "Gesundheit",
   "land": "Deutschland"
  },
  {
   "id": "sy1",
   "art": "aktie",
   "name": "Symrise",
   "kuerzel": "SY1",
   "kurs": 92.9,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 51.96,
   "gewinnJeAktie": 1.7879,
   "dividende": 1.3285,
   "divRendite": 1.43,
   "sektor": "Chemie",
   "land": "Deutschland"
  },
  {
   "id": "srt3",
   "art": "aktie",
   "name": "Sartorius Vorzuege",
   "kuerzel": "SRT3",
   "kurs": 253.5,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 78.62,
   "gewinnJeAktie": 3.2244,
   "dividende": 0.8112,
   "divRendite": 0.32,
   "sektor": "Gesundheit",
   "land": "Deutschland"
  },
  {
   "id": "tlx",
   "art": "aktie",
   "name": "Talanx",
   "kuerzel": "TLX",
   "kurs": 125.4,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 12.31,
   "gewinnJeAktie": 10.1868,
   "dividende": 3.8372,
   "divRendite": 3.06,
   "sektor": "Versicherung",
   "land": "Deutschland"
  },
  {
   "id": "pub",
   "art": "aktie",
   "name": "Publicis Groupe",
   "kuerzel": "PUB",
   "kurs": 101.65,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 15.78,
   "gewinnJeAktie": 6.4417,
   "dividende": 3.7407,
   "divRendite": 3.68,
   "sektor": "Medien",
   "land": "Frankreich"
  },
  {
   "id": "stla",
   "art": "aktie",
   "name": "Stellantis",
   "kuerzel": "STLA",
   "kurs": 4.681,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Automobil",
   "land": "Niederlande"
  },
  {
   "id": "prx",
   "art": "aktie",
   "name": "Prosus",
   "kuerzel": "PRX",
   "kurs": 38.69,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 8.38,
   "gewinnJeAktie": 4.6169,
   "dividende": 0.286306,
   "divRendite": 0.74,
   "sektor": "Technologie",
   "land": "Niederlande"
  },
  {
   "id": "g",
   "art": "aktie",
   "name": "Generali",
   "kuerzel": "G",
   "kurs": 44.13,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 14.9,
   "gewinnJeAktie": 2.9617,
   "dividende": 1.6902,
   "divRendite": 3.83,
   "sektor": "Versicherung",
   "land": "Italien"
  },
  {
   "id": "bbva",
   "art": "aktie",
   "name": "BBVA",
   "kuerzel": "BBVA",
   "kurs": 25.04,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 13.03,
   "gewinnJeAktie": 1.9217,
   "dividende": 0.933992,
   "divRendite": 3.73,
   "sektor": "Banken",
   "land": "Spanien"
  },
  {
   "id": "tef",
   "art": "aktie",
   "name": "Telefonica",
   "kuerzel": "TEF",
   "kurs": 3.625,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0.295438,
   "divRendite": 8.15,
   "sektor": "Telekom",
   "land": "Spanien"
  },
  {
   "id": "kbc",
   "art": "aktie",
   "name": "KBC Group",
   "kuerzel": "KBC",
   "kurs": 132.4,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 14.59,
   "gewinnJeAktie": 9.0747,
   "dividende": 5.1504,
   "divRendite": 3.89,
   "sektor": "Banken",
   "land": "Belgien"
  },
  {
   "id": "ulvr",
   "art": "aktie",
   "name": "Unilever",
   "kuerzel": "ULVR",
   "kurs": 55.7163,
   "kursOriginal": 4776,
   "waehrungOriginal": "GBX",
   "kgv": 21.65,
   "gewinnJeAktie": 2.5735,
   "dividende": 2.0671,
   "divRendite": 3.71,
   "sektor": "Konsum",
   "land": "Grossbritannien"
  },
  {
   "id": "bp1",
   "art": "aktie",
   "name": "BP",
   "kuerzel": "BP1",
   "kurs": 6.0021,
   "kursOriginal": 514.5,
   "waehrungOriginal": "GBX",
   "kgv": 19.84,
   "gewinnJeAktie": 0.302525,
   "dividende": 0.279098,
   "divRendite": 4.65,
   "sektor": "Energie",
   "land": "Grossbritannien"
  },
  {
   "id": "gsk",
   "art": "aktie",
   "name": "GSK",
   "kuerzel": "GSK",
   "kurs": 21.6227,
   "kursOriginal": 1853.5,
   "waehrungOriginal": "GBX",
   "kgv": 15.72,
   "gewinnJeAktie": 1.3755,
   "dividende": 0.823825,
   "divRendite": 3.81,
   "sektor": "Pharma",
   "land": "Grossbritannien"
  },
  {
   "id": "dge",
   "art": "aktie",
   "name": "Diageo",
   "kuerzel": "DGE",
   "kurs": 19.937,
   "kursOriginal": 1709,
   "waehrungOriginal": "GBX",
   "kgv": 28.98,
   "gewinnJeAktie": 0.687957,
   "dividende": 0.424658,
   "divRendite": 2.13,
   "sektor": "Nahrung",
   "land": "Grossbritannien"
  },
  {
   "id": "rio",
   "art": "aktie",
   "name": "Rio Tinto",
   "kuerzel": "RIO",
   "kurs": 89.524,
   "kursOriginal": 7674,
   "waehrungOriginal": "GBX",
   "kgv": 13.82,
   "gewinnJeAktie": 6.4779,
   "dividende": 3.4467,
   "divRendite": 3.85,
   "sektor": "Industrie",
   "land": "Grossbritannien"
  },
  {
   "id": "barc",
   "art": "aktie",
   "name": "Barclays",
   "kuerzel": "BARC",
   "kurs": 5.7939,
   "kursOriginal": 496.65,
   "waehrungOriginal": "GBX",
   "kgv": 10.24,
   "gewinnJeAktie": 0.565811,
   "dividende": 0.100234,
   "divRendite": 1.73,
   "sektor": "Banken",
   "land": "Grossbritannien"
  },
  {
   "id": "lloy",
   "art": "aktie",
   "name": "Lloyds Banking Group",
   "kuerzel": "LLOY",
   "kurs": 1.2827,
   "kursOriginal": 109.95,
   "waehrungOriginal": "GBX",
   "kgv": 13.7,
   "gewinnJeAktie": 0.0936277,
   "dividende": 0.0415595,
   "divRendite": 3.24,
   "sektor": "Banken",
   "land": "Grossbritannien"
  },
  {
   "id": "ba1",
   "art": "aktie",
   "name": "BAE Systems",
   "kuerzel": "BA1",
   "kurs": 23.8451,
   "kursOriginal": 2044,
   "waehrungOriginal": "GBX",
   "kgv": 29.97,
   "gewinnJeAktie": 0.795632,
   "dividende": 0.400598,
   "divRendite": 1.68,
   "sektor": "Ruestung",
   "land": "Grossbritannien"
  },
  {
   "id": "rr",
   "art": "aktie",
   "name": "Rolls-Royce",
   "kuerzel": "RR",
   "kurs": 17.8511,
   "kursOriginal": 1530.2,
   "waehrungOriginal": "GBX",
   "kgv": 42.29,
   "gewinnJeAktie": 0.422112,
   "dividende": 0.141024,
   "divRendite": 0.79,
   "sektor": "Luftfahrt",
   "land": "Grossbritannien"
  },
  {
   "id": "nesn",
   "art": "aktie",
   "name": "Nestle",
   "kuerzel": "NESN",
   "kurs": 83.9598,
   "kursOriginal": 78.62,
   "waehrungOriginal": "CHF",
   "kgv": 27.15,
   "gewinnJeAktie": 3.0924,
   "dividende": 3.2828,
   "divRendite": 3.91,
   "sektor": "Nahrung",
   "land": "Schweiz"
  },
  {
   "id": "ro",
   "art": "aktie",
   "name": "Roche",
   "kuerzel": "RO",
   "kurs": 390.86,
   "kursOriginal": 366,
   "waehrungOriginal": "CHF",
   "kgv": 23.58,
   "gewinnJeAktie": 16.5759,
   "dividende": 11.1395,
   "divRendite": 2.85,
   "sektor": "Pharma",
   "land": "Schweiz"
  },
  {
   "id": "zurn",
   "art": "aktie",
   "name": "Zurich Insurance",
   "kuerzel": "ZURN",
   "kurs": 634.13,
   "kursOriginal": 593.8,
   "waehrungOriginal": "CHF",
   "kgv": 14.82,
   "gewinnJeAktie": 42.7888,
   "dividende": 32.4675,
   "divRendite": 5.12,
   "sektor": "Versicherung",
   "land": "Schweiz"
  },
  {
   "id": "abbn",
   "art": "aktie",
   "name": "ABB",
   "kuerzel": "ABBN",
   "kurs": 85.5404,
   "kursOriginal": 80.1,
   "waehrungOriginal": "CHF",
   "kgv": 36.07,
   "gewinnJeAktie": 2.3715,
   "dividende": 1.0008,
   "divRendite": 1.17,
   "sektor": "Industrie",
   "land": "Schweiz"
  },
  {
   "id": "ubsg",
   "art": "aktie",
   "name": "UBS Group",
   "kuerzel": "UBSG",
   "kurs": 47.5545,
   "kursOriginal": 44.53,
   "waehrungOriginal": "CHF",
   "kgv": 18.47,
   "gewinnJeAktie": 2.5747,
   "dividende": 0.974867,
   "divRendite": 2.05,
   "sektor": "Banken",
   "land": "Schweiz"
  },
  {
   "id": "cfr",
   "art": "aktie",
   "name": "Richemont",
   "kuerzel": "CFR",
   "kurs": 207.76,
   "kursOriginal": 194.55,
   "waehrungOriginal": "CHF",
   "kgv": 35.16,
   "gewinnJeAktie": 5.909,
   "dividende": 3.6566,
   "divRendite": 1.76,
   "sektor": "Luxus",
   "land": "Schweiz"
  },
  {
   "id": "holn",
   "art": "aktie",
   "name": "Holcim",
   "kuerzel": "HOLN",
   "kurs": 77.9795,
   "kursOriginal": 73.02,
   "waehrungOriginal": "CHF",
   "kgv": 103.39,
   "gewinnJeAktie": 0.754227,
   "dividende": 1.9027,
   "divRendite": 2.44,
   "sektor": "Bau",
   "land": "Schweiz"
  },
  {
   "id": "sika",
   "art": "aktie",
   "name": "Sika",
   "kuerzel": "SIKA",
   "kurs": 206.11,
   "kursOriginal": 193,
   "waehrungOriginal": "CHF",
   "kgv": 29.56,
   "gewinnJeAktie": 6.9726,
   "dividende": 4.1222,
   "divRendite": 2,
   "sektor": "Chemie",
   "land": "Schweiz"
  },
  {
   "id": "sren",
   "art": "aktie",
   "name": "Swiss Re",
   "kuerzel": "SREN",
   "kurs": 150.74,
   "kursOriginal": 141.15,
   "waehrungOriginal": "CHF",
   "kgv": 10.55,
   "gewinnJeAktie": 14.2882,
   "dividende": 6.8888,
   "divRendite": 4.57,
   "sektor": "Versicherung",
   "land": "Schweiz"
  },
  {
   "id": "lonn",
   "art": "aktie",
   "name": "Lonza",
   "kuerzel": "LONN",
   "kurs": 623.45,
   "kursOriginal": 583.8,
   "waehrungOriginal": "CHF",
   "kgv": 38.03,
   "gewinnJeAktie": 16.3936,
   "dividende": 5.4864,
   "divRendite": 0.88,
   "sektor": "Pharma",
   "land": "Schweiz"
  },
  {
   "id": "7203",
   "art": "aktie",
   "name": "Toyota Motor",
   "kuerzel": "7203",
   "kurs": 16.7599,
   "kursOriginal": 3116,
   "waehrungOriginal": "JPY",
   "kgv": 8.92,
   "gewinnJeAktie": 1.8789,
   "dividende": 0.554753,
   "divRendite": 3.31,
   "sektor": "Automobil",
   "land": "Japan"
  },
  {
   "id": "6758",
   "art": "aktie",
   "name": "Sony Group",
   "kuerzel": "6758",
   "kurs": 21.1274,
   "kursOriginal": 3928,
   "waehrungOriginal": "JPY",
   "kgv": 20.66,
   "gewinnJeAktie": 1.0226,
   "dividende": 0.188034,
   "divRendite": 0.89,
   "sektor": "Technologie",
   "land": "Japan"
  },
  {
   "id": "7974",
   "art": "aktie",
   "name": "Nintendo",
   "kuerzel": "7974",
   "kurs": 48.3703,
   "kursOriginal": 8993,
   "waehrungOriginal": "JPY",
   "kgv": 21.95,
   "gewinnJeAktie": 2.2037,
   "dividende": 0.914199,
   "divRendite": 1.89,
   "sektor": "Medien",
   "land": "Japan"
  },
  {
   "id": "6861",
   "art": "aktie",
   "name": "Keyence",
   "kuerzel": "6861",
   "kurs": 446.21,
   "kursOriginal": 82960,
   "waehrungOriginal": "JPY",
   "kgv": 40.88,
   "gewinnJeAktie": 10.9151,
   "dividende": 3.0788,
   "divRendite": 0.69,
   "sektor": "Industrie",
   "land": "Japan"
  },
  {
   "id": "8035",
   "art": "aktie",
   "name": "Tokyo Electron",
   "kuerzel": "8035",
   "kurs": 302.44,
   "kursOriginal": 56230,
   "waehrungOriginal": "JPY",
   "kgv": 41.52,
   "gewinnJeAktie": 7.2842,
   "dividende": 4.1434,
   "divRendite": 1.37,
   "sektor": "Halbleiter",
   "land": "Japan"
  },
  {
   "id": "6857",
   "art": "aktie",
   "name": "Advantest",
   "kuerzel": "6857",
   "kurs": 189.71,
   "kursOriginal": 35270,
   "waehrungOriginal": "JPY",
   "kgv": 55.96,
   "gewinnJeAktie": 3.3901,
   "dividende": 0.322507,
   "divRendite": 0.17,
   "sektor": "Halbleiter",
   "land": "Japan"
  },
  {
   "id": "9984",
   "art": "aktie",
   "name": "SoftBank Group",
   "kuerzel": "9984",
   "kurs": 27.7593,
   "kursOriginal": 5161,
   "waehrungOriginal": "JPY",
   "kgv": 6.05,
   "gewinnJeAktie": 4.5883,
   "dividende": 0.0555186,
   "divRendite": 0.2,
   "sektor": "Technologie",
   "land": "Japan"
  },
  {
   "id": "6501",
   "art": "aktie",
   "name": "Hitachi",
   "kuerzel": "6501",
   "kurs": 29.8515,
   "kursOriginal": 5550,
   "waehrungOriginal": "JPY",
   "kgv": 31.37,
   "gewinnJeAktie": 0.951594,
   "dividende": 0.319411,
   "divRendite": 1.07,
   "sektor": "Industrie",
   "land": "Japan"
  },
  {
   "id": "8058",
   "art": "aktie",
   "name": "Mitsubishi Corporation",
   "kuerzel": "8058",
   "kurs": 25.7423,
   "kursOriginal": 4786,
   "waehrungOriginal": "JPY",
   "kgv": 19.81,
   "gewinnJeAktie": 1.2995,
   "dividende": 0.692468,
   "divRendite": 2.69,
   "sektor": "Handel",
   "land": "Japan"
  },
  {
   "id": "4063",
   "art": "aktie",
   "name": "Shin-Etsu Chemical",
   "kuerzel": "4063",
   "kurs": 32.2773,
   "kursOriginal": 6001,
   "waehrungOriginal": "JPY",
   "kgv": 23.42,
   "gewinnJeAktie": 1.3782,
   "dividende": 0.606813,
   "divRendite": 1.88,
   "sektor": "Chemie",
   "land": "Japan"
  },
  {
   "id": "4502",
   "art": "aktie",
   "name": "Takeda Pharmaceutical",
   "kuerzel": "4502",
   "kurs": 31.1962,
   "kursOriginal": 5800,
   "waehrungOriginal": "JPY",
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 1.1043,
   "divRendite": 3.54,
   "sektor": "Pharma",
   "land": "Japan"
  },
  {
   "id": "7267",
   "art": "aktie",
   "name": "Honda Motor",
   "kuerzel": "7267",
   "kurs": 9.1572,
   "kursOriginal": 1702.5,
   "waehrungOriginal": "JPY",
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0.374529,
   "divRendite": 4.09,
   "sektor": "Automobil",
   "land": "Japan"
  },
  {
   "id": "8316",
   "art": "aktie",
   "name": "Sumitomo Mitsui Financial",
   "kuerzel": "8316",
   "kurs": 37.1235,
   "kursOriginal": 6902,
   "waehrungOriginal": "JPY",
   "kgv": 20.94,
   "gewinnJeAktie": 1.7729,
   "dividende": 1.0172,
   "divRendite": 2.74,
   "sektor": "Banken",
   "land": "Japan"
  },
  {
   "id": "9983",
   "art": "aktie",
   "name": "Fast Retailing",
   "kuerzel": "9983",
   "kurs": 383.28,
   "kursOriginal": 71260,
   "waehrungOriginal": "JPY",
   "kgv": 42.11,
   "gewinnJeAktie": 9.1019,
   "dividende": 3.2579,
   "divRendite": 0.85,
   "sektor": "Handel",
   "land": "Japan"
  },
  {
   "id": "9432",
   "art": "aktie",
   "name": "Nippon Telegraph & Telephone",
   "kuerzel": "9432",
   "kurs": 0.906842,
   "kursOriginal": 168.6,
   "waehrungOriginal": "JPY",
   "kgv": 13.13,
   "gewinnJeAktie": 0.0690664,
   "dividende": 0.0303792,
   "divRendite": 3.35,
   "sektor": "Telekom",
   "land": "Japan"
  },
  {
   "id": "005930",
   "art": "aktie",
   "name": "Samsung Electronics",
   "kuerzel": "005930",
   "kurs": 160.59,
   "kursOriginal": 257000,
   "waehrungOriginal": "KRW",
   "kgv": 11.46,
   "gewinnJeAktie": 14.0131,
   "dividende": 1.2847,
   "divRendite": 0.8,
   "sektor": "Technologie",
   "land": "Suedkorea"
  },
  {
   "id": "005380",
   "art": "aktie",
   "name": "Hyundai Motor",
   "kuerzel": "005380",
   "kurs": 249.63,
   "kursOriginal": 399500,
   "waehrungOriginal": "KRW",
   "kgv": 12.82,
   "gewinnJeAktie": 19.4719,
   "dividende": 5.9911,
   "divRendite": 2.4,
   "sektor": "Automobil",
   "land": "Suedkorea"
  },
  {
   "id": "000270",
   "art": "aktie",
   "name": "Kia",
   "kuerzel": "000270",
   "kurs": 79.9805,
   "kursOriginal": 128000,
   "waehrungOriginal": "KRW",
   "kgv": 7.04,
   "gewinnJeAktie": 11.3609,
   "dividende": 3.967,
   "divRendite": 4.96,
   "sektor": "Automobil",
   "land": "Suedkorea"
  },
  {
   "id": "035420",
   "art": "aktie",
   "name": "NAVER",
   "kuerzel": "035420",
   "kurs": 137.78,
   "kursOriginal": 220500,
   "waehrungOriginal": "KRW",
   "kgv": 16.46,
   "gewinnJeAktie": 8.3706,
   "dividende": 1.6671,
   "divRendite": 1.21,
   "sektor": "Technologie",
   "land": "Suedkorea"
  },
  {
   "id": "207940",
   "art": "aktie",
   "name": "Samsung Biologics",
   "kuerzel": "207940",
   "kurs": 928.52,
   "kursOriginal": 1486000,
   "waehrungOriginal": "KRW",
   "kgv": 37.54,
   "gewinnJeAktie": 24.7342,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Pharma",
   "land": "Suedkorea"
  },
  {
   "id": "005490",
   "art": "aktie",
   "name": "POSCO Holdings",
   "kuerzel": "005490",
   "kurs": 210.89,
   "kursOriginal": 337500,
   "waehrungOriginal": "KRW",
   "kgv": 19.05,
   "gewinnJeAktie": 11.0703,
   "dividende": 4.9981,
   "divRendite": 2.37,
   "sektor": "Industrie",
   "land": "Suedkorea"
  },
  {
   "id": "373220",
   "art": "aktie",
   "name": "LG Energy Solution",
   "kuerzel": "373220",
   "kurs": 231.19,
   "kursOriginal": 370000,
   "waehrungOriginal": "KRW",
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Industrie",
   "land": "Suedkorea"
  },
  {
   "id": "0700",
   "art": "aktie",
   "name": "Tencent Holdings",
   "kuerzel": "0700",
   "kurs": 49.8707,
   "kursOriginal": 455.2,
   "waehrungOriginal": "HKD",
   "kgv": 15.49,
   "gewinnJeAktie": 3.2195,
   "dividende": 0.5785,
   "divRendite": 1.16,
   "sektor": "Technologie",
   "land": "Hongkong"
  },
  {
   "id": "1299",
   "art": "aktie",
   "name": "AIA Group",
   "kuerzel": "1299",
   "kurs": 8.2716,
   "kursOriginal": 75.5,
   "waehrungOriginal": "HKD",
   "kgv": 12.6,
   "gewinnJeAktie": 0.656476,
   "dividende": 0.21258,
   "divRendite": 2.57,
   "sektor": "Versicherung",
   "land": "Hongkong"
  },
  {
   "id": "0388",
   "art": "aktie",
   "name": "Hong Kong Exchanges",
   "kuerzel": "0388",
   "kurs": 46.4525,
   "kursOriginal": 424,
   "waehrungOriginal": "HKD",
   "kgv": 27.13,
   "gewinnJeAktie": 1.7122,
   "dividende": 1.6398,
   "divRendite": 3.53,
   "sektor": "Finanzen",
   "land": "Hongkong"
  },
  {
   "id": "shop",
   "art": "aktie",
   "name": "Shopify",
   "kuerzel": "SHOP",
   "kurs": 131.9,
   "kursOriginal": 212.75,
   "waehrungOriginal": "CAD",
   "kgv": 100.54,
   "gewinnJeAktie": 1.3119,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Technologie",
   "land": "Kanada"
  },
  {
   "id": "td",
   "art": "aktie",
   "name": "Toronto-Dominion Bank",
   "kuerzel": "TD",
   "kurs": 104.35,
   "kursOriginal": 168.32,
   "waehrungOriginal": "CAD",
   "kgv": 17.77,
   "gewinnJeAktie": 5.8723,
   "dividende": 2.7861,
   "divRendite": 2.67,
   "sektor": "Banken",
   "land": "Kanada"
  },
  {
   "id": "bns",
   "art": "aktie",
   "name": "Bank of Nova Scotia",
   "kuerzel": "BNS",
   "kurs": 79.473,
   "kursOriginal": 128.19,
   "waehrungOriginal": "CAD",
   "kgv": 16.83,
   "gewinnJeAktie": 4.7221,
   "dividende": 2.8133,
   "divRendite": 3.54,
   "sektor": "Banken",
   "land": "Kanada"
  },
  {
   "id": "bmo",
   "art": "aktie",
   "name": "Bank of Montreal",
   "kuerzel": "BMO",
   "kurs": 147.42,
   "kursOriginal": 237.79,
   "waehrungOriginal": "CAD",
   "kgv": 19.45,
   "gewinnJeAktie": 7.5794,
   "dividende": 4.2015,
   "divRendite": 2.85,
   "sektor": "Banken",
   "land": "Kanada"
  },
  {
   "id": "enb",
   "art": "aktie",
   "name": "Enbridge",
   "kuerzel": "ENB",
   "kurs": 43.261,
   "kursOriginal": 69.78,
   "waehrungOriginal": "CAD",
   "kgv": 26.75,
   "gewinnJeAktie": 1.6172,
   "dividende": 2.4226,
   "divRendite": 5.6,
   "sektor": "Energie",
   "land": "Kanada"
  },
  {
   "id": "cnq",
   "art": "aktie",
   "name": "Canadian Natural Resources",
   "kuerzel": "CNQ",
   "kurs": 42.2226,
   "kursOriginal": 68.105,
   "waehrungOriginal": "CAD",
   "kgv": 12.28,
   "gewinnJeAktie": 3.4383,
   "dividende": 1.5242,
   "divRendite": 3.61,
   "sektor": "Energie",
   "land": "Kanada"
  },
  {
   "id": "cnr",
   "art": "aktie",
   "name": "Canadian National Railway",
   "kuerzel": "CNR",
   "kurs": 108.11,
   "kursOriginal": 174.385,
   "waehrungOriginal": "CAD",
   "kgv": 22.48,
   "gewinnJeAktie": 4.8092,
   "dividende": 2.2595,
   "divRendite": 2.09,
   "sektor": "Logistik",
   "land": "Kanada"
  },
  {
   "id": "cp",
   "art": "aktie",
   "name": "Canadian Pacific Kansas City",
   "kuerzel": "CP",
   "kurs": 80.7316,
   "kursOriginal": 130.22,
   "waehrungOriginal": "CAD",
   "kgv": 30.27,
   "gewinnJeAktie": 2.667,
   "dividende": 0.661999,
   "divRendite": 0.82,
   "sektor": "Logistik",
   "land": "Kanada"
  },
  {
   "id": "bce",
   "art": "aktie",
   "name": "BCE",
   "kuerzel": "BCE",
   "kurs": 20.124,
   "kursOriginal": 32.46,
   "waehrungOriginal": "CAD",
   "kgv": 4.83,
   "gewinnJeAktie": 4.1665,
   "dividende": 1.0746,
   "divRendite": 5.34,
   "sektor": "Telekom",
   "land": "Kanada"
  },
  {
   "id": "bn1",
   "art": "aktie",
   "name": "Brookfield Corporation",
   "kuerzel": "BN1",
   "kurs": 35.5983,
   "kursOriginal": 57.42,
   "waehrungOriginal": "CAD",
   "kgv": 75.24,
   "gewinnJeAktie": 0.47313,
   "dividende": 0.238509,
   "divRendite": 0.67,
   "sektor": "Finanzen",
   "land": "Kanada"
  },
  {
   "id": "ba",
   "art": "aktie",
   "name": "Boeing",
   "kuerzel": "BA",
   "kurs": 179.38,
   "kursOriginal": 208.85,
   "waehrungOriginal": "USD",
   "kgv": 78.27,
   "gewinnJeAktie": 2.2918,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Luftfahrt",
   "land": "USA"
  },
  {
   "id": "dis",
   "art": "aktie",
   "name": "Walt Disney",
   "kuerzel": "DIS",
   "kurs": 92.4933,
   "kursOriginal": 107.69,
   "waehrungOriginal": "USD",
   "kgv": 22.08,
   "gewinnJeAktie": 4.189,
   "dividende": 1.2857,
   "divRendite": 1.39,
   "sektor": "Medien",
   "land": "USA"
  },
  {
   "id": "vz",
   "art": "aktie",
   "name": "Verizon Communications",
   "kuerzel": "VZ",
   "kurs": 42.9357,
   "kursOriginal": 49.99,
   "waehrungOriginal": "USD",
   "kgv": 12.88,
   "gewinnJeAktie": 3.3335,
   "dividende": 2.4302,
   "divRendite": 5.66,
   "sektor": "Telekom",
   "land": "USA"
  },
  {
   "id": "lmt",
   "art": "aktie",
   "name": "Lockheed Martin",
   "kuerzel": "LMT",
   "kurs": 483.76,
   "kursOriginal": 563.24,
   "waehrungOriginal": "USD",
   "kgv": 20.85,
   "gewinnJeAktie": 23.2019,
   "dividende": 11.8521,
   "divRendite": 2.45,
   "sektor": "Ruestung",
   "land": "USA"
  },
  {
   "id": "amt",
   "art": "aktie",
   "name": "American Tower",
   "kuerzel": "AMT",
   "kurs": 151.03,
   "kursOriginal": 175.85,
   "waehrungOriginal": "USD",
   "kgv": 23.96,
   "gewinnJeAktie": 6.3034,
   "dividende": 6.1469,
   "divRendite": 4.07,
   "sektor": "Immobilien",
   "land": "USA"
  },
  {
   "id": "crm",
   "art": "aktie",
   "name": "Salesforce",
   "kuerzel": "CRM",
   "kurs": 223.74,
   "kursOriginal": 260.5,
   "waehrungOriginal": "USD",
   "kgv": 23.36,
   "gewinnJeAktie": 9.5779,
   "dividende": 1.5214,
   "divRendite": 0.68,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "adbe",
   "art": "aktie",
   "name": "Adobe",
   "kuerzel": "ADBE",
   "kurs": 250.91,
   "kursOriginal": 292.14,
   "waehrungOriginal": "USD",
   "kgv": 16.54,
   "gewinnJeAktie": 15.1699,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "qcom",
   "art": "aktie",
   "name": "Qualcomm",
   "kuerzel": "QCOM",
   "kurs": 140.01,
   "kursOriginal": 163.01,
   "waehrungOriginal": "USD",
   "kgv": 19.17,
   "gewinnJeAktie": 7.3036,
   "dividende": 3.1642,
   "divRendite": 2.26,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "ibm",
   "art": "aktie",
   "name": "IBM",
   "kuerzel": "IBM",
   "kurs": 202.67,
   "kursOriginal": 235.97,
   "waehrungOriginal": "USD",
   "kgv": 21.23,
   "gewinnJeAktie": 9.5464,
   "dividende": 5.7964,
   "divRendite": 2.86,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "pfe",
   "art": "aktie",
   "name": "Pfizer",
   "kuerzel": "PFE",
   "kurs": 23.9028,
   "kursOriginal": 27.83,
   "waehrungOriginal": "USD",
   "kgv": 36.83,
   "gewinnJeAktie": 0.649004,
   "dividende": 1.4772,
   "divRendite": 6.18,
   "sektor": "Pharma",
   "land": "USA"
  },
  {
   "id": "abbv",
   "art": "aktie",
   "name": "AbbVie",
   "kuerzel": "ABBV",
   "kurs": 219.96,
   "kursOriginal": 256.1,
   "waehrungOriginal": "USD",
   "kgv": 72.93,
   "gewinnJeAktie": 3.016,
   "dividende": 5.9389,
   "divRendite": 2.7,
   "sektor": "Pharma",
   "land": "USA"
  },
  {
   "id": "mcd",
   "art": "aktie",
   "name": "McDonald's",
   "kuerzel": "MCD",
   "kurs": 226.34,
   "kursOriginal": 263.53,
   "waehrungOriginal": "USD",
   "kgv": 21.12,
   "gewinnJeAktie": 10.7169,
   "dividende": 6.3828,
   "divRendite": 2.82,
   "sektor": "Nahrung",
   "land": "USA"
  },
  {
   "id": "nke",
   "art": "aktie",
   "name": "Nike",
   "kuerzel": "NKE",
   "kurs": 33.7069,
   "kursOriginal": 39.245,
   "waehrungOriginal": "USD",
   "kgv": 18.3,
   "gewinnJeAktie": 1.8419,
   "dividende": 1.4089,
   "divRendite": 4.18,
   "sektor": "Konsum",
   "land": "USA"
  },
  {
   "id": "pep",
   "art": "aktie",
   "name": "PepsiCo",
   "kuerzel": "PEP",
   "kurs": 120.93,
   "kursOriginal": 140.8,
   "waehrungOriginal": "USD",
   "kgv": 18.31,
   "gewinnJeAktie": 6.6046,
   "dividende": 5.0912,
   "divRendite": 4.21,
   "sektor": "Nahrung",
   "land": "USA"
  },
  {
   "id": "coin",
   "art": "aktie",
   "name": "Coinbase",
   "kuerzel": "COIN",
   "kurs": 151.44,
   "kursOriginal": 176.32,
   "waehrungOriginal": "USD",
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Finanzen",
   "land": "USA"
  },
  {
   "id": "voo",
   "art": "etf",
   "name": "Vanguard S&P 500 ETF",
   "kuerzel": "VOO",
   "kurs": 607.34,
   "kursOriginal": 707.13,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 1040,
   "anzahlPositionen": 518,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "USA breit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "qqq",
   "art": "etf",
   "name": "Invesco QQQ Trust",
   "kuerzel": "QQQ",
   "kurs": 615.29,
   "kursOriginal": 716.38,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 487.6,
   "anzahlPositionen": 105,
   "ter": 0.18,
   "ausschuettend": true,
   "sektor": "USA Technologie",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vt",
   "art": "etf",
   "name": "Vanguard Total World Stock ETF",
   "kuerzel": "VT",
   "kurs": 138.28,
   "kursOriginal": 160.995,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 81.8,
   "anzahlPositionen": 10118,
   "ter": 0.06,
   "ausschuettend": true,
   "sektor": "Welt",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vea",
   "art": "etf",
   "name": "Vanguard FTSE Developed Markets ETF",
   "kuerzel": "VEA",
   "kurs": 62.7244,
   "kursOriginal": 73.03,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 240.3,
   "anzahlPositionen": 3877,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "Welt ohne USA",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vwo",
   "art": "etf",
   "name": "Vanguard FTSE Emerging Markets ETF",
   "kuerzel": "VWO",
   "kurs": 52.1429,
   "kursOriginal": 60.71,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 127.1,
   "anzahlPositionen": 5063,
   "ter": 0.06,
   "ausschuettend": true,
   "sektor": "Schwellenlaender",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "efa",
   "art": "etf",
   "name": "iShares MSCI EAFE ETF",
   "kuerzel": "EFA",
   "kurs": 92.4762,
   "kursOriginal": 107.67,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 80.3,
   "anzahlPositionen": 699,
   "ter": 0.32,
   "ausschuettend": true,
   "sektor": "Europa/Asien",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "iwm",
   "art": "etf",
   "name": "iShares Russell 2000 ETF",
   "kuerzel": "IWM",
   "kurs": 254.32,
   "kursOriginal": 296.11,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 80.9,
   "anzahlPositionen": 1971,
   "ter": 0.19,
   "ausschuettend": true,
   "sektor": "USA klein",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "ijh",
   "art": "etf",
   "name": "iShares Core S&P Mid-Cap ETF",
   "kuerzel": "IJH",
   "kurs": 65.1464,
   "kursOriginal": 75.85,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 125,
   "anzahlPositionen": 414,
   "ter": 0.05,
   "ausschuettend": true,
   "sektor": "USA mittel",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "dia",
   "art": "etf",
   "name": "SPDR Dow Jones Industrial Average ETF",
   "kuerzel": "DIA",
   "kurs": 459.31,
   "kursOriginal": 534.77,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 45.5,
   "anzahlPositionen": 31,
   "ter": 0.16,
   "ausschuettend": true,
   "sektor": "USA Standard",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "rsp",
   "art": "etf",
   "name": "Invesco S&P 500 Equal Weight ETF",
   "kuerzel": "RSP",
   "kurs": 189.5,
   "kursOriginal": 220.63,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 100.5,
   "anzahlPositionen": 509,
   "ter": 0.2,
   "ausschuettend": true,
   "sektor": "USA breit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vug",
   "art": "etf",
   "name": "Vanguard Growth ETF",
   "kuerzel": "VUG",
   "kurs": 76.1144,
   "kursOriginal": 88.62,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 224.7,
   "anzahlPositionen": 151,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "USA Wachstum",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vtv",
   "art": "etf",
   "name": "Vanguard Value ETF",
   "kuerzel": "VTV",
   "kurs": 193.28,
   "kursOriginal": 225.04,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 193.5,
   "anzahlPositionen": 326,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "USA Substanz",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "schd",
   "art": "etf",
   "name": "Schwab US Dividend Equity ETF",
   "kuerzel": "SCHD",
   "kurs": 29.9236,
   "kursOriginal": 34.84,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 112.2,
   "anzahlPositionen": 103,
   "ter": 0.06,
   "ausschuettend": true,
   "sektor": "Dividenden",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vym",
   "art": "etf",
   "name": "Vanguard High Dividend Yield ETF",
   "kuerzel": "VYM",
   "kurs": 140.82,
   "kursOriginal": 163.96,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 83.5,
   "anzahlPositionen": 618,
   "ter": 0.04,
   "ausschuettend": true,
   "sektor": "Dividenden",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlk",
   "art": "etf",
   "name": "Technology Select Sector SPDR",
   "kuerzel": "XLK",
   "kurs": 159.86,
   "kursOriginal": 186.13,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 118.6,
   "anzahlPositionen": 76,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Technologie",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "soxx",
   "art": "etf",
   "name": "iShares Semiconductor ETF",
   "kuerzel": "SOXX",
   "kurs": 437.59,
   "kursOriginal": 509.49,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 41.5,
   "anzahlPositionen": 34,
   "ter": 0.33,
   "ausschuettend": true,
   "sektor": "Halbleiter",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlv",
   "art": "etf",
   "name": "Health Care Select Sector SPDR",
   "kuerzel": "XLV",
   "kurs": 146.83,
   "kursOriginal": 170.95,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 45.1,
   "anzahlPositionen": 63,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Gesundheit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlf",
   "art": "etf",
   "name": "Financial Select Sector SPDR",
   "kuerzel": "XLF",
   "kurs": 49.8755,
   "kursOriginal": 58.07,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 56.1,
   "anzahlPositionen": 80,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Finanzen",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xle",
   "art": "etf",
   "name": "Energy Select Sector SPDR",
   "kuerzel": "XLE",
   "kurs": 53.6803,
   "kursOriginal": 62.5,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 40.1,
   "anzahlPositionen": 24,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Energie",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vnq",
   "art": "etf",
   "name": "Vanguard Real Estate ETF",
   "kuerzel": "VNQ",
   "kurs": 83.6984,
   "kursOriginal": 97.45,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 39.4,
   "anzahlPositionen": 157,
   "ter": 0.13,
   "ausschuettend": true,
   "sektor": "Immobilien",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "gld",
   "art": "etf",
   "name": "SPDR Gold Shares",
   "kuerzel": "GLD",
   "kurs": 351.34,
   "kursOriginal": 409.06,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 155.5,
   "anzahlPositionen": 2,
   "ter": 0.4,
   "ausschuettend": true,
   "sektor": "Rohstoffe",
   "anlageklasse": "Rohstoff",
   "land": null
  },
  {
   "id": "agg",
   "art": "etf",
   "name": "iShares Core US Aggregate Bond ETF",
   "kuerzel": "AGG",
   "kurs": 83.7542,
   "kursOriginal": 97.515,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 138.9,
   "anzahlPositionen": 13386,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "Anleihen",
   "anlageklasse": "Anleihen",
   "land": null
  },
  {
   "id": "tlt",
   "art": "etf",
   "name": "iShares 20+ Year Treasury Bond ETF",
   "kuerzel": "TLT",
   "kurs": 71.2273,
   "kursOriginal": 82.93,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 47.5,
   "anzahlPositionen": 48,
   "ter": 0.15,
   "ausschuettend": true,
   "sektor": "Anleihen",
   "anlageklasse": "Anleihen",
   "land": null
  },
  {
   "id": "vcit",
   "art": "etf",
   "name": "Vanguard Interm.-Term Corp. Bond ETF",
   "kuerzel": "VCIT",
   "kurs": 69.6985,
   "kursOriginal": 81.15,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 70.4,
   "anzahlPositionen": 2268,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "Anleihen",
   "anlageklasse": "Anleihen",
   "land": null
  },
  {
   "id": "ibit",
   "art": "etf",
   "name": "iShares Bitcoin Trust",
   "kuerzel": "IBIT",
   "kurs": 37.8081,
   "kursOriginal": 44.02,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 60.7,
   "anzahlPositionen": 2,
   "ter": 0.25,
   "ausschuettend": true,
   "sektor": "Krypto",
   "anlageklasse": "Krypto",
   "land": null
  },
  {
   "id": "spy",
   "art": "etf",
   "name": "SPDR S&P 500 ETF Trust",
   "kuerzel": "SPY",
   "kurs": 660.67,
   "kursOriginal": 769.22,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 807.5,
   "anzahlPositionen": 505,
   "ter": 0.09,
   "ausschuettend": true,
   "sektor": "USA breit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "ivv",
   "art": "etf",
   "name": "iShares Core S&P 500 ETF",
   "kuerzel": "IVV",
   "kurs": 663.88,
   "kursOriginal": 772.95,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 883.9,
   "anzahlPositionen": 508,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "USA breit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vti",
   "art": "etf",
   "name": "Vanguard Total Stock Market ETF",
   "kuerzel": "VTI",
   "kurs": 325.84,
   "kursOriginal": 379.38,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 688.8,
   "anzahlPositionen": 3498,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "USA breit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "iefa",
   "art": "etf",
   "name": "iShares Core MSCI EAFE ETF",
   "kuerzel": "IEFA",
   "kurs": 86.2321,
   "kursOriginal": 100.4,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 196,
   "anzahlPositionen": 2641,
   "ter": 0.07,
   "ausschuettend": true,
   "sektor": "Europa/Asien",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "iemg",
   "art": "etf",
   "name": "iShares Core MSCI Emerging Markets ETF",
   "kuerzel": "IEMG",
   "kurs": 70.3169,
   "kursOriginal": 81.87,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 160.6,
   "anzahlPositionen": 2896,
   "ter": 0.09,
   "ausschuettend": true,
   "sektor": "Schwellenlaender",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "ewj",
   "art": "etf",
   "name": "iShares MSCI Japan ETF",
   "kuerzel": "EWJ",
   "kurs": 82.2211,
   "kursOriginal": 95.73,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 22.7,
   "anzahlPositionen": 174,
   "ter": 0.49,
   "ausschuettend": true,
   "sektor": "Japan",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "ezu",
   "art": "etf",
   "name": "iShares MSCI Eurozone ETF",
   "kuerzel": "EZU",
   "kurs": 60.8821,
   "kursOriginal": 70.885,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 10,
   "anzahlPositionen": 226,
   "ter": 0.5,
   "ausschuettend": true,
   "sektor": "Eurozone",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "fxi",
   "art": "etf",
   "name": "iShares China Large-Cap ETF",
   "kuerzel": "FXI",
   "kurs": 30.426,
   "kursOriginal": 35.425,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 4.2,
   "anzahlPositionen": 59,
   "ter": 0.74,
   "ausschuettend": true,
   "sektor": "China",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "inda",
   "art": "etf",
   "name": "iShares MSCI India ETF",
   "kuerzel": "INDA",
   "kurs": 42.5277,
   "kursOriginal": 49.515,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 6.7,
   "anzahlPositionen": 173,
   "ter": 0.61,
   "ausschuettend": true,
   "sektor": "Indien",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xli",
   "art": "etf",
   "name": "Industrial Select Sector SPDR",
   "kuerzel": "XLI",
   "kurs": 152.03,
   "kursOriginal": 177.01,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 33,
   "anzahlPositionen": 86,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Industrie",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xly",
   "art": "etf",
   "name": "Consumer Discretionary Select Sector SPDR",
   "kuerzel": "XLY",
   "kurs": 100.35,
   "kursOriginal": 116.84,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 23.1,
   "anzahlPositionen": 50,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Konsum",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlp",
   "art": "etf",
   "name": "Consumer Staples Select Sector SPDR",
   "kuerzel": "XLP",
   "kurs": 73.3831,
   "kursOriginal": 85.44,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 14.8,
   "anzahlPositionen": 38,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Nahrung",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlu",
   "art": "etf",
   "name": "Utilities Select Sector SPDR",
   "kuerzel": "XLU",
   "kurs": 36.64,
   "kursOriginal": 42.66,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 22.3,
   "anzahlPositionen": 34,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Versorger",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlc",
   "art": "etf",
   "name": "Communication Services Select Sector SPDR",
   "kuerzel": "XLC",
   "kurs": 96.8092,
   "kursOriginal": 112.715,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 22.5,
   "anzahlPositionen": 26,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Medien",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "slv",
   "art": "etf",
   "name": "iShares Silver Trust",
   "kuerzel": "SLV",
   "kurs": 51.6448,
   "kursOriginal": 60.13,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 33.5,
   "anzahlPositionen": 1,
   "ter": 0.5,
   "ausschuettend": true,
   "sektor": "Rohstoffe",
   "anlageklasse": "Rohstoff",
   "land": null
  },
  {
   "id": "dbc",
   "art": "etf",
   "name": "Invesco DB Commodity Index Tracking Fund",
   "kuerzel": "DBC",
   "kurs": 26.4279,
   "kursOriginal": 30.77,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 1.9,
   "anzahlPositionen": 41,
   "ter": 0.84,
   "ausschuettend": true,
   "sektor": "Rohstoffe",
   "anlageklasse": "Rohstoff",
   "land": null
  },
  {
   "id": "lqd",
   "art": "etf",
   "name": "iShares iBoxx Investment Grade Corporate Bond ETF",
   "kuerzel": "LQD",
   "kurs": 91.3639,
   "kursOriginal": 106.375,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 33.2,
   "anzahlPositionen": 3143,
   "ter": 0.14,
   "ausschuettend": true,
   "sektor": "Anleihen",
   "anlageklasse": "Anleihen",
   "land": null
  },
  {
   "id": "hyg",
   "art": "etf",
   "name": "iShares iBoxx High Yield Corporate Bond ETF",
   "kuerzel": "HYG",
   "kurs": 68.4617,
   "kursOriginal": 79.71,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 16.5,
   "anzahlPositionen": 1333,
   "ter": 0.49,
   "ausschuettend": true,
   "sektor": "Anleihen",
   "anlageklasse": "Anleihen",
   "land": null
  },
  {
   "id": "etha",
   "art": "etf",
   "name": "iShares Ethereum Trust",
   "kuerzel": "ETHA",
   "kurs": 15.8035,
   "kursOriginal": 18.4,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 8.1,
   "anzahlPositionen": 2,
   "ter": 0.25,
   "ausschuettend": true,
   "sektor": "Krypto",
   "anlageklasse": "Krypto",
   "land": null
  },
  {
   "id": "btc",
   "art": "krypto",
   "name": "Bitcoin",
   "kuerzel": "BTC",
   "kurs": 67151,
   "marktkapitalisierung": 1348195827202,
   "umlaufmenge": 20076428,
   "hoechstmenge": 21000000,
   "allzeithoch": 107662,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "eth",
   "art": "krypto",
   "name": "Ethereum",
   "kuerzel": "ETH",
   "kurs": 2105.88,
   "marktkapitalisierung": 254133135174,
   "umlaufmenge": 120681206,
   "hoechstmenge": null,
   "allzeithoch": 4229.76,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "xrp",
   "art": "krypto",
   "name": "XRP",
   "kuerzel": "XRP",
   "kurs": 1.19,
   "marktkapitalisierung": 74940517672,
   "umlaufmenge": 62744504852,
   "hoechstmenge": 100000000000,
   "allzeithoch": 3.28,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "sol",
   "art": "krypto",
   "name": "Solana",
   "kuerzel": "SOL",
   "kurs": 89.8,
   "marktkapitalisierung": 52464072077,
   "umlaufmenge": 584162483,
   "hoechstmenge": null,
   "allzeithoch": 285.6,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "doge",
   "art": "krypto",
   "name": "Dogecoin",
   "kuerzel": "DOGE",
   "kurs": 0.073305,
   "marktkapitalisierung": 11410957437,
   "umlaufmenge": 155682446384,
   "hoechstmenge": null,
   "allzeithoch": 0.601466,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "ada",
   "art": "krypto",
   "name": "Cardano",
   "kuerzel": "ADA",
   "kurs": 0.174695,
   "marktkapitalisierung": 6551112223,
   "umlaufmenge": 37498597081,
   "hoechstmenge": 45000000000,
   "allzeithoch": 2.61,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "link",
   "art": "krypto",
   "name": "Chainlink",
   "kuerzel": "LINK",
   "kurs": 9.86,
   "marktkapitalisierung": 7373134621,
   "umlaufmenge": 748099970,
   "hoechstmenge": 1000000000,
   "allzeithoch": 43.32,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "ltc",
   "art": "krypto",
   "name": "Litecoin",
   "kuerzel": "LTC",
   "kurs": 42.22,
   "marktkapitalisierung": 3274421176,
   "umlaufmenge": 77545367,
   "hoechstmenge": 84000000,
   "allzeithoch": 337.56,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "avax",
   "art": "krypto",
   "name": "Avalanche",
   "kuerzel": "AVAX",
   "kurs": 6.28,
   "marktkapitalisierung": 2711697592,
   "umlaufmenge": 431771961,
   "hoechstmenge": 720000000,
   "allzeithoch": 128.43,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "dot",
   "art": "krypto",
   "name": "Polkadot",
   "kuerzel": "DOT",
   "kurs": 0.731423,
   "marktkapitalisierung": 1243737358,
   "umlaufmenge": 1700150638,
   "hoechstmenge": 2100000000,
   "allzeithoch": 47.6,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "bnb",
   "art": "krypto",
   "name": "BNB",
   "kuerzel": "BNB",
   "kurs": 597.2,
   "marktkapitalisierung": 79527152925,
   "umlaufmenge": 133162586,
   "hoechstmenge": 200000000,
   "allzeithoch": 1182.86,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "trx",
   "art": "krypto",
   "name": "Tron",
   "kuerzel": "TRX",
   "kurs": 0.293319,
   "marktkapitalisierung": 27841266022,
   "umlaufmenge": 94923701758,
   "hoechstmenge": null,
   "allzeithoch": 0.410308,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "ton",
   "art": "krypto",
   "name": "Toncoin",
   "kuerzel": "TON",
   "kurs": 1.18,
   "marktkapitalisierung": 3258542275,
   "umlaufmenge": 2766369829,
   "hoechstmenge": null,
   "allzeithoch": 7.7,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "aave",
   "art": "krypto",
   "name": "Aave",
   "kuerzel": "AAVE",
   "kurs": 105.63,
   "marktkapitalisierung": 1629413194,
   "umlaufmenge": 15425051,
   "hoechstmenge": 16000000,
   "allzeithoch": 541.28,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "xlm",
   "art": "krypto",
   "name": "Stellar",
   "kuerzel": "XLM",
   "kurs": 0.15384,
   "marktkapitalisierung": 5332491117,
   "umlaufmenge": 34663871478,
   "hoechstmenge": null,
   "allzeithoch": 0.729104,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "bch",
   "art": "krypto",
   "name": "Bitcoin Cash",
   "kuerzel": "BCH",
   "kurs": 213.03,
   "marktkapitalisierung": 4278167539,
   "umlaufmenge": 20081494,
   "hoechstmenge": 21000000,
   "allzeithoch": 3187.12,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "xmr",
   "art": "krypto",
   "name": "Monero",
   "kuerzel": "XMR",
   "kurs": 404.35,
   "marktkapitalisierung": 7602750196,
   "umlaufmenge": 18797296,
   "hoechstmenge": null,
   "allzeithoch": 685.48,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "uni",
   "art": "krypto",
   "name": "Uniswap",
   "kuerzel": "UNI",
   "kurs": 3.81,
   "marktkapitalisierung": 2371652498,
   "umlaufmenge": 623212424,
   "hoechstmenge": 1000000000,
   "allzeithoch": 37.37,
   "sektor": "Krypto",
   "land": null
  }
 ]
};
