/* Erzeugt von pflege/baue-werte.js - NICHT von Hand aendern. */
/* Stand 2026-08-17. Zum Aktualisieren die Zahlen im Pflegeskript ersetzen. */
const WERTE = {
 "stand": "2026-08-17",
 "eurUsd": 1.1567,
 "hinweis": "Startkurse und Kennzahlen sind echte Marktdaten vom angegebenen Stand. Der Kursverlauf im Spiel ist simuliert und hat keinen Bezug zur Wirklichkeit.",
 "quellen": [
  "stockanalysis.com (Kurse, KGV, Dividendenrendite, ETF-Kennzahlen)",
  "CoinGecko (Kryptokurse)",
  "frankfurter.dev / EZB (Wechselkurse)"
 ],
 "werte": [
  {
   "id": "sap",
   "art": "aktie",
   "name": "SAP",
   "kuerzel": "SAP",
   "kurs": 180.14,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 26.98,
   "gewinnJeAktie": 6.6768,
   "dividende": 2.5039,
   "divRendite": 1.39,
   "sektor": "Technologie",
   "land": "Deutschland"
  },
  {
   "id": "sie",
   "art": "aktie",
   "name": "Siemens",
   "kuerzel": "SIE",
   "kurs": 284,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 28.39,
   "gewinnJeAktie": 10.0035,
   "dividende": 5.3392,
   "divRendite": 1.88,
   "sektor": "Industrie",
   "land": "Deutschland"
  },
  {
   "id": "alv",
   "art": "aktie",
   "name": "Allianz",
   "kuerzel": "ALV",
   "kurs": 442.7,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 14.52,
   "gewinnJeAktie": 30.489,
   "dividende": 17.0882,
   "divRendite": 3.86,
   "sektor": "Versicherung",
   "land": "Deutschland"
  },
  {
   "id": "rhm",
   "art": "aktie",
   "name": "Rheinmetall",
   "kuerzel": "RHM",
   "kurs": 1202,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 46.06,
   "gewinnJeAktie": 26.0964,
   "dividende": 11.5392,
   "divRendite": 0.96,
   "sektor": "Ruestung",
   "land": "Deutschland"
  },
  {
   "id": "mbg",
   "art": "aktie",
   "name": "Mercedes-Benz Group",
   "kuerzel": "MBG",
   "kurs": 46.025,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 8.72,
   "gewinnJeAktie": 5.2781,
   "dividende": 3.4979,
   "divRendite": 7.6,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "bmw",
   "art": "aktie",
   "name": "BMW",
   "kuerzel": "BMW",
   "kurs": 59.4,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 5.64,
   "gewinnJeAktie": 10.5319,
   "dividende": 4.4015,
   "divRendite": 7.41,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "vow3",
   "art": "aktie",
   "name": "Volkswagen Vorzuege",
   "kuerzel": "VOW3",
   "kurs": 73.72,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 7.05,
   "gewinnJeAktie": 10.4567,
   "dividende": 5.2636,
   "divRendite": 7.14,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "dbk",
   "art": "aktie",
   "name": "Deutsche Bank",
   "kuerzel": "DBK",
   "kurs": 33.385,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 10.78,
   "gewinnJeAktie": 3.0969,
   "dividende": 1.0016,
   "divRendite": 3,
   "sektor": "Banken",
   "land": "Deutschland"
  },
  {
   "id": "cbk",
   "art": "aktie",
   "name": "Commerzbank",
   "kuerzel": "CBK",
   "kurs": 39.74,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 15.26,
   "gewinnJeAktie": 2.6042,
   "dividende": 1.1008,
   "divRendite": 2.77,
   "sektor": "Banken",
   "land": "Deutschland"
  },
  {
   "id": "ads",
   "art": "aktie",
   "name": "adidas",
   "kuerzel": "ADS",
   "kurs": 157.55,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 20.24,
   "gewinnJeAktie": 7.7841,
   "dividende": 2.8044,
   "divRendite": 1.78,
   "sektor": "Konsum",
   "land": "Deutschland"
  },
  {
   "id": "zal",
   "art": "aktie",
   "name": "Zalando",
   "kuerzel": "ZAL",
   "kurs": 23.6,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 64,
   "gewinnJeAktie": 0.36875,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Handel",
   "land": "Deutschland"
  },
  {
   "id": "ifx",
   "art": "aktie",
   "name": "Infineon",
   "kuerzel": "IFX",
   "kurs": 61.73,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 67.07,
   "gewinnJeAktie": 0.920382,
   "dividende": 0.351861,
   "divRendite": 0.57,
   "sektor": "Halbleiter",
   "land": "Deutschland"
  },
  {
   "id": "bas",
   "art": "aktie",
   "name": "BASF",
   "kuerzel": "BAS",
   "kurs": 51.15,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 21.62,
   "gewinnJeAktie": 2.3659,
   "dividende": 2.2506,
   "divRendite": 4.4,
   "sektor": "Chemie",
   "land": "Deutschland"
  },
  {
   "id": "bayn",
   "art": "aktie",
   "name": "Bayer",
   "kuerzel": "BAYN",
   "kurs": 47.79,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0.109917,
   "divRendite": 0.23,
   "sektor": "Pharma",
   "land": "Deutschland"
  },
  {
   "id": "mrk1",
   "art": "aktie",
   "name": "Merck",
   "kuerzel": "MRK1",
   "kurs": 136.3,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 25.01,
   "gewinnJeAktie": 5.4498,
   "dividende": 2.1944,
   "divRendite": 1.61,
   "sektor": "Pharma",
   "land": "Deutschland"
  },
  {
   "id": "dte",
   "art": "aktie",
   "name": "Deutsche Telekom",
   "kuerzel": "DTE",
   "kurs": 28.67,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 16.05,
   "gewinnJeAktie": 1.7863,
   "dividende": 1.0006,
   "divRendite": 3.49,
   "sektor": "Telekom",
   "land": "Deutschland"
  },
  {
   "id": "dhl",
   "art": "aktie",
   "name": "DHL Group",
   "kuerzel": "DHL",
   "kurs": 55.26,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 16.83,
   "gewinnJeAktie": 3.2834,
   "dividende": 1.9009,
   "divRendite": 3.44,
   "sektor": "Logistik",
   "land": "Deutschland"
  },
  {
   "id": "eoan",
   "art": "aktie",
   "name": "E.ON",
   "kuerzel": "EOAN",
   "kurs": 17.45,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 13.52,
   "gewinnJeAktie": 1.2907,
   "dividende": 0.570615,
   "divRendite": 3.27,
   "sektor": "Versorger",
   "land": "Deutschland"
  },
  {
   "id": "rwe",
   "art": "aktie",
   "name": "RWE",
   "kuerzel": "RWE",
   "kurs": 58.9,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 13.04,
   "gewinnJeAktie": 4.5169,
   "dividende": 1.2016,
   "divRendite": 2.04,
   "sektor": "Versorger",
   "land": "Deutschland"
  },
  {
   "id": "enr",
   "art": "aktie",
   "name": "Siemens Energy",
   "kuerzel": "ENR",
   "kurs": 160.72,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 52.28,
   "gewinnJeAktie": 3.0742,
   "dividende": 0.707168,
   "divRendite": 0.44,
   "sektor": "Versorger",
   "land": "Deutschland"
  },
  {
   "id": "muv2",
   "art": "aktie",
   "name": "Muenchener Rueck",
   "kuerzel": "MUV2",
   "kurs": 517.8,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 9.64,
   "gewinnJeAktie": 53.7137,
   "dividende": 23.9741,
   "divRendite": 4.63,
   "sektor": "Versicherung",
   "land": "Deutschland"
  },
  {
   "id": "hnr1",
   "art": "aktie",
   "name": "Hannover Rueck",
   "kuerzel": "HNR1",
   "kurs": 253.4,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 11.18,
   "gewinnJeAktie": 22.6655,
   "dividende": 12.4926,
   "divRendite": 4.93,
   "sektor": "Versicherung",
   "land": "Deutschland"
  },
  {
   "id": "db1",
   "art": "aktie",
   "name": "Deutsche Boerse",
   "kuerzel": "DB1",
   "kurs": 272.9,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 23.54,
   "gewinnJeAktie": 11.593,
   "dividende": 4.2027,
   "divRendite": 1.54,
   "sektor": "Finanzen",
   "land": "Deutschland"
  },
  {
   "id": "bei",
   "art": "aktie",
   "name": "Beiersdorf",
   "kuerzel": "BEI",
   "kurs": 78.1,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 18.26,
   "gewinnJeAktie": 4.2771,
   "dividende": 0.99968,
   "divRendite": 1.28,
   "sektor": "Konsum",
   "land": "Deutschland"
  },
  {
   "id": "hen3",
   "art": "aktie",
   "name": "Henkel Vorzuege",
   "kuerzel": "HEN3",
   "kurs": 76.32,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 16.27,
   "gewinnJeAktie": 4.6908,
   "dividende": 2.0683,
   "divRendite": 2.71,
   "sektor": "Konsum",
   "land": "Deutschland"
  },
  {
   "id": "con",
   "art": "aktie",
   "name": "Continental",
   "kuerzel": "CON",
   "kurs": 69.38,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 2.6989,
   "divRendite": 3.89,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "dtg",
   "art": "aktie",
   "name": "Daimler Truck",
   "kuerzel": "DTG",
   "kurs": 45.1,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 31.98,
   "gewinnJeAktie": 1.4103,
   "dividende": 1.8987,
   "divRendite": 4.21,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "mtx",
   "art": "aktie",
   "name": "MTU Aero Engines",
   "kuerzel": "MTX",
   "kurs": 382.7,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 22.17,
   "gewinnJeAktie": 17.2621,
   "dividende": 3.5974,
   "divRendite": 0.94,
   "sektor": "Luftfahrt",
   "land": "Deutschland"
  },
  {
   "id": "hei",
   "art": "aktie",
   "name": "Heidelberg Materials",
   "kuerzel": "HEI",
   "kurs": 161.75,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 14.05,
   "gewinnJeAktie": 11.5125,
   "dividende": 3.607,
   "divRendite": 2.23,
   "sektor": "Bau",
   "land": "Deutschland"
  },
  {
   "id": "vna",
   "art": "aktie",
   "name": "Vonovia",
   "kuerzel": "VNA",
   "kurs": 20.58,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 4.82,
   "gewinnJeAktie": 4.2697,
   "dividende": 1.2492,
   "divRendite": 6.07,
   "sektor": "Immobilien",
   "land": "Deutschland"
  },
  {
   "id": "asml",
   "art": "aktie",
   "name": "ASML",
   "kuerzel": "ASML",
   "kurs": 1579.6,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 57.36,
   "gewinnJeAktie": 27.5384,
   "dividende": 7.4241,
   "divRendite": 0.47,
   "sektor": "Halbleiter",
   "land": "Niederlande"
  },
  {
   "id": "mc",
   "art": "aktie",
   "name": "LVMH",
   "kuerzel": "MC",
   "kurs": 458.4,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 20.9,
   "gewinnJeAktie": 21.933,
   "dividende": 13.0186,
   "divRendite": 2.84,
   "sektor": "Luxus",
   "land": "Frankreich"
  },
  {
   "id": "rms",
   "art": "aktie",
   "name": "Hermes",
   "kuerzel": "RMS",
   "kurs": 1576,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 36.65,
   "gewinnJeAktie": 43.0014,
   "dividende": 17.9664,
   "divRendite": 1.14,
   "sektor": "Luxus",
   "land": "Frankreich"
  },
  {
   "id": "or",
   "art": "aktie",
   "name": "LOreal",
   "kuerzel": "OR",
   "kurs": 379.5,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 32.22,
   "gewinnJeAktie": 11.7784,
   "dividende": 7.2105,
   "divRendite": 1.9,
   "sektor": "Konsum",
   "land": "Frankreich"
  },
  {
   "id": "tte",
   "art": "aktie",
   "name": "TotalEnergies",
   "kuerzel": "TTE",
   "kurs": 75.78,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 10.79,
   "gewinnJeAktie": 7.0232,
   "dividende": 3.4025,
   "divRendite": 4.49,
   "sektor": "Energie",
   "land": "Frankreich"
  },
  {
   "id": "san",
   "art": "aktie",
   "name": "Sanofi",
   "kuerzel": "SAN",
   "kurs": 75.52,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 23.25,
   "gewinnJeAktie": 3.2482,
   "dividende": 4.1234,
   "divRendite": 5.46,
   "sektor": "Pharma",
   "land": "Frankreich"
  },
  {
   "id": "ai",
   "art": "aktie",
   "name": "Air Liquide",
   "kuerzel": "AI",
   "kurs": 168.26,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 30.28,
   "gewinnJeAktie": 5.5568,
   "dividende": 3.3652,
   "divRendite": 2,
   "sektor": "Chemie",
   "land": "Frankreich"
  },
  {
   "id": "su",
   "art": "aktie",
   "name": "Schneider Electric",
   "kuerzel": "SU",
   "kurs": 306.4,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 36.86,
   "gewinnJeAktie": 8.3125,
   "dividende": 4.1977,
   "divRendite": 1.37,
   "sektor": "Industrie",
   "land": "Frankreich"
  },
  {
   "id": "saf",
   "art": "aktie",
   "name": "SAFRAN",
   "kuerzel": "SAF",
   "kurs": 360.5,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 38.72,
   "gewinnJeAktie": 9.3104,
   "dividende": 3.3527,
   "divRendite": 0.93,
   "sektor": "Luftfahrt",
   "land": "Frankreich"
  },
  {
   "id": "cs",
   "art": "aktie",
   "name": "AXA",
   "kuerzel": "CS",
   "kurs": 45.05,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 12.16,
   "gewinnJeAktie": 3.7048,
   "dividende": 2.3201,
   "divRendite": 5.15,
   "sektor": "Versicherung",
   "land": "Frankreich"
  },
  {
   "id": "bnp",
   "art": "aktie",
   "name": "BNP Paribas",
   "kuerzel": "BNP",
   "kurs": 112.1,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 9.71,
   "gewinnJeAktie": 11.5448,
   "dividende": 5.1454,
   "divRendite": 4.59,
   "sektor": "Banken",
   "land": "Frankreich"
  },
  {
   "id": "dg",
   "art": "aktie",
   "name": "VINCI",
   "kuerzel": "DG",
   "kurs": 120.85,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 13.4,
   "gewinnJeAktie": 9.0187,
   "dividende": 5.0032,
   "divRendite": 4.14,
   "sektor": "Bau",
   "land": "Frankreich"
  },
  {
   "id": "bn",
   "art": "aktie",
   "name": "Danone",
   "kuerzel": "BN",
   "kurs": 67.24,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 22.27,
   "gewinnJeAktie": 3.0193,
   "dividende": 2.2525,
   "divRendite": 3.35,
   "sektor": "Nahrung",
   "land": "Frankreich"
  },
  {
   "id": "el",
   "art": "aktie",
   "name": "EssilorLuxottica",
   "kuerzel": "EL",
   "kurs": 162.55,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 30.37,
   "gewinnJeAktie": 5.3523,
   "dividende": 3.9987,
   "divRendite": 2.46,
   "sektor": "Konsum",
   "land": "Frankreich"
  },
  {
   "id": "air",
   "art": "aktie",
   "name": "Airbus",
   "kuerzel": "AIR",
   "kurs": 215.4,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 28.68,
   "gewinnJeAktie": 7.5105,
   "dividende": 3.2095,
   "divRendite": 1.49,
   "sektor": "Luftfahrt",
   "land": "Niederlande"
  },
  {
   "id": "race",
   "art": "aktie",
   "name": "Ferrari",
   "kuerzel": "RACE",
   "kurs": 356.8,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 38.67,
   "gewinnJeAktie": 9.2268,
   "dividende": 3.6037,
   "divRendite": 1.01,
   "sektor": "Automobil",
   "land": "Italien"
  },
  {
   "id": "adyen",
   "art": "aktie",
   "name": "Adyen",
   "kuerzel": "ADYEN",
   "kurs": 1061.6,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 29.77,
   "gewinnJeAktie": 35.6601,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Finanzen",
   "land": "Niederlande"
  },
  {
   "id": "inga",
   "art": "aktie",
   "name": "ING Group",
   "kuerzel": "INGA",
   "kurs": 30.885,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 10.34,
   "gewinnJeAktie": 2.9869,
   "dividende": 1.3095,
   "divRendite": 4.24,
   "sektor": "Banken",
   "land": "Niederlande"
  },
  {
   "id": "abi",
   "art": "aktie",
   "name": "AB InBev",
   "kuerzel": "ABI",
   "kurs": 68.62,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 16.9,
   "gewinnJeAktie": 4.0604,
   "dividende": 1.1528,
   "divRendite": 1.68,
   "sektor": "Nahrung",
   "land": "Belgien"
  },
  {
   "id": "itx",
   "art": "aktie",
   "name": "Inditex",
   "kuerzel": "ITX",
   "kurs": 57.6,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 28.55,
   "gewinnJeAktie": 2.0175,
   "dividende": 1.751,
   "divRendite": 3.04,
   "sektor": "Handel",
   "land": "Spanien"
  },
  {
   "id": "san2",
   "art": "aktie",
   "name": "Banco Santander",
   "kuerzel": "SAN2",
   "kurs": 12.898,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 14.62,
   "gewinnJeAktie": 0.882216,
   "dividende": 0.250221,
   "divRendite": 1.94,
   "sektor": "Banken",
   "land": "Spanien"
  },
  {
   "id": "ibe",
   "art": "aktie",
   "name": "Iberdrola",
   "kuerzel": "IBE",
   "kurs": 20.2,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 24.75,
   "gewinnJeAktie": 0.816162,
   "dividende": 0.68074,
   "divRendite": 3.37,
   "sektor": "Versorger",
   "land": "Spanien"
  },
  {
   "id": "enel",
   "art": "aktie",
   "name": "Enel",
   "kuerzel": "ENEL",
   "kurs": 9.495,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 22.76,
   "gewinnJeAktie": 0.417179,
   "dividende": 0.489942,
   "divRendite": 5.16,
   "sektor": "Versorger",
   "land": "Italien"
  },
  {
   "id": "eni",
   "art": "aktie",
   "name": "Eni",
   "kuerzel": "ENI",
   "kurs": 23.695,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 12.43,
   "gewinnJeAktie": 1.9063,
   "dividende": 1.0805,
   "divRendite": 4.56,
   "sektor": "Energie",
   "land": "Italien"
  },
  {
   "id": "ucg",
   "art": "aktie",
   "name": "UniCredit",
   "kuerzel": "UCG",
   "kurs": 85.23,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 12.11,
   "gewinnJeAktie": 7.038,
   "dividende": 3.145,
   "divRendite": 3.69,
   "sektor": "Banken",
   "land": "Italien"
  },
  {
   "id": "isp",
   "art": "aktie",
   "name": "Intesa Sanpaolo",
   "kuerzel": "ISP",
   "kurs": 6.917,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 12.46,
   "gewinnJeAktie": 0.555136,
   "dividende": 0.379743,
   "divRendite": 5.49,
   "sektor": "Banken",
   "land": "Italien"
  },
  {
   "id": "nvda",
   "art": "aktie",
   "name": "NVIDIA",
   "kuerzel": "NVDA",
   "kurs": 194.66,
   "kursOriginal": 225.16,
   "waehrungOriginal": "USD",
   "kgv": 34.48,
   "gewinnJeAktie": 5.6456,
   "dividende": 0.856504,
   "divRendite": 0.44,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "aapl",
   "art": "aktie",
   "name": "Apple",
   "kuerzel": "AAPL",
   "kurs": 264.49,
   "kursOriginal": 305.93,
   "waehrungOriginal": "USD",
   "kgv": 35.1,
   "gewinnJeAktie": 7.5353,
   "dividende": 0.925715,
   "divRendite": 0.35,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "googl",
   "art": "aktie",
   "name": "Alphabet",
   "kuerzel": "GOOGL",
   "kurs": 299.04,
   "kursOriginal": 345.9,
   "waehrungOriginal": "USD",
   "kgv": 17.36,
   "gewinnJeAktie": 17.2258,
   "dividende": 0.7476,
   "divRendite": 0.25,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "msft",
   "art": "aktie",
   "name": "Microsoft",
   "kuerzel": "MSFT",
   "kurs": 428.29,
   "kursOriginal": 495.4,
   "waehrungOriginal": "USD",
   "kgv": 27.6,
   "gewinnJeAktie": 15.5178,
   "dividende": 3.1265,
   "divRendite": 0.73,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "amzn",
   "art": "aktie",
   "name": "Amazon",
   "kuerzel": "AMZN",
   "kurs": 227.07,
   "kursOriginal": 262.65,
   "waehrungOriginal": "USD",
   "kgv": 21.12,
   "gewinnJeAktie": 10.7514,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Handel",
   "land": "USA"
  },
  {
   "id": "avgo",
   "art": "aktie",
   "name": "Broadcom",
   "kuerzel": "AVGO",
   "kurs": 339.75,
   "kursOriginal": 392.99,
   "waehrungOriginal": "USD",
   "kgv": 65.4,
   "gewinnJeAktie": 5.195,
   "dividende": 2.2424,
   "divRendite": 0.66,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "meta",
   "art": "aktie",
   "name": "Meta Platforms",
   "kuerzel": "META",
   "kurs": 509.94,
   "kursOriginal": 589.85,
   "waehrungOriginal": "USD",
   "kgv": 22.23,
   "gewinnJeAktie": 22.9393,
   "dividende": 1.8358,
   "divRendite": 0.36,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "tsla",
   "art": "aktie",
   "name": "Tesla",
   "kuerzel": "TSLA",
   "kurs": 295.9,
   "kursOriginal": 342.27,
   "waehrungOriginal": "USD",
   "kgv": 355.18,
   "gewinnJeAktie": 0.833099,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Automobil",
   "land": "USA"
  },
  {
   "id": "brkb",
   "art": "aktie",
   "name": "Berkshire Hathaway",
   "kuerzel": "BRK.B",
   "kurs": 435.75,
   "kursOriginal": 504.03,
   "waehrungOriginal": "USD",
   "kgv": 12.58,
   "gewinnJeAktie": 34.6383,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Finanzen",
   "land": "USA"
  },
  {
   "id": "mu",
   "art": "aktie",
   "name": "Micron Technology",
   "kuerzel": "MU",
   "kurs": 840.03,
   "kursOriginal": 971.66,
   "waehrungOriginal": "USD",
   "kgv": 21.93,
   "gewinnJeAktie": 38.3051,
   "dividende": 0.504018,
   "divRendite": 0.06,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "jpm",
   "art": "aktie",
   "name": "JPMorgan Chase",
   "kuerzel": "JPM",
   "kurs": 313.69,
   "kursOriginal": 362.84,
   "waehrungOriginal": "USD",
   "kgv": 15.57,
   "gewinnJeAktie": 20.1471,
   "dividende": 5.1759,
   "divRendite": 1.65,
   "sektor": "Banken",
   "land": "USA"
  },
  {
   "id": "wmt",
   "art": "aktie",
   "name": "Walmart",
   "kuerzel": "WMT",
   "kurs": 99.6542,
   "kursOriginal": 115.27,
   "waehrungOriginal": "USD",
   "kgv": 40.58,
   "gewinnJeAktie": 2.4557,
   "dividende": 0.857026,
   "divRendite": 0.86,
   "sektor": "Handel",
   "land": "USA"
  },
  {
   "id": "amd",
   "art": "aktie",
   "name": "AMD",
   "kuerzel": "AMD",
   "kurs": 444.7,
   "kursOriginal": 514.39,
   "waehrungOriginal": "USD",
   "kgv": 131.29,
   "gewinnJeAktie": 3.3872,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "v",
   "art": "aktie",
   "name": "Visa",
   "kuerzel": "V",
   "kurs": 314.82,
   "kursOriginal": 364.15,
   "waehrungOriginal": "USD",
   "kgv": 31,
   "gewinnJeAktie": 10.1555,
   "dividende": 2.3297,
   "divRendite": 0.74,
   "sektor": "Finanzen",
   "land": "USA"
  },
  {
   "id": "jnj",
   "art": "aktie",
   "name": "Johnson & Johnson",
   "kuerzel": "JNJ",
   "kurs": 225.08,
   "kursOriginal": 260.35,
   "waehrungOriginal": "USD",
   "kgv": 30.18,
   "gewinnJeAktie": 7.4579,
   "dividende": 4.6366,
   "divRendite": 2.06,
   "sektor": "Pharma",
   "land": "USA"
  },
  {
   "id": "csco",
   "art": "aktie",
   "name": "Cisco",
   "kuerzel": "CSCO",
   "kurs": 96.5505,
   "kursOriginal": 111.68,
   "waehrungOriginal": "USD",
   "kgv": 33.54,
   "gewinnJeAktie": 2.8787,
   "dividende": 1.4483,
   "divRendite": 1.5,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "cost",
   "art": "aktie",
   "name": "Costco",
   "kuerzel": "COST",
   "kurs": 830.9,
   "kursOriginal": 961.1,
   "waehrungOriginal": "USD",
   "kgv": 48.34,
   "gewinnJeAktie": 17.1887,
   "dividende": 5.0685,
   "divRendite": 0.61,
   "sektor": "Handel",
   "land": "USA"
  },
  {
   "id": "amat",
   "art": "aktie",
   "name": "Applied Materials",
   "kuerzel": "AMAT",
   "kurs": 438.47,
   "kursOriginal": 507.18,
   "waehrungOriginal": "USD",
   "kgv": 43.75,
   "gewinnJeAktie": 10.0222,
   "dividende": 1.8416,
   "divRendite": 0.42,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "cat",
   "art": "aktie",
   "name": "Caterpillar",
   "kuerzel": "CAT",
   "kurs": 740.53,
   "kursOriginal": 856.57,
   "waehrungOriginal": "USD",
   "kgv": 36.91,
   "gewinnJeAktie": 20.0631,
   "dividende": 5.628,
   "divRendite": 0.76,
   "sektor": "Industrie",
   "land": "USA"
  },
  {
   "id": "lrcx",
   "art": "aktie",
   "name": "Lam Research",
   "kuerzel": "LRCX",
   "kurs": 287.33,
   "kursOriginal": 332.36,
   "waehrungOriginal": "USD",
   "kgv": 57.7,
   "gewinnJeAktie": 4.9797,
   "dividende": 0.890723,
   "divRendite": 0.31,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "pltr",
   "art": "aktie",
   "name": "Palantir",
   "kuerzel": "PLTR",
   "kurs": 150.46,
   "kursOriginal": 174.04,
   "waehrungOriginal": "USD",
   "kgv": 148.85,
   "gewinnJeAktie": 1.0108,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "ko",
   "art": "aktie",
   "name": "Coca-Cola",
   "kuerzel": "KO",
   "kurs": 75.8278,
   "kursOriginal": 87.71,
   "waehrungOriginal": "USD",
   "kgv": 26.36,
   "gewinnJeAktie": 2.8766,
   "dividende": 1.835,
   "divRendite": 2.42,
   "sektor": "Nahrung",
   "land": "USA"
  },
  {
   "id": "cvx",
   "art": "aktie",
   "name": "Chevron",
   "kuerzel": "CVX",
   "kurs": 172.91,
   "kursOriginal": 200,
   "waehrungOriginal": "USD",
   "kgv": 19.21,
   "gewinnJeAktie": 9.001,
   "dividende": 6.1556,
   "divRendite": 3.56,
   "sektor": "Energie",
   "land": "USA"
  },
  {
   "id": "unh",
   "art": "aktie",
   "name": "UnitedHealth",
   "kuerzel": "UNH",
   "kurs": 347.31,
   "kursOriginal": 401.73,
   "waehrungOriginal": "USD",
   "kgv": 25.86,
   "gewinnJeAktie": 13.4304,
   "dividende": 8.0229,
   "divRendite": 2.31,
   "sektor": "Gesundheit",
   "land": "USA"
  },
  {
   "id": "hd",
   "art": "aktie",
   "name": "Home Depot",
   "kuerzel": "HD",
   "kurs": 292.95,
   "kursOriginal": 338.86,
   "waehrungOriginal": "USD",
   "kgv": 24.07,
   "gewinnJeAktie": 12.1708,
   "dividende": 8.0561,
   "divRendite": 2.75,
   "sektor": "Handel",
   "land": "USA"
  },
  {
   "id": "pg",
   "art": "aktie",
   "name": "Procter & Gamble",
   "kuerzel": "PG",
   "kurs": 124.97,
   "kursOriginal": 144.55,
   "waehrungOriginal": "USD",
   "kgv": 21.82,
   "gewinnJeAktie": 5.7273,
   "dividende": 3.7616,
   "divRendite": 3.01,
   "sektor": "Konsum",
   "land": "USA"
  },
  {
   "id": "mrk",
   "art": "aktie",
   "name": "Merck & Co",
   "kuerzel": "MRK",
   "kurs": 117.44,
   "kursOriginal": 135.84,
   "waehrungOriginal": "USD",
   "kgv": 106.72,
   "gewinnJeAktie": 1.1004,
   "dividende": 2.936,
   "divRendite": 2.5,
   "sektor": "Pharma",
   "land": "USA"
  },
  {
   "id": "gs",
   "art": "aktie",
   "name": "Goldman Sachs",
   "kuerzel": "GS",
   "kurs": 898.61,
   "kursOriginal": 1039.42,
   "waehrungOriginal": "USD",
   "kgv": 16.08,
   "gewinnJeAktie": 55.8837,
   "dividende": 17.2533,
   "divRendite": 1.92,
   "sektor": "Banken",
   "land": "USA"
  },
  {
   "id": "nflx",
   "art": "aktie",
   "name": "Netflix",
   "kuerzel": "NFLX",
   "kurs": 67.5715,
   "kursOriginal": 78.16,
   "waehrungOriginal": "USD",
   "kgv": 24.62,
   "gewinnJeAktie": 2.7446,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Medien",
   "land": "USA"
  },
  {
   "id": "txn",
   "art": "aktie",
   "name": "Texas Instruments",
   "kuerzel": "TXN",
   "kurs": 241.7,
   "kursOriginal": 279.58,
   "waehrungOriginal": "USD",
   "kgv": 42.47,
   "gewinnJeAktie": 5.6911,
   "dividende": 4.9065,
   "divRendite": 2.03,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "klac",
   "art": "aktie",
   "name": "KLA",
   "kuerzel": "KLAC",
   "kurs": 176.12,
   "kursOriginal": 203.72,
   "waehrungOriginal": "USD",
   "kgv": 55.66,
   "gewinnJeAktie": 3.1642,
   "dividende": 0.79254,
   "divRendite": 0.45,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "axp",
   "art": "aktie",
   "name": "American Express",
   "kuerzel": "AXP",
   "kurs": 296.08,
   "kursOriginal": 342.48,
   "waehrungOriginal": "USD",
   "kgv": 20.79,
   "gewinnJeAktie": 14.2415,
   "dividende": 3.2865,
   "divRendite": 1.11,
   "sektor": "Finanzen",
   "land": "USA"
  },
  {
   "id": "panw",
   "art": "aktie",
   "name": "Palo Alto Networks",
   "kuerzel": "PANW",
   "kurs": 332.21,
   "kursOriginal": 384.27,
   "waehrungOriginal": "USD",
   "kgv": 371.55,
   "gewinnJeAktie": 0.894119,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "intc",
   "art": "aktie",
   "name": "Intel",
   "kuerzel": "INTC",
   "kurs": 88.6142,
   "kursOriginal": 102.5,
   "waehrungOriginal": "USD",
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "ma",
   "art": "aktie",
   "name": "Mastercard",
   "kuerzel": "MA",
   "kurs": 492.17,
   "kursOriginal": 569.29,
   "waehrungOriginal": "USD",
   "kgv": 31.31,
   "gewinnJeAktie": 15.7193,
   "dividende": 3.0022,
   "divRendite": 0.61,
   "sektor": "Finanzen",
   "land": "USA"
  },
  {
   "id": "lly",
   "art": "aktie",
   "name": "Eli Lilly",
   "kuerzel": "LLY",
   "kurs": 1020.28,
   "kursOriginal": 1180.16,
   "waehrungOriginal": "USD",
   "kgv": 39.62,
   "gewinnJeAktie": 25.7516,
   "dividende": 6.0197,
   "divRendite": 0.59,
   "sektor": "Pharma",
   "land": "USA"
  },
  {
   "id": "xom",
   "art": "aktie",
   "name": "ExxonMobil",
   "kuerzel": "XOM",
   "kurs": 138.41,
   "kursOriginal": 160.1,
   "waehrungOriginal": "USD",
   "kgv": 20.64,
   "gewinnJeAktie": 6.7059,
   "dividende": 3.5571,
   "divRendite": 2.57,
   "sektor": "Energie",
   "land": "USA"
  },
  {
   "id": "orcl",
   "art": "aktie",
   "name": "Oracle",
   "kuerzel": "ORCL",
   "kurs": 130.13,
   "kursOriginal": 150.52,
   "waehrungOriginal": "USD",
   "kgv": 25.82,
   "gewinnJeAktie": 5.0399,
   "dividende": 1.7307,
   "divRendite": 1.33,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "ge",
   "art": "aktie",
   "name": "GE Aerospace",
   "kuerzel": "GE",
   "kurs": 318.47,
   "kursOriginal": 368.38,
   "waehrungOriginal": "USD",
   "kgv": 43.42,
   "gewinnJeAktie": 7.3346,
   "dividende": 1.6242,
   "divRendite": 0.51,
   "sektor": "Luftfahrt",
   "land": "USA"
  },
  {
   "id": "bac",
   "art": "aktie",
   "name": "Bank of America",
   "kuerzel": "BAC",
   "kurs": 55.7534,
   "kursOriginal": 64.49,
   "waehrungOriginal": "USD",
   "kgv": 14.9,
   "gewinnJeAktie": 3.7418,
   "dividende": 0.970109,
   "divRendite": 1.74,
   "sektor": "Banken",
   "land": "USA"
  },
  {
   "id": "tsm",
   "art": "aktie",
   "name": "TSMC",
   "kuerzel": "TSM",
   "kurs": 368.59,
   "kursOriginal": 426.35,
   "waehrungOriginal": "USD",
   "kgv": 27.86,
   "gewinnJeAktie": 13.2301,
   "dividende": 2.3958,
   "divRendite": 0.65,
   "sektor": "Halbleiter",
   "land": "Taiwan"
  },
  {
   "id": "skhy",
   "art": "aktie",
   "name": "SK hynix",
   "kuerzel": "SKHY",
   "kurs": 1007.71,
   "kursOriginal": 1645000,
   "waehrungOriginal": "KRW",
   "kgv": 7.21,
   "gewinnJeAktie": 139.77,
   "dividende": 1.8139,
   "divRendite": 0.18,
   "sektor": "Halbleiter",
   "land": "Suedkorea"
  },
  {
   "id": "baba",
   "art": "aktie",
   "name": "Alibaba",
   "kuerzel": "BABA",
   "kurs": 107.04,
   "kursOriginal": 123.81,
   "waehrungOriginal": "USD",
   "kgv": 19.41,
   "gewinnJeAktie": 5.5147,
   "dividende": 0.90984,
   "divRendite": 0.85,
   "sektor": "Handel",
   "land": "China"
  },
  {
   "id": "mufg",
   "art": "aktie",
   "name": "Mitsubishi UFJ",
   "kuerzel": "MUFG",
   "kurs": 19.936,
   "kursOriginal": 23.06,
   "waehrungOriginal": "USD",
   "kgv": 21.27,
   "gewinnJeAktie": 0.937283,
   "dividende": 0.382771,
   "divRendite": 1.92,
   "sektor": "Banken",
   "land": "Japan"
  },
  {
   "id": "arm",
   "art": "aktie",
   "name": "Arm Holdings",
   "kuerzel": "ARM",
   "kurs": 241.58,
   "kursOriginal": 279.44,
   "waehrungOriginal": "USD",
   "kgv": 285.23,
   "gewinnJeAktie": 0.846966,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Halbleiter",
   "land": "Grossbritannien"
  },
  {
   "id": "shel",
   "art": "aktie",
   "name": "Shell",
   "kuerzel": "SHEL",
   "kurs": 78.2139,
   "kursOriginal": 90.47,
   "waehrungOriginal": "USD",
   "kgv": 9.62,
   "gewinnJeAktie": 8.1303,
   "dividende": 2.6123,
   "divRendite": 3.34,
   "sektor": "Energie",
   "land": "Grossbritannien"
  },
  {
   "id": "azn",
   "art": "aktie",
   "name": "AstraZeneca",
   "kuerzel": "AZN",
   "kurs": 135.26,
   "kursOriginal": 156.45,
   "waehrungOriginal": "USD",
   "kgv": 23.05,
   "gewinnJeAktie": 5.8681,
   "dividende": 2.7999,
   "divRendite": 2.07,
   "sektor": "Pharma",
   "land": "Grossbritannien"
  },
  {
   "id": "hsbc",
   "art": "aktie",
   "name": "HSBC",
   "kuerzel": "HSBC",
   "kurs": 89.7294,
   "kursOriginal": 103.79,
   "waehrungOriginal": "USD",
   "kgv": 16.83,
   "gewinnJeAktie": 5.3315,
   "dividende": 3.2213,
   "divRendite": 3.59,
   "sektor": "Banken",
   "land": "Grossbritannien"
  },
  {
   "id": "nvs",
   "art": "aktie",
   "name": "Novartis",
   "kuerzel": "NVS",
   "kurs": 130.44,
   "kursOriginal": 150.88,
   "waehrungOriginal": "USD",
   "kgv": 22.48,
   "gewinnJeAktie": 5.8025,
   "dividende": 2.661,
   "divRendite": 2.04,
   "sektor": "Pharma",
   "land": "Schweiz"
  },
  {
   "id": "ry",
   "art": "aktie",
   "name": "Royal Bank of Canada",
   "kuerzel": "RY",
   "kurs": 187.22,
   "kursOriginal": 216.56,
   "waehrungOriginal": "USD",
   "kgv": 18.98,
   "gewinnJeAktie": 9.8641,
   "dividende": 4.1001,
   "divRendite": 2.19,
   "sektor": "Banken",
   "land": "Kanada"
  },
  {
   "id": "p911",
   "art": "aktie",
   "name": "Porsche AG",
   "kuerzel": "P911",
   "kurs": 44.42,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 48,
   "gewinnJeAktie": 0.925417,
   "dividende": 1.0083,
   "divRendite": 2.27,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "fre",
   "art": "aktie",
   "name": "Fresenius",
   "kuerzel": "FRE",
   "kurs": 47.08,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 16.97,
   "gewinnJeAktie": 2.7743,
   "dividende": 1.0499,
   "divRendite": 2.23,
   "sektor": "Gesundheit",
   "land": "Deutschland"
  },
  {
   "id": "fme",
   "art": "aktie",
   "name": "Fresenius Medical Care",
   "kuerzel": "FME",
   "kurs": 41.04,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 12.27,
   "gewinnJeAktie": 3.3447,
   "dividende": 1.4898,
   "divRendite": 3.63,
   "sektor": "Gesundheit",
   "land": "Deutschland"
  },
  {
   "id": "sy1",
   "art": "aktie",
   "name": "Symrise",
   "kuerzel": "SY1",
   "kurs": 89.04,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 50.36,
   "gewinnJeAktie": 1.7681,
   "dividende": 1.2466,
   "divRendite": 1.4,
   "sektor": "Chemie",
   "land": "Deutschland"
  },
  {
   "id": "srt3",
   "art": "aktie",
   "name": "Sartorius Vorzuege",
   "kuerzel": "SRT3",
   "kurs": 237.5,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 75.32,
   "gewinnJeAktie": 3.1532,
   "dividende": 0.73625,
   "divRendite": 0.31,
   "sektor": "Gesundheit",
   "land": "Deutschland"
  },
  {
   "id": "tlx",
   "art": "aktie",
   "name": "Talanx",
   "kuerzel": "TLX",
   "kurs": 118.5,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 11.76,
   "gewinnJeAktie": 10.0765,
   "dividende": 3.6024,
   "divRendite": 3.04,
   "sektor": "Versicherung",
   "land": "Deutschland"
  },
  {
   "id": "pub",
   "art": "aktie",
   "name": "Publicis Groupe",
   "kuerzel": "PUB",
   "kurs": 101.8,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 15.86,
   "gewinnJeAktie": 6.4187,
   "dividende": 3.7462,
   "divRendite": 3.68,
   "sektor": "Medien",
   "land": "Frankreich"
  },
  {
   "id": "stla",
   "art": "aktie",
   "name": "Stellantis",
   "kuerzel": "STLA",
   "kurs": 4.61,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Automobil",
   "land": "Niederlande"
  },
  {
   "id": "prx",
   "art": "aktie",
   "name": "Prosus",
   "kuerzel": "PRX",
   "kurs": 37.395,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 8.24,
   "gewinnJeAktie": 4.5382,
   "dividende": 0.280463,
   "divRendite": 0.75,
   "sektor": "Technologie",
   "land": "Niederlande"
  },
  {
   "id": "g",
   "art": "aktie",
   "name": "Generali",
   "kuerzel": "G",
   "kurs": 44.06,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 14.95,
   "gewinnJeAktie": 2.9472,
   "dividende": 1.639,
   "divRendite": 3.72,
   "sektor": "Versicherung",
   "land": "Italien"
  },
  {
   "id": "bbva",
   "art": "aktie",
   "name": "BBVA",
   "kuerzel": "BBVA",
   "kurs": 24.95,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 13.19,
   "gewinnJeAktie": 1.8916,
   "dividende": 0.920655,
   "divRendite": 3.69,
   "sektor": "Banken",
   "land": "Spanien"
  },
  {
   "id": "tef",
   "art": "aktie",
   "name": "Telefonica",
   "kuerzel": "TEF",
   "kurs": 3.683,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0.300165,
   "divRendite": 8.15,
   "sektor": "Telekom",
   "land": "Spanien"
  },
  {
   "id": "kbc",
   "art": "aktie",
   "name": "KBC Group",
   "kuerzel": "KBC",
   "kurs": 131.7,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 14.6,
   "gewinnJeAktie": 9.0205,
   "dividende": 5.0968,
   "divRendite": 3.87,
   "sektor": "Banken",
   "land": "Belgien"
  },
  {
   "id": "ulvr",
   "art": "aktie",
   "name": "Unilever",
   "kuerzel": "ULVR",
   "kurs": 53.7098,
   "kursOriginal": 4589.5,
   "waehrungOriginal": "GBX",
   "kgv": 20.91,
   "gewinnJeAktie": 2.5686,
   "dividende": 2.0195,
   "divRendite": 3.76,
   "sektor": "Konsum",
   "land": "Grossbritannien"
  },
  {
   "id": "bp1",
   "art": "aktie",
   "name": "BP",
   "kuerzel": "BP1",
   "kurs": 6.1194,
   "kursOriginal": 522.9,
   "waehrungOriginal": "GBX",
   "kgv": 20.13,
   "gewinnJeAktie": 0.303994,
   "dividende": 0.299239,
   "divRendite": 4.89,
   "sektor": "Energie",
   "land": "Grossbritannien"
  },
  {
   "id": "gsk",
   "art": "aktie",
   "name": "GSK",
   "kuerzel": "GSK",
   "kurs": 21.2697,
   "kursOriginal": 1817.5,
   "waehrungOriginal": "GBX",
   "kgv": 15.42,
   "gewinnJeAktie": 1.3794,
   "dividende": 0.84228,
   "divRendite": 3.96,
   "sektor": "Pharma",
   "land": "Grossbritannien"
  },
  {
   "id": "dge",
   "art": "aktie",
   "name": "Diageo",
   "kuerzel": "DGE",
   "kurs": 20.6437,
   "kursOriginal": 1764,
   "waehrungOriginal": "GBX",
   "kgv": 30.04,
   "gewinnJeAktie": 0.687207,
   "dividende": 0.431453,
   "divRendite": 2.09,
   "sektor": "Nahrung",
   "land": "Grossbritannien"
  },
  {
   "id": "rio",
   "art": "aktie",
   "name": "Rio Tinto",
   "kuerzel": "RIO",
   "kurs": 82.6097,
   "kursOriginal": 7059,
   "waehrungOriginal": "GBX",
   "kgv": 12.69,
   "gewinnJeAktie": 6.5098,
   "dividende": 3.4696,
   "divRendite": 4.2,
   "sektor": "Industrie",
   "land": "Grossbritannien"
  },
  {
   "id": "barc",
   "art": "aktie",
   "name": "Barclays",
   "kuerzel": "BARC",
   "kurs": 6.0913,
   "kursOriginal": 520.5,
   "waehrungOriginal": "GBX",
   "kgv": 10.82,
   "gewinnJeAktie": 0.562967,
   "dividende": 0.100506,
   "divRendite": 1.65,
   "sektor": "Banken",
   "land": "Grossbritannien"
  },
  {
   "id": "lloy",
   "art": "aktie",
   "name": "Lloyds Banking Group",
   "kuerzel": "LLOY",
   "kurs": 1.3482,
   "kursOriginal": 115.2,
   "waehrungOriginal": "GBX",
   "kgv": 14.44,
   "gewinnJeAktie": 0.0933657,
   "dividende": 0.0427379,
   "divRendite": 3.17,
   "sektor": "Banken",
   "land": "Grossbritannien"
  },
  {
   "id": "ba1",
   "art": "aktie",
   "name": "BAE Systems",
   "kuerzel": "BA1",
   "kurs": 26.4248,
   "kursOriginal": 2258,
   "waehrungOriginal": "GBX",
   "kgv": 32.35,
   "gewinnJeAktie": 0.816841,
   "dividende": 0.425439,
   "divRendite": 1.61,
   "sektor": "Ruestung",
   "land": "Grossbritannien"
  },
  {
   "id": "rr",
   "art": "aktie",
   "name": "Rolls-Royce",
   "kuerzel": "RR",
   "kurs": 18.0339,
   "kursOriginal": 1541,
   "waehrungOriginal": "GBX",
   "kgv": 42.59,
   "gewinnJeAktie": 0.42343,
   "dividende": 0.140664,
   "divRendite": 0.78,
   "sektor": "Luftfahrt",
   "land": "Grossbritannien"
  },
  {
   "id": "nesn",
   "art": "aktie",
   "name": "Nestle",
   "kuerzel": "NESN",
   "kurs": 86.2726,
   "kursOriginal": 81.01,
   "waehrungOriginal": "CHF",
   "kgv": 28.02,
   "gewinnJeAktie": 3.079,
   "dividende": 3.3042,
   "divRendite": 3.83,
   "sektor": "Nahrung",
   "land": "Schweiz"
  },
  {
   "id": "ro",
   "art": "aktie",
   "name": "Roche",
   "kuerzel": "RO",
   "kurs": 385.3,
   "kursOriginal": 361.8,
   "waehrungOriginal": "CHF",
   "kgv": 22.98,
   "gewinnJeAktie": 16.7668,
   "dividende": 11.1352,
   "divRendite": 2.89,
   "sektor": "Pharma",
   "land": "Schweiz"
  },
  {
   "id": "zurn",
   "art": "aktie",
   "name": "Zurich Insurance",
   "kuerzel": "ZURN",
   "kurs": 631.31,
   "kursOriginal": 592.8,
   "waehrungOriginal": "CHF",
   "kgv": 14.87,
   "gewinnJeAktie": 42.4553,
   "dividende": 31.9443,
   "divRendite": 5.06,
   "sektor": "Versicherung",
   "land": "Schweiz"
  },
  {
   "id": "abbn",
   "art": "aktie",
   "name": "ABB",
   "kuerzel": "ABBN",
   "kurs": 88.1576,
   "kursOriginal": 82.78,
   "waehrungOriginal": "CHF",
   "kgv": 37.66,
   "gewinnJeAktie": 2.3409,
   "dividende": 1.005,
   "divRendite": 1.14,
   "sektor": "Industrie",
   "land": "Schweiz"
  },
  {
   "id": "ubsg",
   "art": "aktie",
   "name": "UBS Group",
   "kuerzel": "UBSG",
   "kurs": 46.3791,
   "kursOriginal": 43.55,
   "waehrungOriginal": "CHF",
   "kgv": 18.37,
   "gewinnJeAktie": 2.5247,
   "dividende": 0.950772,
   "divRendite": 2.05,
   "sektor": "Banken",
   "land": "Schweiz"
  },
  {
   "id": "cfr",
   "art": "aktie",
   "name": "Richemont",
   "kuerzel": "CFR",
   "kurs": 204.95,
   "kursOriginal": 192.45,
   "waehrungOriginal": "CHF",
   "kgv": 35.42,
   "gewinnJeAktie": 5.7863,
   "dividende": 3.5046,
   "divRendite": 1.71,
   "sektor": "Luxus",
   "land": "Schweiz"
  },
  {
   "id": "holn",
   "art": "aktie",
   "name": "Holcim",
   "kuerzel": "HOLN",
   "kurs": 76.2939,
   "kursOriginal": 71.64,
   "waehrungOriginal": "CHF",
   "kgv": 101.8,
   "gewinnJeAktie": 0.749449,
   "dividende": 1.8082,
   "divRendite": 2.37,
   "sektor": "Bau",
   "land": "Schweiz"
  },
  {
   "id": "sika",
   "art": "aktie",
   "name": "Sika",
   "kuerzel": "SIKA",
   "kurs": 203.25,
   "kursOriginal": 190.85,
   "waehrungOriginal": "CHF",
   "kgv": 29.45,
   "gewinnJeAktie": 6.9015,
   "dividende": 3.9431,
   "divRendite": 1.94,
   "sektor": "Chemie",
   "land": "Schweiz"
  },
  {
   "id": "sren",
   "art": "aktie",
   "name": "Swiss Re",
   "kuerzel": "SREN",
   "kurs": 148.51,
   "kursOriginal": 139.45,
   "waehrungOriginal": "CHF",
   "kgv": 10.51,
   "gewinnJeAktie": 14.1304,
   "dividende": 6.9206,
   "divRendite": 4.66,
   "sektor": "Versicherung",
   "land": "Schweiz"
  },
  {
   "id": "lonn",
   "art": "aktie",
   "name": "Lonza",
   "kuerzel": "LONN",
   "kurs": 599.15,
   "kursOriginal": 562.6,
   "waehrungOriginal": "CHF",
   "kgv": 36.37,
   "gewinnJeAktie": 16.4737,
   "dividende": 5.3324,
   "divRendite": 0.89,
   "sektor": "Pharma",
   "land": "Schweiz"
  },
  {
   "id": "7203",
   "art": "aktie",
   "name": "Toyota Motor",
   "kuerzel": "7203",
   "kurs": 16.3758,
   "kursOriginal": 3012,
   "waehrungOriginal": "JPY",
   "kgv": 8.64,
   "gewinnJeAktie": 1.8953,
   "dividende": 0.542039,
   "divRendite": 3.31,
   "sektor": "Automobil",
   "land": "Japan"
  },
  {
   "id": "6758",
   "art": "aktie",
   "name": "Sony Group",
   "kuerzel": "6758",
   "kurs": 20.5894,
   "kursOriginal": 3787,
   "waehrungOriginal": "JPY",
   "kgv": 20.88,
   "gewinnJeAktie": 0.986082,
   "dividende": 0.183246,
   "divRendite": 0.89,
   "sektor": "Technologie",
   "land": "Japan"
  },
  {
   "id": "7974",
   "art": "aktie",
   "name": "Nintendo",
   "kuerzel": "7974",
   "kurs": 47.7247,
   "kursOriginal": 8778,
   "waehrungOriginal": "JPY",
   "kgv": 21.72,
   "gewinnJeAktie": 2.1973,
   "dividende": 0.86859,
   "divRendite": 1.82,
   "sektor": "Medien",
   "land": "Japan"
  },
  {
   "id": "6861",
   "art": "aktie",
   "name": "Keyence",
   "kuerzel": "6861",
   "kurs": 472.84,
   "kursOriginal": 86970,
   "waehrungOriginal": "JPY",
   "kgv": 43.19,
   "gewinnJeAktie": 10.9479,
   "dividende": 2.9789,
   "divRendite": 0.63,
   "sektor": "Industrie",
   "land": "Japan"
  },
  {
   "id": "8035",
   "art": "aktie",
   "name": "Tokyo Electron",
   "kuerzel": "8035",
   "kurs": 326.37,
   "kursOriginal": 60030,
   "waehrungOriginal": "JPY",
   "kgv": 43.66,
   "gewinnJeAktie": 7.4753,
   "dividende": 4.1449,
   "divRendite": 1.27,
   "sektor": "Halbleiter",
   "land": "Japan"
  },
  {
   "id": "6857",
   "art": "aktie",
   "name": "Advantest",
   "kuerzel": "6857",
   "kurs": 204.75,
   "kursOriginal": 37660,
   "waehrungOriginal": "JPY",
   "kgv": 58.5,
   "gewinnJeAktie": 3.5,
   "dividende": 0.3276,
   "divRendite": 0.16,
   "sektor": "Halbleiter",
   "land": "Japan"
  },
  {
   "id": "9984",
   "art": "aktie",
   "name": "SoftBank Group",
   "kuerzel": "9984",
   "kurs": 31.9361,
   "kursOriginal": 5874,
   "waehrungOriginal": "JPY",
   "kgv": 6.67,
   "gewinnJeAktie": 4.788,
   "dividende": 0.0606786,
   "divRendite": 0.19,
   "sektor": "Technologie",
   "land": "Japan"
  },
  {
   "id": "6501",
   "art": "aktie",
   "name": "Hitachi",
   "kuerzel": "6501",
   "kurs": 30.3811,
   "kursOriginal": 5588,
   "waehrungOriginal": "JPY",
   "kgv": 32.6,
   "gewinnJeAktie": 0.931936,
   "dividende": 0.294697,
   "divRendite": 0.97,
   "sektor": "Industrie",
   "land": "Japan"
  },
  {
   "id": "8058",
   "art": "aktie",
   "name": "Mitsubishi Corporation",
   "kuerzel": "8058",
   "kurs": 25.6402,
   "kursOriginal": 4716,
   "waehrungOriginal": "JPY",
   "kgv": 19.95,
   "gewinnJeAktie": 1.2852,
   "dividende": 0.671773,
   "divRendite": 2.62,
   "sektor": "Handel",
   "land": "Japan"
  },
  {
   "id": "4063",
   "art": "aktie",
   "name": "Shin-Etsu Chemical",
   "kuerzel": "4063",
   "kurs": 34.6925,
   "kursOriginal": 6381,
   "waehrungOriginal": "JPY",
   "kgv": 24.87,
   "gewinnJeAktie": 1.395,
   "dividende": 0.631404,
   "divRendite": 1.82,
   "sektor": "Chemie",
   "land": "Japan"
  },
  {
   "id": "4502",
   "art": "aktie",
   "name": "Takeda Pharmaceutical",
   "kuerzel": "4502",
   "kurs": 30.0332,
   "kursOriginal": 5524,
   "waehrungOriginal": "JPY",
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 1.0932,
   "divRendite": 3.64,
   "sektor": "Pharma",
   "land": "Japan"
  },
  {
   "id": "7267",
   "art": "aktie",
   "name": "Honda Motor",
   "kuerzel": "7267",
   "kurs": 9.2291,
   "kursOriginal": 1697.5,
   "waehrungOriginal": "JPY",
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0.389468,
   "divRendite": 4.22,
   "sektor": "Automobil",
   "land": "Japan"
  },
  {
   "id": "8316",
   "art": "aktie",
   "name": "Sumitomo Mitsui Financial",
   "kuerzel": "8316",
   "kurs": 37.6991,
   "kursOriginal": 6934,
   "waehrungOriginal": "JPY",
   "kgv": 21.14,
   "gewinnJeAktie": 1.7833,
   "dividende": 0.972637,
   "divRendite": 2.58,
   "sektor": "Banken",
   "land": "Japan"
  },
  {
   "id": "9983",
   "art": "aktie",
   "name": "Fast Retailing",
   "kuerzel": "9983",
   "kurs": 417.71,
   "kursOriginal": 76830,
   "waehrungOriginal": "JPY",
   "kgv": 45.57,
   "gewinnJeAktie": 9.1663,
   "dividende": 3.467,
   "divRendite": 0.83,
   "sektor": "Handel",
   "land": "Japan"
  },
  {
   "id": "9432",
   "art": "aktie",
   "name": "Nippon Telegraph & Telephone",
   "kuerzel": "9432",
   "kurs": 0.879682,
   "kursOriginal": 161.8,
   "waehrungOriginal": "JPY",
   "kgv": 12.67,
   "gewinnJeAktie": 0.0694303,
   "dividende": 0.0292054,
   "divRendite": 3.32,
   "sektor": "Telekom",
   "land": "Japan"
  },
  {
   "id": "005930",
   "art": "aktie",
   "name": "Samsung Electronics",
   "kuerzel": "005930",
   "kurs": 168.16,
   "kursOriginal": 274500,
   "waehrungOriginal": "KRW",
   "kgv": 12.09,
   "gewinnJeAktie": 13.909,
   "dividende": 1.3789,
   "divRendite": 0.82,
   "sektor": "Technologie",
   "land": "Suedkorea"
  },
  {
   "id": "005380",
   "art": "aktie",
   "name": "Hyundai Motor",
   "kuerzel": "005380",
   "kurs": 277.5,
   "kursOriginal": 453000,
   "waehrungOriginal": "KRW",
   "kgv": 14.33,
   "gewinnJeAktie": 19.365,
   "dividende": 6.1328,
   "divRendite": 2.21,
   "sektor": "Automobil",
   "land": "Suedkorea"
  },
  {
   "id": "000270",
   "art": "aktie",
   "name": "Kia",
   "kuerzel": "000270",
   "kurs": 86.8036,
   "kursOriginal": 141700,
   "waehrungOriginal": "KRW",
   "kgv": 7.87,
   "gewinnJeAktie": 11.0297,
   "dividende": 4.1666,
   "divRendite": 4.8,
   "sektor": "Automobil",
   "land": "Suedkorea"
  },
  {
   "id": "035420",
   "art": "aktie",
   "name": "NAVER",
   "kuerzel": "035420",
   "kurs": 139.67,
   "kursOriginal": 228000,
   "waehrungOriginal": "KRW",
   "kgv": 18.99,
   "gewinnJeAktie": 7.3549,
   "dividende": 1.6062,
   "divRendite": 1.15,
   "sektor": "Technologie",
   "land": "Suedkorea"
  },
  {
   "id": "207940",
   "art": "aktie",
   "name": "Samsung Biologics",
   "kuerzel": "207940",
   "kurs": 948.29,
   "kursOriginal": 1548000,
   "waehrungOriginal": "KRW",
   "kgv": 38.49,
   "gewinnJeAktie": 24.6373,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Pharma",
   "land": "Suedkorea"
  },
  {
   "id": "005490",
   "art": "aktie",
   "name": "POSCO Holdings",
   "kuerzel": "005490",
   "kurs": 204.6,
   "kursOriginal": 334000,
   "waehrungOriginal": "KRW",
   "kgv": 19.51,
   "gewinnJeAktie": 10.4869,
   "dividende": 4.9104,
   "divRendite": 2.4,
   "sektor": "Industrie",
   "land": "Suedkorea"
  },
  {
   "id": "373220",
   "art": "aktie",
   "name": "LG Energy Solution",
   "kuerzel": "373220",
   "kurs": 226.35,
   "kursOriginal": 369500,
   "waehrungOriginal": "KRW",
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Industrie",
   "land": "Suedkorea"
  },
  {
   "id": "0700",
   "art": "aktie",
   "name": "Tencent Holdings",
   "kuerzel": "0700",
   "kurs": 49.4436,
   "kursOriginal": 448.8,
   "waehrungOriginal": "HKD",
   "kgv": 14.98,
   "gewinnJeAktie": 3.3006,
   "dividende": 0.593323,
   "divRendite": 1.2,
   "sektor": "Technologie",
   "land": "Hongkong"
  },
  {
   "id": "1299",
   "art": "aktie",
   "name": "AIA Group",
   "kuerzel": "1299",
   "kurs": 8.0478,
   "kursOriginal": 73.05,
   "waehrungOriginal": "HKD",
   "kgv": 15.33,
   "gewinnJeAktie": 0.524971,
   "dividende": 0.22051,
   "divRendite": 2.74,
   "sektor": "Versicherung",
   "land": "Hongkong"
  },
  {
   "id": "0388",
   "art": "aktie",
   "name": "Hong Kong Exchanges",
   "kuerzel": "0388",
   "kurs": 44.8386,
   "kursOriginal": 407,
   "waehrungOriginal": "HKD",
   "kgv": 27.31,
   "gewinnJeAktie": 1.6418,
   "dividende": 1.4393,
   "divRendite": 3.21,
   "sektor": "Finanzen",
   "land": "Hongkong"
  },
  {
   "id": "shop",
   "art": "aktie",
   "name": "Shopify",
   "kuerzel": "SHOP",
   "kurs": 133.56,
   "kursOriginal": 214.35,
   "waehrungOriginal": "CAD",
   "kgv": 100.64,
   "gewinnJeAktie": 1.3271,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Technologie",
   "land": "Kanada"
  },
  {
   "id": "td",
   "art": "aktie",
   "name": "Toronto-Dominion Bank",
   "kuerzel": "TD",
   "kurs": 107.55,
   "kursOriginal": 172.61,
   "waehrungOriginal": "CAD",
   "kgv": 20.39,
   "gewinnJeAktie": 5.2746,
   "dividende": 2.7963,
   "divRendite": 2.6,
   "sektor": "Banken",
   "land": "Kanada"
  },
  {
   "id": "bns",
   "art": "aktie",
   "name": "Bank of Nova Scotia",
   "kuerzel": "BNS",
   "kurs": 79.1202,
   "kursOriginal": 126.98,
   "waehrungOriginal": "CAD",
   "kgv": 17.49,
   "gewinnJeAktie": 4.5237,
   "dividende": 2.8404,
   "divRendite": 3.59,
   "sektor": "Banken",
   "land": "Kanada"
  },
  {
   "id": "bmo",
   "art": "aktie",
   "name": "Bank of Montreal",
   "kuerzel": "BMO",
   "kurs": 160.68,
   "kursOriginal": 257.88,
   "waehrungOriginal": "CAD",
   "kgv": 19.81,
   "gewinnJeAktie": 8.1111,
   "dividende": 4.258,
   "divRendite": 2.65,
   "sektor": "Banken",
   "land": "Kanada"
  },
  {
   "id": "enb",
   "art": "aktie",
   "name": "Enbridge",
   "kuerzel": "ENB",
   "kurs": 43.9965,
   "kursOriginal": 70.61,
   "waehrungOriginal": "CAD",
   "kgv": 27.26,
   "gewinnJeAktie": 1.614,
   "dividende": 2.4198,
   "divRendite": 5.5,
   "sektor": "Energie",
   "land": "Kanada"
  },
  {
   "id": "cnq",
   "art": "aktie",
   "name": "Canadian Natural Resources",
   "kuerzel": "CNQ",
   "kurs": 41.3795,
   "kursOriginal": 66.41,
   "waehrungOriginal": "CAD",
   "kgv": 11.81,
   "gewinnJeAktie": 3.5038,
   "dividende": 1.5559,
   "divRendite": 3.76,
   "sektor": "Energie",
   "land": "Kanada"
  },
  {
   "id": "cnr",
   "art": "aktie",
   "name": "Canadian National Railway",
   "kuerzel": "CNR",
   "kurs": 109.58,
   "kursOriginal": 175.87,
   "waehrungOriginal": "CAD",
   "kgv": 22.57,
   "gewinnJeAktie": 4.8551,
   "dividende": 2.2793,
   "divRendite": 2.08,
   "sektor": "Logistik",
   "land": "Kanada"
  },
  {
   "id": "cp",
   "art": "aktie",
   "name": "Canadian Pacific Kansas City",
   "kuerzel": "CP",
   "kurs": 80.8649,
   "kursOriginal": 129.78,
   "waehrungOriginal": "CAD",
   "kgv": 30.19,
   "gewinnJeAktie": 2.6785,
   "dividende": 0.671179,
   "divRendite": 0.83,
   "sektor": "Logistik",
   "land": "Kanada"
  },
  {
   "id": "bce",
   "art": "aktie",
   "name": "BCE",
   "kuerzel": "BCE",
   "kurs": 20.2941,
   "kursOriginal": 32.57,
   "waehrungOriginal": "CAD",
   "kgv": 4.84,
   "gewinnJeAktie": 4.193,
   "dividende": 1.0898,
   "divRendite": 5.37,
   "sektor": "Telekom",
   "land": "Kanada"
  },
  {
   "id": "bn1",
   "art": "aktie",
   "name": "Brookfield Corporation",
   "kuerzel": "BN1",
   "kurs": 37.9214,
   "kursOriginal": 60.86,
   "waehrungOriginal": "CAD",
   "kgv": 79.73,
   "gewinnJeAktie": 0.475623,
   "dividende": 0.242697,
   "divRendite": 0.64,
   "sektor": "Finanzen",
   "land": "Kanada"
  },
  {
   "id": "ba",
   "art": "aktie",
   "name": "Boeing",
   "kuerzel": "BA",
   "kurs": 200.29,
   "kursOriginal": 231.67,
   "waehrungOriginal": "USD",
   "kgv": 86.39,
   "gewinnJeAktie": 2.3184,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Luftfahrt",
   "land": "USA"
  },
  {
   "id": "dis",
   "art": "aktie",
   "name": "Walt Disney",
   "kuerzel": "DIS",
   "kurs": 92.3749,
   "kursOriginal": 106.85,
   "waehrungOriginal": "USD",
   "kgv": 22.09,
   "gewinnJeAktie": 4.1818,
   "dividende": 1.2932,
   "divRendite": 1.4,
   "sektor": "Medien",
   "land": "USA"
  },
  {
   "id": "vz",
   "art": "aktie",
   "name": "Verizon Communications",
   "kuerzel": "VZ",
   "kurs": 41.9123,
   "kursOriginal": 48.48,
   "waehrungOriginal": "USD",
   "kgv": 12.63,
   "gewinnJeAktie": 3.3185,
   "dividende": 2.4477,
   "divRendite": 5.84,
   "sektor": "Telekom",
   "land": "USA"
  },
  {
   "id": "lmt",
   "art": "aktie",
   "name": "Lockheed Martin",
   "kuerzel": "LMT",
   "kurs": 526.22,
   "kursOriginal": 608.68,
   "waehrungOriginal": "USD",
   "kgv": 22.43,
   "gewinnJeAktie": 23.4605,
   "dividende": 11.9452,
   "divRendite": 2.27,
   "sektor": "Ruestung",
   "land": "USA"
  },
  {
   "id": "amt",
   "art": "aktie",
   "name": "American Tower",
   "kuerzel": "AMT",
   "kurs": 151.79,
   "kursOriginal": 175.58,
   "waehrungOriginal": "USD",
   "kgv": 24.15,
   "gewinnJeAktie": 6.2853,
   "dividende": 6.193,
   "divRendite": 4.08,
   "sektor": "Immobilien",
   "land": "USA"
  },
  {
   "id": "crm",
   "art": "aktie",
   "name": "Salesforce",
   "kuerzel": "CRM",
   "kurs": 169.63,
   "kursOriginal": 196.21,
   "waehrungOriginal": "USD",
   "kgv": 22.78,
   "gewinnJeAktie": 7.4464,
   "dividende": 1.5267,
   "divRendite": 0.9,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "adbe",
   "art": "aktie",
   "name": "Adobe",
   "kuerzel": "ADBE",
   "kurs": 228.25,
   "kursOriginal": 264.02,
   "waehrungOriginal": "USD",
   "kgv": 15.1,
   "gewinnJeAktie": 15.1159,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "qcom",
   "art": "aktie",
   "name": "Qualcomm",
   "kuerzel": "QCOM",
   "kurs": 143.33,
   "kursOriginal": 165.79,
   "waehrungOriginal": "USD",
   "kgv": 19.29,
   "gewinnJeAktie": 7.4303,
   "dividende": 3.1819,
   "divRendite": 2.22,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "ibm",
   "art": "aktie",
   "name": "IBM",
   "kuerzel": "IBM",
   "kurs": 202.58,
   "kursOriginal": 234.32,
   "waehrungOriginal": "USD",
   "kgv": 20.83,
   "gewinnJeAktie": 9.7254,
   "dividende": 5.8546,
   "divRendite": 2.89,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "pfe",
   "art": "aktie",
   "name": "Pfizer",
   "kuerzel": "PFE",
   "kurs": 23.1607,
   "kursOriginal": 26.79,
   "waehrungOriginal": "USD",
   "kgv": 35.22,
   "gewinnJeAktie": 0.657601,
   "dividende": 1.4869,
   "divRendite": 6.42,
   "sektor": "Pharma",
   "land": "USA"
  },
  {
   "id": "abbv",
   "art": "aktie",
   "name": "AbbVie",
   "kuerzel": "ABBV",
   "kurs": 215.67,
   "kursOriginal": 249.46,
   "waehrungOriginal": "USD",
   "kgv": 70.47,
   "gewinnJeAktie": 3.0605,
   "dividende": 5.9741,
   "divRendite": 2.77,
   "sektor": "Pharma",
   "land": "USA"
  },
  {
   "id": "mcd",
   "art": "aktie",
   "name": "McDonald's",
   "kuerzel": "MCD",
   "kurs": 235.87,
   "kursOriginal": 272.83,
   "waehrungOriginal": "USD",
   "kgv": 22.16,
   "gewinnJeAktie": 10.644,
   "dividende": 6.4393,
   "divRendite": 2.73,
   "sektor": "Nahrung",
   "land": "USA"
  },
  {
   "id": "nke",
   "art": "aktie",
   "name": "Nike",
   "kuerzel": "NKE",
   "kurs": 35.2122,
   "kursOriginal": 40.73,
   "waehrungOriginal": "USD",
   "kgv": 19.4,
   "gewinnJeAktie": 1.8151,
   "dividende": 1.4191,
   "divRendite": 4.03,
   "sektor": "Konsum",
   "land": "USA"
  },
  {
   "id": "pep",
   "art": "aktie",
   "name": "PepsiCo",
   "kuerzel": "PEP",
   "kurs": 121.72,
   "kursOriginal": 140.79,
   "waehrungOriginal": "USD",
   "kgv": 18.45,
   "gewinnJeAktie": 6.5973,
   "dividende": 5.1244,
   "divRendite": 4.21,
   "sektor": "Nahrung",
   "land": "USA"
  },
  {
   "id": "coin",
   "art": "aktie",
   "name": "Coinbase",
   "kuerzel": "COIN",
   "kurs": 128.36,
   "kursOriginal": 148.47,
   "waehrungOriginal": "USD",
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Finanzen",
   "land": "USA"
  },
  {
   "id": "voo",
   "art": "etf",
   "name": "Vanguard S&P 500 ETF",
   "kuerzel": "VOO",
   "kurs": 616.94,
   "kursOriginal": 713.61,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 1050,
   "anzahlPositionen": 520,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "USA breit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "qqq",
   "art": "etf",
   "name": "Invesco QQQ Trust",
   "kuerzel": "QQQ",
   "kurs": 632.03,
   "kursOriginal": 731.07,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 496.1,
   "anzahlPositionen": 105,
   "ter": 0.18,
   "ausschuettend": true,
   "sektor": "USA Technologie",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vt",
   "art": "etf",
   "name": "Vanguard Total World Stock ETF",
   "kuerzel": "VT",
   "kurs": 140.27,
   "kursOriginal": 162.25,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 82,
   "anzahlPositionen": 10144,
   "ter": 0.06,
   "ausschuettend": true,
   "sektor": "Welt",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vea",
   "art": "etf",
   "name": "Vanguard FTSE Developed Markets ETF",
   "kuerzel": "VEA",
   "kurs": 63.612,
   "kursOriginal": 73.58,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 239.2,
   "anzahlPositionen": 3877,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "Welt ohne USA",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vwo",
   "art": "etf",
   "name": "Vanguard FTSE Emerging Markets ETF",
   "kuerzel": "VWO",
   "kurs": 51.9668,
   "kursOriginal": 60.11,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 125.3,
   "anzahlPositionen": 5063,
   "ter": 0.06,
   "ausschuettend": true,
   "sektor": "Schwellenlaender",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "efa",
   "art": "etf",
   "name": "iShares MSCI EAFE ETF",
   "kuerzel": "EFA",
   "kurs": 93.9224,
   "kursOriginal": 108.64,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 80.2,
   "anzahlPositionen": 699,
   "ter": 0.32,
   "ausschuettend": true,
   "sektor": "Europa/Asien",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "iwm",
   "art": "etf",
   "name": "iShares Russell 2000 ETF",
   "kuerzel": "IWM",
   "kurs": 263.76,
   "kursOriginal": 305.09,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 83.3,
   "anzahlPositionen": 1971,
   "ter": 0.19,
   "ausschuettend": true,
   "sektor": "USA klein",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "ijh",
   "art": "etf",
   "name": "iShares Core S&P Mid-Cap ETF",
   "kuerzel": "IJH",
   "kurs": 68.0124,
   "kursOriginal": 78.67,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 128.7,
   "anzahlPositionen": 414,
   "ter": 0.05,
   "ausschuettend": true,
   "sektor": "USA mittel",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "dia",
   "art": "etf",
   "name": "SPDR Dow Jones Industrial Average ETF",
   "kuerzel": "DIA",
   "kurs": 464.08,
   "kursOriginal": 536.8,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 46.9,
   "anzahlPositionen": 31,
   "ter": 0.16,
   "ausschuettend": true,
   "sektor": "USA Standard",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "rsp",
   "art": "etf",
   "name": "Invesco S&P 500 Equal Weight ETF",
   "kuerzel": "RSP",
   "kurs": 192.59,
   "kursOriginal": 222.77,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 98.8,
   "anzahlPositionen": 509,
   "ter": 0.2,
   "ausschuettend": true,
   "sektor": "USA breit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vug",
   "art": "etf",
   "name": "Vanguard Growth ETF",
   "kuerzel": "VUG",
   "kurs": 77.237,
   "kursOriginal": 89.34,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 229.8,
   "anzahlPositionen": 151,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "USA Wachstum",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vtv",
   "art": "etf",
   "name": "Vanguard Value ETF",
   "kuerzel": "VTV",
   "kurs": 196.69,
   "kursOriginal": 227.51,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 194.5,
   "anzahlPositionen": 326,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "USA Substanz",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "schd",
   "art": "etf",
   "name": "Schwab US Dividend Equity ETF",
   "kuerzel": "SCHD",
   "kurs": 29.8435,
   "kursOriginal": 34.52,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 109.2,
   "anzahlPositionen": 103,
   "ter": 0.06,
   "ausschuettend": true,
   "sektor": "Dividenden",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vym",
   "art": "etf",
   "name": "Vanguard High Dividend Yield ETF",
   "kuerzel": "VYM",
   "kurs": 143.96,
   "kursOriginal": 166.52,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 84.3,
   "anzahlPositionen": 618,
   "ter": 0.04,
   "ausschuettend": true,
   "sektor": "Dividenden",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlk",
   "art": "etf",
   "name": "Technology Select Sector SPDR",
   "kuerzel": "XLK",
   "kurs": 164.27,
   "kursOriginal": 190.01,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 124,
   "anzahlPositionen": 76,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Technologie",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "soxx",
   "art": "etf",
   "name": "iShares Semiconductor ETF",
   "kuerzel": "SOXX",
   "kurs": 475.85,
   "kursOriginal": 550.42,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 43.5,
   "anzahlPositionen": 34,
   "ter": 0.33,
   "ausschuettend": true,
   "sektor": "Halbleiter",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlv",
   "art": "etf",
   "name": "Health Care Select Sector SPDR",
   "kuerzel": "XLV",
   "kurs": 144.7,
   "kursOriginal": 167.37,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 43.7,
   "anzahlPositionen": 63,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Gesundheit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlf",
   "art": "etf",
   "name": "Financial Select Sector SPDR",
   "kuerzel": "XLF",
   "kurs": 50.281,
   "kursOriginal": 58.16,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 58.3,
   "anzahlPositionen": 80,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Finanzen",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xle",
   "art": "etf",
   "name": "Energy Select Sector SPDR",
   "kuerzel": "XLE",
   "kurs": 53.523,
   "kursOriginal": 61.91,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 40.5,
   "anzahlPositionen": 24,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Energie",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vnq",
   "art": "etf",
   "name": "Vanguard Real Estate ETF",
   "kuerzel": "VNQ",
   "kurs": 85.4413,
   "kursOriginal": 98.83,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 39.2,
   "anzahlPositionen": 157,
   "ter": 0.13,
   "ausschuettend": true,
   "sektor": "Immobilien",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "gld",
   "art": "etf",
   "name": "SPDR Gold Shares",
   "kuerzel": "GLD",
   "kurs": 347.09,
   "kursOriginal": 401.48,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 144.5,
   "anzahlPositionen": 2,
   "ter": 0.4,
   "ausschuettend": true,
   "sektor": "Rohstoffe",
   "anlageklasse": "Rohstoff",
   "land": null
  },
  {
   "id": "agg",
   "art": "etf",
   "name": "iShares Core US Aggregate Bond ETF",
   "kuerzel": "AGG",
   "kurs": 84.2742,
   "kursOriginal": 97.48,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 138,
   "anzahlPositionen": 13371,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "Anleihen",
   "anlageklasse": "Anleihen",
   "land": null
  },
  {
   "id": "tlt",
   "art": "etf",
   "name": "iShares 20+ Year Treasury Bond ETF",
   "kuerzel": "TLT",
   "kurs": 70.9259,
   "kursOriginal": 82.04,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 45.7,
   "anzahlPositionen": 48,
   "ter": 0.15,
   "ausschuettend": true,
   "sektor": "Anleihen",
   "anlageklasse": "Anleihen",
   "land": null
  },
  {
   "id": "vcit",
   "art": "etf",
   "name": "Vanguard Interm.-Term Corp. Bond ETF",
   "kuerzel": "VCIT",
   "kurs": 70.2256,
   "kursOriginal": 81.23,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 67.9,
   "anzahlPositionen": 2268,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "Anleihen",
   "anlageklasse": "Anleihen",
   "land": null
  },
  {
   "id": "ibit",
   "art": "etf",
   "name": "iShares Bitcoin Trust",
   "kuerzel": "IBIT",
   "kurs": 30.8031,
   "kursOriginal": 35.63,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 47,
   "anzahlPositionen": 2,
   "ter": 0.25,
   "ausschuettend": true,
   "sektor": "Krypto",
   "anlageklasse": "Krypto",
   "land": null
  },
  {
   "id": "spy",
   "art": "etf",
   "name": "SPDR S&P 500 ETF Trust",
   "kuerzel": "SPY",
   "kurs": 671.17,
   "kursOriginal": 776.34,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 824,
   "anzahlPositionen": 505,
   "ter": 0.09,
   "ausschuettend": true,
   "sektor": "USA breit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "ivv",
   "art": "etf",
   "name": "iShares Core S&P 500 ETF",
   "kuerzel": "IVV",
   "kurs": 674.37,
   "kursOriginal": 780.04,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 905.5,
   "anzahlPositionen": 508,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "USA breit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vti",
   "art": "etf",
   "name": "Vanguard Total Stock Market ETF",
   "kuerzel": "VTI",
   "kurs": 331.85,
   "kursOriginal": 383.85,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 696.1,
   "anzahlPositionen": 3498,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "USA breit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "iefa",
   "art": "etf",
   "name": "iShares Core MSCI EAFE ETF",
   "kuerzel": "IEFA",
   "kurs": 87.4816,
   "kursOriginal": 101.19,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 195.8,
   "anzahlPositionen": 2641,
   "ter": 0.07,
   "ausschuettend": true,
   "sektor": "Europa/Asien",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "iemg",
   "art": "etf",
   "name": "iShares Core MSCI Emerging Markets ETF",
   "kuerzel": "IEMG",
   "kurs": 70.1911,
   "kursOriginal": 81.19,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 159,
   "anzahlPositionen": 2896,
   "ter": 0.09,
   "ausschuettend": true,
   "sektor": "Schwellenlaender",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "ewj",
   "art": "etf",
   "name": "iShares MSCI Japan ETF",
   "kuerzel": "EWJ",
   "kurs": 84.9053,
   "kursOriginal": 98.21,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 23.1,
   "anzahlPositionen": 175,
   "ter": 0.49,
   "ausschuettend": true,
   "sektor": "Japan",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "ezu",
   "art": "etf",
   "name": "iShares MSCI Eurozone ETF",
   "kuerzel": "EZU",
   "kurs": 62.2374,
   "kursOriginal": 71.99,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 10,
   "anzahlPositionen": 226,
   "ter": 0.5,
   "ausschuettend": true,
   "sektor": "Eurozone",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "fxi",
   "art": "etf",
   "name": "iShares China Large-Cap ETF",
   "kuerzel": "FXI",
   "kurs": 30.1634,
   "kursOriginal": 34.89,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 4.2,
   "anzahlPositionen": 59,
   "ter": 0.74,
   "ausschuettend": true,
   "sektor": "China",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "inda",
   "art": "etf",
   "name": "iShares MSCI India ETF",
   "kuerzel": "INDA",
   "kurs": 43.0362,
   "kursOriginal": 49.78,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 6.7,
   "anzahlPositionen": 173,
   "ter": 0.61,
   "ausschuettend": true,
   "sektor": "Indien",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xli",
   "art": "etf",
   "name": "Industrial Select Sector SPDR",
   "kuerzel": "XLI",
   "kurs": 161.24,
   "kursOriginal": 186.51,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 34.7,
   "anzahlPositionen": 86,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Industrie",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xly",
   "art": "etf",
   "name": "Consumer Discretionary Select Sector SPDR",
   "kuerzel": "XLY",
   "kurs": 102.19,
   "kursOriginal": 118.2,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 23.4,
   "anzahlPositionen": 50,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Konsum",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlp",
   "art": "etf",
   "name": "Consumer Staples Select Sector SPDR",
   "kuerzel": "XLP",
   "kurs": 74.4272,
   "kursOriginal": 86.09,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 14.9,
   "anzahlPositionen": 38,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Nahrung",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlu",
   "art": "etf",
   "name": "Utilities Select Sector SPDR",
   "kuerzel": "XLU",
   "kurs": 38.3073,
   "kursOriginal": 44.31,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 22.9,
   "anzahlPositionen": 34,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Versorger",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlc",
   "art": "etf",
   "name": "Communication Services Select Sector SPDR",
   "kuerzel": "XLC",
   "kurs": 97.6485,
   "kursOriginal": 112.95,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 22.7,
   "anzahlPositionen": 26,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Medien",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "slv",
   "art": "etf",
   "name": "iShares Silver Trust",
   "kuerzel": "SLV",
   "kurs": 50.5576,
   "kursOriginal": 58.48,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 31.8,
   "anzahlPositionen": 1,
   "ter": 0.5,
   "ausschuettend": true,
   "sektor": "Rohstoffe",
   "anlageklasse": "Rohstoff",
   "land": null
  },
  {
   "id": "dbc",
   "art": "etf",
   "name": "Invesco DB Commodity Index Tracking Fund",
   "kuerzel": "DBC",
   "kurs": 25.9359,
   "kursOriginal": 30,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 1.8,
   "anzahlPositionen": 41,
   "ter": 0.84,
   "ausschuettend": true,
   "sektor": "Rohstoffe",
   "anlageklasse": "Rohstoff",
   "land": null
  },
  {
   "id": "lqd",
   "art": "etf",
   "name": "iShares iBoxx Investment Grade Corporate Bond ETF",
   "kuerzel": "LQD",
   "kurs": 91.7438,
   "kursOriginal": 106.12,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 33.2,
   "anzahlPositionen": 3143,
   "ter": 0.14,
   "ausschuettend": true,
   "sektor": "Anleihen",
   "anlageklasse": "Anleihen",
   "land": null
  },
  {
   "id": "hyg",
   "art": "etf",
   "name": "iShares iBoxx High Yield Corporate Bond ETF",
   "kuerzel": "HYG",
   "kurs": 68.9116,
   "kursOriginal": 79.71,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 18,
   "anzahlPositionen": 1333,
   "ter": 0.49,
   "ausschuettend": true,
   "sektor": "Anleihen",
   "anlageklasse": "Anleihen",
   "land": null
  },
  {
   "id": "etha",
   "art": "etf",
   "name": "iShares Ethereum Trust",
   "kuerzel": "ETHA",
   "kurs": 12.259,
   "kursOriginal": 14.18,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 5.6,
   "anzahlPositionen": 2,
   "ter": 0.25,
   "ausschuettend": true,
   "sektor": "Krypto",
   "anlageklasse": "Krypto",
   "land": null
  },
  {
   "id": "btc",
   "art": "krypto",
   "name": "Bitcoin",
   "kuerzel": "BTC",
   "kurs": 54812,
   "marktkapitalisierung": 1100117254842,
   "umlaufmenge": 20071346,
   "hoechstmenge": 21000000,
   "allzeithoch": 107662,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "eth",
   "art": "krypto",
   "name": "Ethereum",
   "kuerzel": "ETH",
   "kurs": 1639.35,
   "marktkapitalisierung": 197832270281,
   "umlaufmenge": 120681932,
   "hoechstmenge": null,
   "allzeithoch": 4229.76,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "xrp",
   "art": "krypto",
   "name": "XRP",
   "kuerzel": "XRP",
   "kurs": 0.865586,
   "marktkapitalisierung": 54248301400,
   "umlaufmenge": 62676938832,
   "hoechstmenge": 100000000000,
   "allzeithoch": 3.28,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "sol",
   "art": "krypto",
   "name": "Solana",
   "kuerzel": "SOL",
   "kurs": 65.1,
   "marktkapitalisierung": 37945038260,
   "umlaufmenge": 582899583,
   "hoechstmenge": null,
   "allzeithoch": 285.6,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "doge",
   "art": "krypto",
   "name": "Dogecoin",
   "kuerzel": "DOGE",
   "kurs": 0.060569,
   "marktkapitalisierung": 9420046959,
   "umlaufmenge": 155526026384,
   "hoechstmenge": null,
   "allzeithoch": 0.601466,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "ada",
   "art": "krypto",
   "name": "Cardano",
   "kuerzel": "ADA",
   "kurs": 0.152477,
   "marktkapitalisierung": 5696822250,
   "umlaufmenge": 37359859978,
   "hoechstmenge": 45000000000,
   "allzeithoch": 2.61,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "link",
   "art": "krypto",
   "name": "Chainlink",
   "kuerzel": "LINK",
   "kurs": 8.14,
   "marktkapitalisierung": 6089826707,
   "umlaufmenge": 748099970,
   "hoechstmenge": 1000000000,
   "allzeithoch": 43.32,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "ltc",
   "art": "krypto",
   "name": "Litecoin",
   "kuerzel": "LTC",
   "kurs": 38.13,
   "marktkapitalisierung": 2955010505,
   "umlaufmenge": 77503154,
   "hoechstmenge": 84000000,
   "allzeithoch": 337.56,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "avax",
   "art": "krypto",
   "name": "Avalanche",
   "kuerzel": "AVAX",
   "kurs": 5.47,
   "marktkapitalisierung": 2362434855,
   "umlaufmenge": 431771961,
   "hoechstmenge": 720000000,
   "allzeithoch": 128.43,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "dot",
   "art": "krypto",
   "name": "Polkadot",
   "kuerzel": "DOT",
   "kurs": 0.659194,
   "marktkapitalisierung": 1119651977,
   "umlaufmenge": 1698389301,
   "hoechstmenge": 2100000000,
   "allzeithoch": 47.6,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "bnb",
   "art": "krypto",
   "name": "BNB",
   "kuerzel": "BNB",
   "kurs": 522.42,
   "marktkapitalisierung": 69563792240,
   "umlaufmenge": 133163748,
   "hoechstmenge": 200000000,
   "allzeithoch": 1182.86,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "trx",
   "art": "krypto",
   "name": "Tron",
   "kuerzel": "TRX",
   "kurs": 0.286756,
   "marktkapitalisierung": 27213590926,
   "umlaufmenge": 94904800478,
   "hoechstmenge": null,
   "allzeithoch": 0.410308,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "ton",
   "art": "krypto",
   "name": "Toncoin",
   "kuerzel": "TON",
   "kurs": 1.15,
   "marktkapitalisierung": 3175334451,
   "umlaufmenge": 2759533209,
   "hoechstmenge": null,
   "allzeithoch": 7.7,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "aave",
   "art": "krypto",
   "name": "Aave",
   "kuerzel": "AAVE",
   "kurs": 74.42,
   "marktkapitalisierung": 1147675656,
   "umlaufmenge": 15422794,
   "hoechstmenge": 16000000,
   "allzeithoch": 541.28,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "xlm",
   "art": "krypto",
   "name": "Stellar",
   "kuerzel": "XLM",
   "kurs": 0.136856,
   "marktkapitalisierung": 4725440672,
   "umlaufmenge": 34530901002,
   "hoechstmenge": null,
   "allzeithoch": 0.729104,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "bch",
   "art": "krypto",
   "name": "Bitcoin Cash",
   "kuerzel": "BCH",
   "kurs": 177.02,
   "marktkapitalisierung": 3553459196,
   "umlaufmenge": 20076359,
   "hoechstmenge": 21000000,
   "allzeithoch": 3187.12,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "xmr",
   "art": "krypto",
   "name": "Monero",
   "kuerzel": "XMR",
   "kurs": 359.11,
   "marktkapitalisierung": 6748386140,
   "umlaufmenge": 18792300,
   "hoechstmenge": null,
   "allzeithoch": 685.48,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "uni",
   "art": "krypto",
   "name": "Uniswap",
   "kuerzel": "UNI",
   "kurs": 2.8,
   "marktkapitalisierung": 1748731350,
   "umlaufmenge": 623982424,
   "hoechstmenge": 1000000000,
   "allzeithoch": 37.37,
   "sektor": "Krypto",
   "land": null
  }
 ]
};
