/* Erzeugt von pflege/baue-werte.js - NICHT von Hand aendern. */
/* Stand 2026-08-22. Zum Aktualisieren die Zahlen im Pflegeskript ersetzen. */
const WERTE = {
 "stand": "2026-08-22",
 "eurUsd": 1.1699,
 "hinweis": "Startkurse und Kennzahlen sind echte Marktdaten vom angegebenen Stand. Der Kursverlauf im Spiel ist simuliert und hat keinen Bezug zur Wirklichkeit.",
 "quellen": [
  "stockanalysis.com (Kurse, KGV, Dividendenrendite, ETF-Kennzahlen)",
  "CoinGecko (Kryptokurse)",
  "frankfurter.dev / EZB (Wechselkurse)"
 ],
 "werte": [
  {
   "id": "sap",
   "art": "aktie",
   "name": "SAP",
   "kuerzel": "SAP",
   "kurs": 188.12,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 28.17,
   "gewinnJeAktie": 6.678,
   "dividende": 2.5772,
   "divRendite": 1.37,
   "sektor": "Technologie",
   "land": "Deutschland"
  },
  {
   "id": "sie",
   "art": "aktie",
   "name": "Siemens",
   "kuerzel": "SIE",
   "kurs": 280.35,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 28.03,
   "gewinnJeAktie": 10.0018,
   "dividende": 5.4108,
   "divRendite": 1.93,
   "sektor": "Industrie",
   "land": "Deutschland"
  },
  {
   "id": "alv",
   "art": "aktie",
   "name": "Allianz",
   "kuerzel": "ALV",
   "kurs": 440.8,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 14.46,
   "gewinnJeAktie": 30.4841,
   "dividende": 17.059,
   "divRendite": 3.87,
   "sektor": "Versicherung",
   "land": "Deutschland"
  },
  {
   "id": "rhm",
   "art": "aktie",
   "name": "Rheinmetall",
   "kuerzel": "RHM",
   "kurs": 1155.4,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 44.28,
   "gewinnJeAktie": 26.093,
   "dividende": 11.3229,
   "divRendite": 0.98,
   "sektor": "Ruestung",
   "land": "Deutschland"
  },
  {
   "id": "mbg",
   "art": "aktie",
   "name": "Mercedes-Benz Group",
   "kuerzel": "MBG",
   "kurs": 45.215,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 8.56,
   "gewinnJeAktie": 5.2821,
   "dividende": 3.5132,
   "divRendite": 7.77,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "bmw",
   "art": "aktie",
   "name": "BMW",
   "kuerzel": "BMW",
   "kurs": 58.88,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 5.59,
   "gewinnJeAktie": 10.5331,
   "dividende": 4.3748,
   "divRendite": 7.43,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "vow3",
   "art": "aktie",
   "name": "Volkswagen Vorzuege",
   "kuerzel": "VOW3",
   "kurs": 75.02,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 7.17,
   "gewinnJeAktie": 10.463,
   "dividende": 5.2739,
   "divRendite": 7.03,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "dbk",
   "art": "aktie",
   "name": "Deutsche Bank",
   "kuerzel": "DBK",
   "kurs": 32.375,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 10.45,
   "gewinnJeAktie": 3.0981,
   "dividende": 0.993912,
   "divRendite": 3.07,
   "sektor": "Banken",
   "land": "Deutschland"
  },
  {
   "id": "cbk",
   "art": "aktie",
   "name": "Commerzbank",
   "kuerzel": "CBK",
   "kurs": 39.01,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 14.98,
   "gewinnJeAktie": 2.6041,
   "dividende": 1.1001,
   "divRendite": 2.82,
   "sektor": "Banken",
   "land": "Deutschland"
  },
  {
   "id": "ads",
   "art": "aktie",
   "name": "adidas",
   "kuerzel": "ADS",
   "kurs": 154.45,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 19.84,
   "gewinnJeAktie": 7.7848,
   "dividende": 2.7955,
   "divRendite": 1.81,
   "sektor": "Konsum",
   "land": "Deutschland"
  },
  {
   "id": "zal",
   "art": "aktie",
   "name": "Zalando",
   "kuerzel": "ZAL",
   "kurs": 22.78,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 61.78,
   "gewinnJeAktie": 0.368728,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Handel",
   "land": "Deutschland"
  },
  {
   "id": "ifx",
   "art": "aktie",
   "name": "Infineon",
   "kuerzel": "IFX",
   "kurs": 55.97,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 60.81,
   "gewinnJeAktie": 0.920408,
   "dividende": 0.352611,
   "divRendite": 0.63,
   "sektor": "Halbleiter",
   "land": "Deutschland"
  },
  {
   "id": "bas",
   "art": "aktie",
   "name": "BASF",
   "kuerzel": "BAS",
   "kurs": 51.67,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 21.83,
   "gewinnJeAktie": 2.3669,
   "dividende": 2.2786,
   "divRendite": 4.41,
   "sektor": "Chemie",
   "land": "Deutschland"
  },
  {
   "id": "bayn",
   "art": "aktie",
   "name": "Bayer",
   "kuerzel": "BAYN",
   "kurs": 48.04,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0.105688,
   "divRendite": 0.22,
   "sektor": "Pharma",
   "land": "Deutschland"
  },
  {
   "id": "mrk1",
   "art": "aktie",
   "name": "Merck",
   "kuerzel": "MRK1",
   "kurs": 137.95,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 25.31,
   "gewinnJeAktie": 5.4504,
   "dividende": 2.1934,
   "divRendite": 1.59,
   "sektor": "Pharma",
   "land": "Deutschland"
  },
  {
   "id": "dte",
   "art": "aktie",
   "name": "Deutsche Telekom",
   "kuerzel": "DTE",
   "kurs": 28.94,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 16.2,
   "gewinnJeAktie": 1.7864,
   "dividende": 0.992642,
   "divRendite": 3.43,
   "sektor": "Telekom",
   "land": "Deutschland"
  },
  {
   "id": "dhl",
   "art": "aktie",
   "name": "DHL Group",
   "kuerzel": "DHL",
   "kurs": 55.98,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 17.05,
   "gewinnJeAktie": 3.2833,
   "dividende": 1.9257,
   "divRendite": 3.44,
   "sektor": "Logistik",
   "land": "Deutschland"
  },
  {
   "id": "eoan",
   "art": "aktie",
   "name": "E.ON",
   "kuerzel": "EOAN",
   "kurs": 17.41,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 13.49,
   "gewinnJeAktie": 1.2906,
   "dividende": 0.565825,
   "divRendite": 3.25,
   "sektor": "Versorger",
   "land": "Deutschland"
  },
  {
   "id": "rwe",
   "art": "aktie",
   "name": "RWE",
   "kuerzel": "RWE",
   "kurs": 57.32,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 12.69,
   "gewinnJeAktie": 4.5169,
   "dividende": 1.2037,
   "divRendite": 2.1,
   "sektor": "Versorger",
   "land": "Deutschland"
  },
  {
   "id": "enr",
   "art": "aktie",
   "name": "Siemens Energy",
   "kuerzel": "ENR",
   "kurs": 153.36,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 49.88,
   "gewinnJeAktie": 3.0746,
   "dividende": 0.69012,
   "divRendite": 0.45,
   "sektor": "Versorger",
   "land": "Deutschland"
  },
  {
   "id": "muv2",
   "art": "aktie",
   "name": "Muenchener Rueck",
   "kuerzel": "MUV2",
   "kurs": 516.4,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 9.61,
   "gewinnJeAktie": 53.7357,
   "dividende": 23.6511,
   "divRendite": 4.58,
   "sektor": "Versicherung",
   "land": "Deutschland"
  },
  {
   "id": "hnr1",
   "art": "aktie",
   "name": "Hannover Rueck",
   "kuerzel": "HNR1",
   "kurs": 250.8,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 11.07,
   "gewinnJeAktie": 22.6558,
   "dividende": 12.239,
   "divRendite": 4.88,
   "sektor": "Versicherung",
   "land": "Deutschland"
  },
  {
   "id": "db1",
   "art": "aktie",
   "name": "Deutsche Boerse",
   "kuerzel": "DB1",
   "kurs": 282.9,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 24.4,
   "gewinnJeAktie": 11.5943,
   "dividende": 4.2718,
   "divRendite": 1.51,
   "sektor": "Finanzen",
   "land": "Deutschland"
  },
  {
   "id": "bei",
   "art": "aktie",
   "name": "Beiersdorf",
   "kuerzel": "BEI",
   "kurs": 79.78,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 18.56,
   "gewinnJeAktie": 4.2985,
   "dividende": 1.0212,
   "divRendite": 1.28,
   "sektor": "Konsum",
   "land": "Deutschland"
  },
  {
   "id": "hen3",
   "art": "aktie",
   "name": "Henkel Vorzuege",
   "kuerzel": "HEN3",
   "kurs": 75.84,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 16.17,
   "gewinnJeAktie": 4.6902,
   "dividende": 2.078,
   "divRendite": 2.74,
   "sektor": "Konsum",
   "land": "Deutschland"
  },
  {
   "id": "con",
   "art": "aktie",
   "name": "Continental",
   "kuerzel": "CON",
   "kurs": 68.78,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 2.7374,
   "divRendite": 3.98,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "dtg",
   "art": "aktie",
   "name": "Daimler Truck",
   "kuerzel": "DTG",
   "kurs": 45.43,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 32.22,
   "gewinnJeAktie": 1.41,
   "dividende": 1.9081,
   "divRendite": 4.2,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "mtx",
   "art": "aktie",
   "name": "MTU Aero Engines",
   "kuerzel": "MTX",
   "kurs": 352.4,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 20.41,
   "gewinnJeAktie": 17.266,
   "dividende": 3.524,
   "divRendite": 1,
   "sektor": "Luftfahrt",
   "land": "Deutschland"
  },
  {
   "id": "hei",
   "art": "aktie",
   "name": "Heidelberg Materials",
   "kuerzel": "HEI",
   "kurs": 159.6,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 13.86,
   "gewinnJeAktie": 11.5152,
   "dividende": 3.6389,
   "divRendite": 2.28,
   "sektor": "Bau",
   "land": "Deutschland"
  },
  {
   "id": "vna",
   "art": "aktie",
   "name": "Vonovia",
   "kuerzel": "VNA",
   "kurs": 20.06,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 4.7,
   "gewinnJeAktie": 4.2681,
   "dividende": 1.2578,
   "divRendite": 6.27,
   "sektor": "Immobilien",
   "land": "Deutschland"
  },
  {
   "id": "asml",
   "art": "aktie",
   "name": "ASML",
   "kuerzel": "ASML",
   "kurs": 1506,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 54.69,
   "gewinnJeAktie": 27.537,
   "dividende": 7.53,
   "divRendite": 0.5,
   "sektor": "Halbleiter",
   "land": "Niederlande"
  },
  {
   "id": "mc",
   "art": "aktie",
   "name": "LVMH",
   "kuerzel": "MC",
   "kurs": 452.5,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 20.63,
   "gewinnJeAktie": 21.9341,
   "dividende": 13.1225,
   "divRendite": 2.9,
   "sektor": "Luxus",
   "land": "Frankreich"
  },
  {
   "id": "rms",
   "art": "aktie",
   "name": "Hermes",
   "kuerzel": "RMS",
   "kurs": 1573,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 36.58,
   "gewinnJeAktie": 43.0016,
   "dividende": 17.9322,
   "divRendite": 1.14,
   "sektor": "Luxus",
   "land": "Frankreich"
  },
  {
   "id": "or",
   "art": "aktie",
   "name": "LOreal",
   "kuerzel": "OR",
   "kurs": 386.6,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 32.82,
   "gewinnJeAktie": 11.7794,
   "dividende": 7.2681,
   "divRendite": 1.88,
   "sektor": "Konsum",
   "land": "Frankreich"
  },
  {
   "id": "tte",
   "art": "aktie",
   "name": "TotalEnergies",
   "kuerzel": "TTE",
   "kurs": 77.44,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 11.03,
   "gewinnJeAktie": 7.0209,
   "dividende": 3.601,
   "divRendite": 4.65,
   "sektor": "Energie",
   "land": "Frankreich"
  },
  {
   "id": "san",
   "art": "aktie",
   "name": "Sanofi",
   "kuerzel": "SAN",
   "kurs": 78.94,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 24.3,
   "gewinnJeAktie": 3.2486,
   "dividende": 4.1365,
   "divRendite": 5.24,
   "sektor": "Pharma",
   "land": "Frankreich"
  },
  {
   "id": "ai",
   "art": "aktie",
   "name": "Air Liquide",
   "kuerzel": "AI",
   "kurs": 167.12,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 30.07,
   "gewinnJeAktie": 5.5577,
   "dividende": 3.3758,
   "divRendite": 2.02,
   "sektor": "Chemie",
   "land": "Frankreich"
  },
  {
   "id": "su",
   "art": "aktie",
   "name": "Schneider Electric",
   "kuerzel": "SU",
   "kurs": 296.8,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 35.7,
   "gewinnJeAktie": 8.3137,
   "dividende": 4.2146,
   "divRendite": 1.42,
   "sektor": "Industrie",
   "land": "Frankreich"
  },
  {
   "id": "saf",
   "art": "aktie",
   "name": "SAFRAN",
   "kuerzel": "SAF",
   "kurs": 343.6,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 36.9,
   "gewinnJeAktie": 9.3117,
   "dividende": 3.2986,
   "divRendite": 0.96,
   "sektor": "Luftfahrt",
   "land": "Frankreich"
  },
  {
   "id": "cs",
   "art": "aktie",
   "name": "AXA",
   "kuerzel": "CS",
   "kurs": 43.72,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 11.8,
   "gewinnJeAktie": 3.7051,
   "dividende": 2.3084,
   "divRendite": 5.28,
   "sektor": "Versicherung",
   "land": "Frankreich"
  },
  {
   "id": "bnp",
   "art": "aktie",
   "name": "BNP Paribas",
   "kuerzel": "BNP",
   "kurs": 107.5,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 9.31,
   "gewinnJeAktie": 11.5467,
   "dividende": 5.1492,
   "divRendite": 4.79,
   "sektor": "Banken",
   "land": "Frankreich"
  },
  {
   "id": "dg",
   "art": "aktie",
   "name": "VINCI",
   "kuerzel": "DG",
   "kurs": 119.3,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 13.23,
   "gewinnJeAktie": 9.0174,
   "dividende": 4.951,
   "divRendite": 4.15,
   "sektor": "Bau",
   "land": "Frankreich"
  },
  {
   "id": "bn",
   "art": "aktie",
   "name": "Danone",
   "kuerzel": "BN",
   "kurs": 66.32,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 21.97,
   "gewinnJeAktie": 3.0187,
   "dividende": 2.2814,
   "divRendite": 3.44,
   "sektor": "Nahrung",
   "land": "Frankreich"
  },
  {
   "id": "el",
   "art": "aktie",
   "name": "EssilorLuxottica",
   "kuerzel": "EL",
   "kurs": 163.2,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 30.5,
   "gewinnJeAktie": 5.3508,
   "dividende": 3.9984,
   "divRendite": 2.45,
   "sektor": "Konsum",
   "land": "Frankreich"
  },
  {
   "id": "air",
   "art": "aktie",
   "name": "Airbus",
   "kuerzel": "AIR",
   "kurs": 203.7,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 27.13,
   "gewinnJeAktie": 7.5083,
   "dividende": 3.137,
   "divRendite": 1.54,
   "sektor": "Luftfahrt",
   "land": "Niederlande"
  },
  {
   "id": "race",
   "art": "aktie",
   "name": "Ferrari",
   "kuerzel": "RACE",
   "kurs": 371.1,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 40.22,
   "gewinnJeAktie": 9.2268,
   "dividende": 3.711,
   "divRendite": 1,
   "sektor": "Automobil",
   "land": "Italien"
  },
  {
   "id": "adyen",
   "art": "aktie",
   "name": "Adyen",
   "kuerzel": "ADYEN",
   "kurs": 1074,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 30.2,
   "gewinnJeAktie": 35.5629,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Finanzen",
   "land": "Niederlande"
  },
  {
   "id": "inga",
   "art": "aktie",
   "name": "ING Group",
   "kuerzel": "INGA",
   "kurs": 29.83,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 9.99,
   "gewinnJeAktie": 2.986,
   "dividende": 1.3125,
   "divRendite": 4.4,
   "sektor": "Banken",
   "land": "Niederlande"
  },
  {
   "id": "abi",
   "art": "aktie",
   "name": "AB InBev",
   "kuerzel": "ABI",
   "kurs": 67.16,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 16.54,
   "gewinnJeAktie": 4.0605,
   "dividende": 1.1619,
   "divRendite": 1.73,
   "sektor": "Nahrung",
   "land": "Belgien"
  },
  {
   "id": "itx",
   "art": "aktie",
   "name": "Inditex",
   "kuerzel": "ITX",
   "kurs": 58.22,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 28.86,
   "gewinnJeAktie": 2.0173,
   "dividende": 1.7466,
   "divRendite": 3,
   "sektor": "Handel",
   "land": "Spanien"
  },
  {
   "id": "san2",
   "art": "aktie",
   "name": "Banco Santander",
   "kuerzel": "SAN2",
   "kurs": 12.55,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 14.22,
   "gewinnJeAktie": 0.88256,
   "dividende": 0.252255,
   "divRendite": 2.01,
   "sektor": "Banken",
   "land": "Spanien"
  },
  {
   "id": "ibe",
   "art": "aktie",
   "name": "Iberdrola",
   "kuerzel": "IBE",
   "kurs": 20.05,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 24.57,
   "gewinnJeAktie": 0.816036,
   "dividende": 0.675685,
   "divRendite": 3.37,
   "sektor": "Versorger",
   "land": "Spanien"
  },
  {
   "id": "enel",
   "art": "aktie",
   "name": "Enel",
   "kuerzel": "ENEL",
   "kurs": 9.503,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 22.78,
   "gewinnJeAktie": 0.417164,
   "dividende": 0.491305,
   "divRendite": 5.17,
   "sektor": "Versorger",
   "land": "Italien"
  },
  {
   "id": "eni",
   "art": "aktie",
   "name": "Eni",
   "kuerzel": "ENI",
   "kurs": 24.14,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 12.67,
   "gewinnJeAktie": 1.9053,
   "dividende": 1.0791,
   "divRendite": 4.47,
   "sektor": "Energie",
   "land": "Italien"
  },
  {
   "id": "ucg",
   "art": "aktie",
   "name": "UniCredit",
   "kuerzel": "UCG",
   "kurs": 83.03,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 11.79,
   "gewinnJeAktie": 7.0424,
   "dividende": 3.1717,
   "divRendite": 3.82,
   "sektor": "Banken",
   "land": "Italien"
  },
  {
   "id": "isp",
   "art": "aktie",
   "name": "Intesa Sanpaolo",
   "kuerzel": "ISP",
   "kurs": 6.769,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 12.2,
   "gewinnJeAktie": 0.554836,
   "dividende": 0.379064,
   "divRendite": 5.6,
   "sektor": "Banken",
   "land": "Italien"
  },
  {
   "id": "nvda",
   "art": "aktie",
   "name": "NVIDIA",
   "kuerzel": "NVDA",
   "kurs": 183.54,
   "kursOriginal": 214.72,
   "waehrungOriginal": "USD",
   "kgv": 32.88,
   "gewinnJeAktie": 5.5821,
   "dividende": 0.862638,
   "divRendite": 0.47,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "aapl",
   "art": "aktie",
   "name": "Apple",
   "kuerzel": "AAPL",
   "kurs": 264.42,
   "kursOriginal": 309.35,
   "waehrungOriginal": "USD",
   "kgv": 35.49,
   "gewinnJeAktie": 7.4505,
   "dividende": 0.92547,
   "divRendite": 0.35,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "googl",
   "art": "aktie",
   "name": "Alphabet",
   "kuerzel": "GOOGL",
   "kurs": 294.74,
   "kursOriginal": 344.82,
   "waehrungOriginal": "USD",
   "kgv": 17.3,
   "gewinnJeAktie": 17.037,
   "dividende": 0.766324,
   "divRendite": 0.26,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "msft",
   "art": "aktie",
   "name": "Microsoft",
   "kuerzel": "MSFT",
   "kurs": 413.06,
   "kursOriginal": 483.24,
   "waehrungOriginal": "USD",
   "kgv": 26.92,
   "gewinnJeAktie": 15.344,
   "dividende": 3.098,
   "divRendite": 0.75,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "amzn",
   "art": "aktie",
   "name": "Amazon",
   "kuerzel": "AMZN",
   "kurs": 221.07,
   "kursOriginal": 258.63,
   "waehrungOriginal": "USD",
   "kgv": 20.8,
   "gewinnJeAktie": 10.6284,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Handel",
   "land": "USA"
  },
  {
   "id": "avgo",
   "art": "aktie",
   "name": "Broadcom",
   "kuerzel": "AVGO",
   "kurs": 314.94,
   "kursOriginal": 368.45,
   "waehrungOriginal": "USD",
   "kgv": 61.32,
   "gewinnJeAktie": 5.136,
   "dividende": 2.2361,
   "divRendite": 0.71,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "meta",
   "art": "aktie",
   "name": "Meta Platforms",
   "kuerzel": "META",
   "kurs": 470.04,
   "kursOriginal": 549.9,
   "waehrungOriginal": "USD",
   "kgv": 20.72,
   "gewinnJeAktie": 22.6853,
   "dividende": 1.7862,
   "divRendite": 0.38,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "tsla",
   "art": "aktie",
   "name": "Tesla",
   "kuerzel": "TSLA",
   "kurs": 310.16,
   "kursOriginal": 362.86,
   "waehrungOriginal": "USD",
   "kgv": 376.55,
   "gewinnJeAktie": 0.823689,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Automobil",
   "land": "USA"
  },
  {
   "id": "brkb",
   "art": "aktie",
   "name": "Berkshire Hathaway",
   "kuerzel": "BRK.B",
   "kurs": 423.81,
   "kursOriginal": 495.82,
   "waehrungOriginal": "USD",
   "kgv": 12.37,
   "gewinnJeAktie": 34.2611,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Finanzen",
   "land": "USA"
  },
  {
   "id": "mu",
   "art": "aktie",
   "name": "Micron Technology",
   "kuerzel": "MU",
   "kurs": 826.38,
   "kursOriginal": 966.78,
   "waehrungOriginal": "USD",
   "kgv": 21.82,
   "gewinnJeAktie": 37.8726,
   "dividende": 0.495828,
   "divRendite": 0.06,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "jpm",
   "art": "aktie",
   "name": "JPMorgan Chase",
   "kuerzel": "JPM",
   "kurs": 300.52,
   "kursOriginal": 351.58,
   "waehrungOriginal": "USD",
   "kgv": 15.09,
   "gewinnJeAktie": 19.9152,
   "dividende": 5.1389,
   "divRendite": 1.71,
   "sektor": "Banken",
   "land": "USA"
  },
  {
   "id": "wmt",
   "art": "aktie",
   "name": "Walmart",
   "kuerzel": "WMT",
   "kurs": 88.6401,
   "kursOriginal": 103.7,
   "waehrungOriginal": "USD",
   "kgv": 37.58,
   "gewinnJeAktie": 2.3587,
   "dividende": 0.842081,
   "divRendite": 0.95,
   "sektor": "Handel",
   "land": "USA"
  },
  {
   "id": "amd",
   "art": "aktie",
   "name": "AMD",
   "kuerzel": "AMD",
   "kurs": 404.52,
   "kursOriginal": 473.25,
   "waehrungOriginal": "USD",
   "kgv": 120.79,
   "gewinnJeAktie": 3.349,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "v",
   "art": "aktie",
   "name": "Visa",
   "kuerzel": "V",
   "kurs": 317.16,
   "kursOriginal": 371.04,
   "waehrungOriginal": "USD",
   "kgv": 31.59,
   "gewinnJeAktie": 10.0399,
   "dividende": 2.2836,
   "divRendite": 0.72,
   "sektor": "Finanzen",
   "land": "USA"
  },
  {
   "id": "jnj",
   "art": "aktie",
   "name": "Johnson & Johnson",
   "kuerzel": "JNJ",
   "kurs": 230.99,
   "kursOriginal": 270.24,
   "waehrungOriginal": "USD",
   "kgv": 31.33,
   "gewinnJeAktie": 7.3728,
   "dividende": 4.5736,
   "divRendite": 1.98,
   "sektor": "Pharma",
   "land": "USA"
  },
  {
   "id": "csco",
   "art": "aktie",
   "name": "Cisco",
   "kuerzel": "CSCO",
   "kurs": 94.9141,
   "kursOriginal": 111.04,
   "waehrungOriginal": "USD",
   "kgv": 33.35,
   "gewinnJeAktie": 2.846,
   "dividende": 1.4332,
   "divRendite": 1.51,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "cost",
   "art": "aktie",
   "name": "Costco",
   "kuerzel": "COST",
   "kurs": 810.1,
   "kursOriginal": 947.74,
   "waehrungOriginal": "USD",
   "kgv": 47.67,
   "gewinnJeAktie": 16.9939,
   "dividende": 5.0226,
   "divRendite": 0.62,
   "sektor": "Handel",
   "land": "USA"
  },
  {
   "id": "amat",
   "art": "aktie",
   "name": "Applied Materials",
   "kuerzel": "AMAT",
   "kurs": 420.82,
   "kursOriginal": 492.32,
   "waehrungOriginal": "USD",
   "kgv": 42.47,
   "gewinnJeAktie": 9.9086,
   "dividende": 1.8095,
   "divRendite": 0.43,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "cat",
   "art": "aktie",
   "name": "Caterpillar",
   "kuerzel": "CAT",
   "kurs": 707.67,
   "kursOriginal": 827.9,
   "waehrungOriginal": "USD",
   "kgv": 35.68,
   "gewinnJeAktie": 19.8338,
   "dividende": 5.5906,
   "divRendite": 0.79,
   "sektor": "Industrie",
   "land": "USA"
  },
  {
   "id": "lrcx",
   "art": "aktie",
   "name": "Lam Research",
   "kuerzel": "LRCX",
   "kurs": 268.4,
   "kursOriginal": 314,
   "waehrungOriginal": "USD",
   "kgv": 54.51,
   "gewinnJeAktie": 4.9239,
   "dividende": 0.88572,
   "divRendite": 0.33,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "pltr",
   "art": "aktie",
   "name": "Palantir",
   "kuerzel": "PLTR",
   "kurs": 153.81,
   "kursOriginal": 179.94,
   "waehrungOriginal": "USD",
   "kgv": 153.9,
   "gewinnJeAktie": 0.999415,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "ko",
   "art": "aktie",
   "name": "Coca-Cola",
   "kuerzel": "KO",
   "kurs": 77.8699,
   "kursOriginal": 91.1,
   "waehrungOriginal": "USD",
   "kgv": 27.38,
   "gewinnJeAktie": 2.844,
   "dividende": 1.8144,
   "divRendite": 2.33,
   "sektor": "Nahrung",
   "land": "USA"
  },
  {
   "id": "cvx",
   "art": "aktie",
   "name": "Chevron",
   "kuerzel": "CVX",
   "kurs": 175.46,
   "kursOriginal": 205.27,
   "waehrungOriginal": "USD",
   "kgv": 19.71,
   "gewinnJeAktie": 8.9021,
   "dividende": 6.0885,
   "divRendite": 3.47,
   "sektor": "Energie",
   "land": "USA"
  },
  {
   "id": "unh",
   "art": "aktie",
   "name": "UnitedHealth",
   "kuerzel": "UNH",
   "kurs": 333.46,
   "kursOriginal": 390.11,
   "waehrungOriginal": "USD",
   "kgv": 25.11,
   "gewinnJeAktie": 13.28,
   "dividende": 7.9363,
   "divRendite": 2.38,
   "sektor": "Gesundheit",
   "land": "USA"
  },
  {
   "id": "hd",
   "art": "aktie",
   "name": "Home Depot",
   "kuerzel": "HD",
   "kurs": 286.87,
   "kursOriginal": 335.61,
   "waehrungOriginal": "USD",
   "kgv": 23.48,
   "gewinnJeAktie": 12.2176,
   "dividende": 7.975,
   "divRendite": 2.78,
   "sektor": "Handel",
   "land": "USA"
  },
  {
   "id": "pg",
   "art": "aktie",
   "name": "Procter & Gamble",
   "kuerzel": "PG",
   "kurs": 123.67,
   "kursOriginal": 144.68,
   "waehrungOriginal": "USD",
   "kgv": 21.84,
   "gewinnJeAktie": 5.6625,
   "dividende": 3.7225,
   "divRendite": 3.01,
   "sektor": "Konsum",
   "land": "USA"
  },
  {
   "id": "mrk",
   "art": "aktie",
   "name": "Merck & Co",
   "kuerzel": "MRK",
   "kurs": 130.4,
   "kursOriginal": 152.55,
   "waehrungOriginal": "USD",
   "kgv": 119.85,
   "gewinnJeAktie": 1.088,
   "dividende": 2.9079,
   "divRendite": 2.23,
   "sektor": "Pharma",
   "land": "USA"
  },
  {
   "id": "gs",
   "art": "aktie",
   "name": "Goldman Sachs",
   "kuerzel": "GS",
   "kurs": 888.35,
   "kursOriginal": 1039.28,
   "waehrungOriginal": "USD",
   "kgv": 16.08,
   "gewinnJeAktie": 55.2456,
   "dividende": 17.0563,
   "divRendite": 1.92,
   "sektor": "Banken",
   "land": "USA"
  },
  {
   "id": "nflx",
   "art": "aktie",
   "name": "Netflix",
   "kuerzel": "NFLX",
   "kurs": 68.0315,
   "kursOriginal": 79.59,
   "waehrungOriginal": "USD",
   "kgv": 25.07,
   "gewinnJeAktie": 2.7137,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Medien",
   "land": "USA"
  },
  {
   "id": "txn",
   "art": "aktie",
   "name": "Texas Instruments",
   "kuerzel": "TXN",
   "kurs": 225.97,
   "kursOriginal": 264.36,
   "waehrungOriginal": "USD",
   "kgv": 40.16,
   "gewinnJeAktie": 5.6267,
   "dividende": 4.8584,
   "divRendite": 2.15,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "klac",
   "art": "aktie",
   "name": "KLA",
   "kuerzel": "KLAC",
   "kurs": 157.27,
   "kursOriginal": 183.99,
   "waehrungOriginal": "USD",
   "kgv": 50.27,
   "gewinnJeAktie": 3.1285,
   "dividende": 0.78635,
   "divRendite": 0.5,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "axp",
   "art": "aktie",
   "name": "American Express",
   "kuerzel": "AXP",
   "kurs": 287.2,
   "kursOriginal": 336,
   "waehrungOriginal": "USD",
   "kgv": 20.4,
   "gewinnJeAktie": 14.0784,
   "dividende": 3.2454,
   "divRendite": 1.13,
   "sektor": "Finanzen",
   "land": "USA"
  },
  {
   "id": "panw",
   "art": "aktie",
   "name": "Palo Alto Networks",
   "kuerzel": "PANW",
   "kurs": 305.9,
   "kursOriginal": 357.87,
   "waehrungOriginal": "USD",
   "kgv": 346.02,
   "gewinnJeAktie": 0.884053,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "intc",
   "art": "aktie",
   "name": "Intel",
   "kuerzel": "INTC",
   "kurs": 76.9895,
   "kursOriginal": 90.07,
   "waehrungOriginal": "USD",
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "ma",
   "art": "aktie",
   "name": "Mastercard",
   "kuerzel": "MA",
   "kurs": 496.31,
   "kursOriginal": 580.63,
   "waehrungOriginal": "USD",
   "kgv": 31.93,
   "gewinnJeAktie": 15.5437,
   "dividende": 2.9779,
   "divRendite": 0.6,
   "sektor": "Finanzen",
   "land": "USA"
  },
  {
   "id": "lly",
   "art": "aktie",
   "name": "Eli Lilly",
   "kuerzel": "LLY",
   "kurs": 1073.08,
   "kursOriginal": 1255.4,
   "waehrungOriginal": "USD",
   "kgv": 42.14,
   "gewinnJeAktie": 25.4646,
   "dividende": 5.9019,
   "divRendite": 0.55,
   "sektor": "Pharma",
   "land": "USA"
  },
  {
   "id": "xom",
   "art": "aktie",
   "name": "ExxonMobil",
   "kuerzel": "XOM",
   "kurs": 141.13,
   "kursOriginal": 165.11,
   "waehrungOriginal": "USD",
   "kgv": 21.29,
   "gewinnJeAktie": 6.6289,
   "dividende": 3.5283,
   "divRendite": 2.5,
   "sektor": "Energie",
   "land": "USA"
  },
  {
   "id": "orcl",
   "art": "aktie",
   "name": "Oracle",
   "kuerzel": "ORCL",
   "kurs": 125.2,
   "kursOriginal": 146.47,
   "waehrungOriginal": "USD",
   "kgv": 25.12,
   "gewinnJeAktie": 4.9841,
   "dividende": 1.7152,
   "divRendite": 1.37,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "ge",
   "art": "aktie",
   "name": "GE Aerospace",
   "kuerzel": "GE",
   "kurs": 297.78,
   "kursOriginal": 348.37,
   "waehrungOriginal": "USD",
   "kgv": 41.06,
   "gewinnJeAktie": 7.2523,
   "dividende": 1.608,
   "divRendite": 0.54,
   "sektor": "Luftfahrt",
   "land": "USA"
  },
  {
   "id": "bac",
   "art": "aktie",
   "name": "Bank of America",
   "kuerzel": "BAC",
   "kurs": 52.731,
   "kursOriginal": 61.69,
   "waehrungOriginal": "USD",
   "kgv": 14.25,
   "gewinnJeAktie": 3.7004,
   "dividende": 1.0968,
   "divRendite": 2.08,
   "sektor": "Banken",
   "land": "USA"
  },
  {
   "id": "tsm",
   "art": "aktie",
   "name": "TSMC",
   "kuerzel": "TSM",
   "kurs": 358.11,
   "kursOriginal": 418.95,
   "waehrungOriginal": "USD",
   "kgv": 28.17,
   "gewinnJeAktie": 12.7125,
   "dividende": 2.7574,
   "divRendite": 0.77,
   "sektor": "Halbleiter",
   "land": "Taiwan"
  },
  {
   "id": "skhy",
   "art": "aktie",
   "name": "SK hynix",
   "kuerzel": "SKHY",
   "kurs": 1068.29,
   "kursOriginal": 1730000,
   "waehrungOriginal": "KRW",
   "kgv": 7.6,
   "gewinnJeAktie": 140.56,
   "dividende": 1.8161,
   "divRendite": 0.17,
   "sektor": "Halbleiter",
   "land": "Suedkorea"
  },
  {
   "id": "baba",
   "art": "aktie",
   "name": "Alibaba",
   "kuerzel": "BABA",
   "kurs": 102.01,
   "kursOriginal": 119.34,
   "waehrungOriginal": "USD",
   "kgv": 27.24,
   "gewinnJeAktie": 3.7449,
   "dividende": 0.897688,
   "divRendite": 0.88,
   "sektor": "Handel",
   "land": "China"
  },
  {
   "id": "mufg",
   "art": "aktie",
   "name": "Mitsubishi UFJ",
   "kuerzel": "MUFG",
   "kurs": 18.8392,
   "kursOriginal": 22.04,
   "waehrungOriginal": "USD",
   "kgv": 20.26,
   "gewinnJeAktie": 0.929872,
   "dividende": 0.378668,
   "divRendite": 2.01,
   "sektor": "Banken",
   "land": "Japan"
  },
  {
   "id": "arm",
   "art": "aktie",
   "name": "Arm Holdings",
   "kuerzel": "ARM",
   "kurs": 207.98,
   "kursOriginal": 243.32,
   "waehrungOriginal": "USD",
   "kgv": 248.36,
   "gewinnJeAktie": 0.837413,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Halbleiter",
   "land": "Grossbritannien"
  },
  {
   "id": "shel",
   "art": "aktie",
   "name": "Shell",
   "kuerzel": "SHEL",
   "kurs": 79.776,
   "kursOriginal": 93.33,
   "waehrungOriginal": "USD",
   "kgv": 9.92,
   "gewinnJeAktie": 8.0419,
   "dividende": 2.5847,
   "divRendite": 3.24,
   "sektor": "Energie",
   "land": "Grossbritannien"
  },
  {
   "id": "azn",
   "art": "aktie",
   "name": "AstraZeneca",
   "kuerzel": "AZN",
   "kurs": 141.88,
   "kursOriginal": 165.98,
   "waehrungOriginal": "USD",
   "kgv": 24.77,
   "gewinnJeAktie": 5.7279,
   "dividende": 2.7667,
   "divRendite": 1.95,
   "sektor": "Pharma",
   "land": "Grossbritannien"
  },
  {
   "id": "hsbc",
   "art": "aktie",
   "name": "HSBC",
   "kuerzel": "HSBC",
   "kurs": 89.0247,
   "kursOriginal": 104.15,
   "waehrungOriginal": "USD",
   "kgv": 16.81,
   "gewinnJeAktie": 5.2959,
   "dividende": 3.1871,
   "divRendite": 3.58,
   "sektor": "Banken",
   "land": "Grossbritannien"
  },
  {
   "id": "nvs",
   "art": "aktie",
   "name": "Novartis",
   "kuerzel": "NVS",
   "kurs": 135.79,
   "kursOriginal": 158.86,
   "waehrungOriginal": "USD",
   "kgv": 23.69,
   "gewinnJeAktie": 5.732,
   "dividende": 2.6343,
   "divRendite": 1.94,
   "sektor": "Pharma",
   "land": "Schweiz"
  },
  {
   "id": "ry",
   "art": "aktie",
   "name": "Royal Bank of Canada",
   "kuerzel": "RY",
   "kurs": 175.43,
   "kursOriginal": 205.23,
   "waehrungOriginal": "USD",
   "kgv": 17.96,
   "gewinnJeAktie": 9.7678,
   "dividende": 4.0524,
   "divRendite": 2.31,
   "sektor": "Banken",
   "land": "Kanada"
  },
  {
   "id": "p911",
   "art": "aktie",
   "name": "Porsche AG",
   "kuerzel": "P911",
   "kurs": 45.01,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 48.64,
   "gewinnJeAktie": 0.92537,
   "dividende": 1.0172,
   "divRendite": 2.26,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "fre",
   "art": "aktie",
   "name": "Fresenius",
   "kuerzel": "FRE",
   "kurs": 46.6,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 16.79,
   "gewinnJeAktie": 2.7755,
   "dividende": 1.0532,
   "divRendite": 2.26,
   "sektor": "Gesundheit",
   "land": "Deutschland"
  },
  {
   "id": "fme",
   "art": "aktie",
   "name": "Fresenius Medical Care",
   "kuerzel": "FME",
   "kurs": 40.14,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 12,
   "gewinnJeAktie": 3.345,
   "dividende": 1.4691,
   "divRendite": 3.66,
   "sektor": "Gesundheit",
   "land": "Deutschland"
  },
  {
   "id": "sy1",
   "art": "aktie",
   "name": "Symrise",
   "kuerzel": "SY1",
   "kurs": 90,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 50.9,
   "gewinnJeAktie": 1.7682,
   "dividende": 1.287,
   "divRendite": 1.43,
   "sektor": "Chemie",
   "land": "Deutschland"
  },
  {
   "id": "srt3",
   "art": "aktie",
   "name": "Sartorius Vorzuege",
   "kuerzel": "SRT3",
   "kurs": 246.8,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 78.05,
   "gewinnJeAktie": 3.1621,
   "dividende": 0.78976,
   "divRendite": 0.32,
   "sektor": "Gesundheit",
   "land": "Deutschland"
  },
  {
   "id": "tlx",
   "art": "aktie",
   "name": "Talanx",
   "kuerzel": "TLX",
   "kurs": 120.8,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 11.98,
   "gewinnJeAktie": 10.0835,
   "dividende": 3.6965,
   "divRendite": 3.06,
   "sektor": "Versicherung",
   "land": "Deutschland"
  },
  {
   "id": "pub",
   "art": "aktie",
   "name": "Publicis Groupe",
   "kuerzel": "PUB",
   "kurs": 102.35,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 15.94,
   "gewinnJeAktie": 6.421,
   "dividende": 3.7665,
   "divRendite": 3.68,
   "sektor": "Medien",
   "land": "Frankreich"
  },
  {
   "id": "stla",
   "art": "aktie",
   "name": "Stellantis",
   "kuerzel": "STLA",
   "kurs": 4.649,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Automobil",
   "land": "Niederlande"
  },
  {
   "id": "prx",
   "art": "aktie",
   "name": "Prosus",
   "kuerzel": "PRX",
   "kurs": 38.295,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 8.44,
   "gewinnJeAktie": 4.5373,
   "dividende": 0.283383,
   "divRendite": 0.74,
   "sektor": "Technologie",
   "land": "Niederlande"
  },
  {
   "id": "g",
   "art": "aktie",
   "name": "Generali",
   "kuerzel": "G",
   "kurs": 42.99,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 14.58,
   "gewinnJeAktie": 2.9486,
   "dividende": 1.6465,
   "divRendite": 3.83,
   "sektor": "Versicherung",
   "land": "Italien"
  },
  {
   "id": "bbva",
   "art": "aktie",
   "name": "BBVA",
   "kuerzel": "BBVA",
   "kurs": 24.82,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 13.12,
   "gewinnJeAktie": 1.8918,
   "dividende": 0.920822,
   "divRendite": 3.71,
   "sektor": "Banken",
   "land": "Spanien"
  },
  {
   "id": "tef",
   "art": "aktie",
   "name": "Telefonica",
   "kuerzel": "TEF",
   "kurs": 3.622,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0.295193,
   "divRendite": 8.15,
   "sektor": "Telekom",
   "land": "Spanien"
  },
  {
   "id": "kbc",
   "art": "aktie",
   "name": "KBC Group",
   "kuerzel": "KBC",
   "kurs": 130.75,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 14.49,
   "gewinnJeAktie": 9.0235,
   "dividende": 5.0862,
   "divRendite": 3.89,
   "sektor": "Banken",
   "land": "Belgien"
  },
  {
   "id": "ulvr",
   "art": "aktie",
   "name": "Unilever",
   "kuerzel": "ULVR",
   "kurs": 54.6399,
   "kursOriginal": 4681,
   "waehrungOriginal": "GBX",
   "kgv": 21.33,
   "gewinnJeAktie": 2.5616,
   "dividende": 2.0271,
   "divRendite": 3.71,
   "sektor": "Konsum",
   "land": "Grossbritannien"
  },
  {
   "id": "bp1",
   "art": "aktie",
   "name": "BP",
   "kuerzel": "BP1",
   "kurs": 6.4141,
   "kursOriginal": 549.5,
   "waehrungOriginal": "GBX",
   "kgv": 21.15,
   "gewinnJeAktie": 0.303267,
   "dividende": 0.298256,
   "divRendite": 4.65,
   "sektor": "Energie",
   "land": "Grossbritannien"
  },
  {
   "id": "gsk",
   "art": "aktie",
   "name": "GSK",
   "kuerzel": "GSK",
   "kurs": 22.3941,
   "kursOriginal": 1918.5,
   "waehrungOriginal": "GBX",
   "kgv": 16.28,
   "gewinnJeAktie": 1.3756,
   "dividende": 0.853215,
   "divRendite": 3.81,
   "sektor": "Pharma",
   "land": "Grossbritannien"
  },
  {
   "id": "dge",
   "art": "aktie",
   "name": "Diageo",
   "kuerzel": "DGE",
   "kurs": 20.0654,
   "kursOriginal": 1719,
   "waehrungOriginal": "GBX",
   "kgv": 29.28,
   "gewinnJeAktie": 0.685294,
   "dividende": 0.427393,
   "divRendite": 2.13,
   "sektor": "Nahrung",
   "land": "Grossbritannien"
  },
  {
   "id": "rio",
   "art": "aktie",
   "name": "Rio Tinto",
   "kuerzel": "RIO",
   "kurs": 89.2728,
   "kursOriginal": 7648,
   "waehrungOriginal": "GBX",
   "kgv": 13.75,
   "gewinnJeAktie": 6.4926,
   "dividende": 3.437,
   "divRendite": 3.85,
   "sektor": "Industrie",
   "land": "Grossbritannien"
  },
  {
   "id": "barc",
   "art": "aktie",
   "name": "Barclays",
   "kuerzel": "BARC",
   "kurs": 5.75,
   "kursOriginal": 492.6,
   "waehrungOriginal": "GBX",
   "kgv": 10.24,
   "gewinnJeAktie": 0.561523,
   "dividende": 0.099475,
   "divRendite": 1.73,
   "sektor": "Banken",
   "land": "Grossbritannien"
  },
  {
   "id": "lloy",
   "art": "aktie",
   "name": "Lloyds Banking Group",
   "kuerzel": "LLOY",
   "kurs": 1.2986,
   "kursOriginal": 111.25,
   "waehrungOriginal": "GBX",
   "kgv": 13.94,
   "gewinnJeAktie": 0.0931564,
   "dividende": 0.0420746,
   "divRendite": 3.24,
   "sektor": "Banken",
   "land": "Grossbritannien"
  },
  {
   "id": "ba1",
   "art": "aktie",
   "name": "BAE Systems",
   "kuerzel": "BA1",
   "kurs": 24.8162,
   "kursOriginal": 2126,
   "waehrungOriginal": "GBX",
   "kgv": 30.46,
   "gewinnJeAktie": 0.814714,
   "dividende": 0.416912,
   "divRendite": 1.68,
   "sektor": "Ruestung",
   "land": "Grossbritannien"
  },
  {
   "id": "rr",
   "art": "aktie",
   "name": "Rolls-Royce",
   "kuerzel": "RR",
   "kurs": 17.5347,
   "kursOriginal": 1502.2,
   "waehrungOriginal": "GBX",
   "kgv": 41.52,
   "gewinnJeAktie": 0.422319,
   "dividende": 0.138524,
   "divRendite": 0.79,
   "sektor": "Luftfahrt",
   "land": "Grossbritannien"
  },
  {
   "id": "nesn",
   "art": "aktie",
   "name": "Nestle",
   "kuerzel": "NESN",
   "kurs": 85.1919,
   "kursOriginal": 79.68,
   "waehrungOriginal": "CHF",
   "kgv": 27.56,
   "gewinnJeAktie": 3.0911,
   "dividende": 3.331,
   "divRendite": 3.91,
   "sektor": "Nahrung",
   "land": "Schweiz"
  },
  {
   "id": "ro",
   "art": "aktie",
   "name": "Roche",
   "kuerzel": "RO",
   "kurs": 405.86,
   "kursOriginal": 379.60001,
   "waehrungOriginal": "CHF",
   "kgv": 24.28,
   "gewinnJeAktie": 16.7158,
   "dividende": 11.9323,
   "divRendite": 2.94,
   "sektor": "Pharma",
   "land": "Schweiz"
  },
  {
   "id": "zurn",
   "art": "aktie",
   "name": "Zurich Insurance",
   "kuerzel": "ZURN",
   "kurs": 626.54,
   "kursOriginal": 586,
   "waehrungOriginal": "CHF",
   "kgv": 14.7,
   "gewinnJeAktie": 42.6218,
   "dividende": 32.0788,
   "divRendite": 5.12,
   "sektor": "Versicherung",
   "land": "Schweiz"
  },
  {
   "id": "abbn",
   "art": "aktie",
   "name": "ABB",
   "kuerzel": "ABBN",
   "kurs": 85.7479,
   "kursOriginal": 80.2,
   "waehrungOriginal": "CHF",
   "kgv": 36.49,
   "gewinnJeAktie": 2.3499,
   "dividende": 1.0033,
   "divRendite": 1.17,
   "sektor": "Industrie",
   "land": "Schweiz"
  },
  {
   "id": "ubsg",
   "art": "aktie",
   "name": "UBS Group",
   "kuerzel": "UBSG",
   "kurs": 45.44,
   "kursOriginal": 42.5,
   "waehrungOriginal": "CHF",
   "kgv": 17.92,
   "gewinnJeAktie": 2.5357,
   "dividende": 0.93152,
   "divRendite": 2.05,
   "sektor": "Banken",
   "land": "Schweiz"
  },
  {
   "id": "cfr",
   "art": "aktie",
   "name": "Richemont",
   "kuerzel": "CFR",
   "kurs": 198.6,
   "kursOriginal": 185.75,
   "waehrungOriginal": "CHF",
   "kgv": 34.19,
   "gewinnJeAktie": 5.8087,
   "dividende": 3.4954,
   "divRendite": 1.76,
   "sektor": "Luxus",
   "land": "Schweiz"
  },
  {
   "id": "holn",
   "art": "aktie",
   "name": "Holcim",
   "kuerzel": "HOLN",
   "kurs": 75.163,
   "kursOriginal": 70.3,
   "waehrungOriginal": "CHF",
   "kgv": 99.89,
   "gewinnJeAktie": 0.752458,
   "dividende": 1.834,
   "divRendite": 2.44,
   "sektor": "Bau",
   "land": "Schweiz"
  },
  {
   "id": "sika",
   "art": "aktie",
   "name": "Sika",
   "kuerzel": "SIKA",
   "kurs": 198.65,
   "kursOriginal": 185.8,
   "waehrungOriginal": "CHF",
   "kgv": 28.67,
   "gewinnJeAktie": 6.9288,
   "dividende": 3.973,
   "divRendite": 2,
   "sektor": "Chemie",
   "land": "Schweiz"
  },
  {
   "id": "sren",
   "art": "aktie",
   "name": "Swiss Re",
   "kuerzel": "SREN",
   "kurs": 148.94,
   "kursOriginal": 139.3,
   "waehrungOriginal": "CHF",
   "kgv": 10.5,
   "gewinnJeAktie": 14.1848,
   "dividende": 6.8066,
   "divRendite": 4.57,
   "sektor": "Versicherung",
   "land": "Schweiz"
  },
  {
   "id": "lonn",
   "art": "aktie",
   "name": "Lonza",
   "kuerzel": "LONN",
   "kurs": 633.17,
   "kursOriginal": 592.20001,
   "waehrungOriginal": "CHF",
   "kgv": 38.28,
   "gewinnJeAktie": 16.5405,
   "dividende": 5.5719,
   "divRendite": 0.88,
   "sektor": "Pharma",
   "land": "Schweiz"
  },
  {
   "id": "7203",
   "art": "aktie",
   "name": "Toyota Motor",
   "kuerzel": "7203",
   "kurs": 16.8695,
   "kursOriginal": 3132,
   "waehrungOriginal": "JPY",
   "kgv": 8.97,
   "gewinnJeAktie": 1.8807,
   "dividende": 0.55838,
   "divRendite": 3.31,
   "sektor": "Automobil",
   "land": "Japan"
  },
  {
   "id": "6758",
   "art": "aktie",
   "name": "Sony Group",
   "kuerzel": "6758",
   "kurs": 20.3867,
   "kursOriginal": 3785,
   "waehrungOriginal": "JPY",
   "kgv": 20.2,
   "gewinnJeAktie": 1.0092,
   "dividende": 0.187558,
   "divRendite": 0.92,
   "sektor": "Technologie",
   "land": "Japan"
  },
  {
   "id": "7974",
   "art": "aktie",
   "name": "Nintendo",
   "kuerzel": "7974",
   "kurs": 46.3158,
   "kursOriginal": 8599,
   "waehrungOriginal": "JPY",
   "kgv": 20.99,
   "gewinnJeAktie": 2.2066,
   "dividende": 0.875369,
   "divRendite": 1.89,
   "sektor": "Medien",
   "land": "Japan"
  },
  {
   "id": "6861",
   "art": "aktie",
   "name": "Keyence",
   "kuerzel": "6861",
   "kurs": 430.36,
   "kursOriginal": 79900,
   "waehrungOriginal": "JPY",
   "kgv": 39.37,
   "gewinnJeAktie": 10.9312,
   "dividende": 2.9695,
   "divRendite": 0.69,
   "sektor": "Industrie",
   "land": "Japan"
  },
  {
   "id": "8035",
   "art": "aktie",
   "name": "Tokyo Electron",
   "kuerzel": "8035",
   "kurs": 292.42,
   "kursOriginal": 54290,
   "waehrungOriginal": "JPY",
   "kgv": 40.08,
   "gewinnJeAktie": 7.2959,
   "dividende": 4.0062,
   "divRendite": 1.37,
   "sektor": "Halbleiter",
   "land": "Japan"
  },
  {
   "id": "6857",
   "art": "aktie",
   "name": "Advantest",
   "kuerzel": "6857",
   "kurs": 193.36,
   "kursOriginal": 35900,
   "waehrungOriginal": "JPY",
   "kgv": 56.96,
   "gewinnJeAktie": 3.3947,
   "dividende": 0.328712,
   "divRendite": 0.17,
   "sektor": "Halbleiter",
   "land": "Japan"
  },
  {
   "id": "9984",
   "art": "aktie",
   "name": "SoftBank Group",
   "kuerzel": "9984",
   "kurs": 28.3044,
   "kursOriginal": 5255,
   "waehrungOriginal": "JPY",
   "kgv": 6.11,
   "gewinnJeAktie": 4.6325,
   "dividende": 0.0566088,
   "divRendite": 0.2,
   "sektor": "Technologie",
   "land": "Japan"
  },
  {
   "id": "6501",
   "art": "aktie",
   "name": "Hitachi",
   "kuerzel": "6501",
   "kurs": 27.9866,
   "kursOriginal": 5196,
   "waehrungOriginal": "JPY",
   "kgv": 29.37,
   "gewinnJeAktie": 0.952898,
   "dividende": 0.299457,
   "divRendite": 1.07,
   "sektor": "Industrie",
   "land": "Japan"
  },
  {
   "id": "8058",
   "art": "aktie",
   "name": "Mitsubishi Corporation",
   "kuerzel": "8058",
   "kurs": 25.8214,
   "kursOriginal": 4794,
   "waehrungOriginal": "JPY",
   "kgv": 20.05,
   "gewinnJeAktie": 1.2879,
   "dividende": 0.694596,
   "divRendite": 2.69,
   "sektor": "Handel",
   "land": "Japan"
  },
  {
   "id": "4063",
   "art": "aktie",
   "name": "Shin-Etsu Chemical",
   "kuerzel": "4063",
   "kurs": 32.5918,
   "kursOriginal": 6051,
   "waehrungOriginal": "JPY",
   "kgv": 23.62,
   "gewinnJeAktie": 1.3798,
   "dividende": 0.612726,
   "divRendite": 1.88,
   "sektor": "Chemie",
   "land": "Japan"
  },
  {
   "id": "4502",
   "art": "aktie",
   "name": "Takeda Pharmaceutical",
   "kuerzel": "4502",
   "kurs": 31.046,
   "kursOriginal": 5764,
   "waehrungOriginal": "JPY",
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 1.099,
   "divRendite": 3.54,
   "sektor": "Pharma",
   "land": "Japan"
  },
  {
   "id": "7267",
   "art": "aktie",
   "name": "Honda Motor",
   "kuerzel": "7267",
   "kurs": 9.442,
   "kursOriginal": 1753,
   "waehrungOriginal": "JPY",
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0.386178,
   "divRendite": 4.09,
   "sektor": "Automobil",
   "land": "Japan"
  },
  {
   "id": "8316",
   "art": "aktie",
   "name": "Sumitomo Mitsui Financial",
   "kuerzel": "8316",
   "kurs": 35.5812,
   "kursOriginal": 6606,
   "waehrungOriginal": "JPY",
   "kgv": 20.04,
   "gewinnJeAktie": 1.7755,
   "dividende": 0.974925,
   "divRendite": 2.74,
   "sektor": "Banken",
   "land": "Japan"
  },
  {
   "id": "9983",
   "art": "aktie",
   "name": "Fast Retailing",
   "kuerzel": "9983",
   "kurs": 395.94,
   "kursOriginal": 73510,
   "waehrungOriginal": "JPY",
   "kgv": 43.44,
   "gewinnJeAktie": 9.1146,
   "dividende": 3.3655,
   "divRendite": 0.85,
   "sektor": "Handel",
   "land": "Japan"
  },
  {
   "id": "9432",
   "art": "aktie",
   "name": "Nippon Telegraph & Telephone",
   "kuerzel": "9432",
   "kurs": 0.894646,
   "kursOriginal": 166.1,
   "waehrungOriginal": "JPY",
   "kgv": 12.93,
   "gewinnJeAktie": 0.0691915,
   "dividende": 0.0299706,
   "divRendite": 3.35,
   "sektor": "Telekom",
   "land": "Japan"
  },
  {
   "id": "005930",
   "art": "aktie",
   "name": "Samsung Electronics",
   "kuerzel": "005930",
   "kurs": 173.83,
   "kursOriginal": 281500,
   "waehrungOriginal": "KRW",
   "kgv": 12.55,
   "gewinnJeAktie": 13.851,
   "dividende": 1.3906,
   "divRendite": 0.8,
   "sektor": "Technologie",
   "land": "Suedkorea"
  },
  {
   "id": "005380",
   "art": "aktie",
   "name": "Hyundai Motor",
   "kuerzel": "005380",
   "kurs": 256.27,
   "kursOriginal": 415000,
   "waehrungOriginal": "KRW",
   "kgv": 13.32,
   "gewinnJeAktie": 19.2395,
   "dividende": 6.1505,
   "divRendite": 2.4,
   "sektor": "Automobil",
   "land": "Suedkorea"
  },
  {
   "id": "000270",
   "art": "aktie",
   "name": "Kia",
   "kuerzel": "000270",
   "kurs": 80.8319,
   "kursOriginal": 130900,
   "waehrungOriginal": "KRW",
   "kgv": 7.27,
   "gewinnJeAktie": 11.1186,
   "dividende": 4.0093,
   "divRendite": 4.96,
   "sektor": "Automobil",
   "land": "Suedkorea"
  },
  {
   "id": "035420",
   "art": "aktie",
   "name": "NAVER",
   "kuerzel": "035420",
   "kurs": 137.09,
   "kursOriginal": 222000,
   "waehrungOriginal": "KRW",
   "kgv": 16.57,
   "gewinnJeAktie": 8.2734,
   "dividende": 1.6588,
   "divRendite": 1.21,
   "sektor": "Technologie",
   "land": "Suedkorea"
  },
  {
   "id": "207940",
   "art": "aktie",
   "name": "Samsung Biologics",
   "kuerzel": "207940",
   "kurs": 957.76,
   "kursOriginal": 1551000,
   "waehrungOriginal": "KRW",
   "kgv": 26.1,
   "gewinnJeAktie": 36.6958,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Pharma",
   "land": "Suedkorea"
  },
  {
   "id": "005490",
   "art": "aktie",
   "name": "POSCO Holdings",
   "kuerzel": "005490",
   "kurs": 191.43,
   "kursOriginal": 310000,
   "waehrungOriginal": "KRW",
   "kgv": 17.4,
   "gewinnJeAktie": 11.0017,
   "dividende": 4.9389,
   "divRendite": 2.58,
   "sektor": "Industrie",
   "land": "Suedkorea"
  },
  {
   "id": "373220",
   "art": "aktie",
   "name": "LG Energy Solution",
   "kuerzel": "373220",
   "kurs": 212.11,
   "kursOriginal": 343500,
   "waehrungOriginal": "KRW",
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Industrie",
   "land": "Suedkorea"
  },
  {
   "id": "0700",
   "art": "aktie",
   "name": "Tencent Holdings",
   "kuerzel": "0700",
   "kurs": 49.8223,
   "kursOriginal": 457,
   "waehrungOriginal": "HKD",
   "kgv": 15.56,
   "gewinnJeAktie": 3.2019,
   "dividende": 0.577939,
   "divRendite": 1.16,
   "sektor": "Technologie",
   "land": "Hongkong"
  },
  {
   "id": "1299",
   "art": "aktie",
   "name": "AIA Group",
   "kuerzel": "1299",
   "kurs": 8.1929,
   "kursOriginal": 75.15,
   "waehrungOriginal": "HKD",
   "kgv": 12.54,
   "gewinnJeAktie": 0.653341,
   "dividende": 0.210558,
   "divRendite": 2.57,
   "sektor": "Versicherung",
   "land": "Hongkong"
  },
  {
   "id": "0388",
   "art": "aktie",
   "name": "Hong Kong Exchanges",
   "kuerzel": "0388",
   "kurs": 45.8976,
   "kursOriginal": 421,
   "waehrungOriginal": "HKD",
   "kgv": 26.94,
   "gewinnJeAktie": 1.7037,
   "dividende": 1.6202,
   "divRendite": 3.53,
   "sektor": "Finanzen",
   "land": "Hongkong"
  },
  {
   "id": "shop",
   "art": "aktie",
   "name": "Shopify",
   "kuerzel": "SHOP",
   "kurs": 127.91,
   "kursOriginal": 205.61,
   "waehrungOriginal": "CAD",
   "kgv": 96.57,
   "gewinnJeAktie": 1.3245,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Technologie",
   "land": "Kanada"
  },
  {
   "id": "td",
   "art": "aktie",
   "name": "Toronto-Dominion Bank",
   "kuerzel": "TD",
   "kurs": 100.31,
   "kursOriginal": 161.24,
   "waehrungOriginal": "CAD",
   "kgv": 19.05,
   "gewinnJeAktie": 5.2656,
   "dividende": 2.7886,
   "divRendite": 2.78,
   "sektor": "Banken",
   "land": "Kanada"
  },
  {
   "id": "bns",
   "art": "aktie",
   "name": "Bank of Nova Scotia",
   "kuerzel": "BNS",
   "kurs": 75.0093,
   "kursOriginal": 120.57,
   "waehrungOriginal": "CAD",
   "kgv": 16.61,
   "gewinnJeAktie": 4.5159,
   "dividende": 2.8354,
   "divRendite": 3.78,
   "sektor": "Banken",
   "land": "Kanada"
  },
  {
   "id": "bmo",
   "art": "aktie",
   "name": "Bank of Montreal",
   "kuerzel": "BMO",
   "kurs": 149.46,
   "kursOriginal": 240.25,
   "waehrungOriginal": "CAD",
   "kgv": 18.45,
   "gewinnJeAktie": 8.1008,
   "dividende": 4.2746,
   "divRendite": 2.86,
   "sektor": "Banken",
   "land": "Kanada"
  },
  {
   "id": "enb",
   "art": "aktie",
   "name": "Enbridge",
   "kuerzel": "ENB",
   "kurs": 43.2437,
   "kursOriginal": 69.51,
   "waehrungOriginal": "CAD",
   "kgv": 26.85,
   "gewinnJeAktie": 1.6106,
   "dividende": 2.413,
   "divRendite": 5.58,
   "sektor": "Energie",
   "land": "Kanada"
  },
  {
   "id": "cnq",
   "art": "aktie",
   "name": "Canadian Natural Resources",
   "kuerzel": "CNQ",
   "kurs": 44.0525,
   "kursOriginal": 70.81,
   "waehrungOriginal": "CAD",
   "kgv": 12.6,
   "gewinnJeAktie": 3.4962,
   "dividende": 1.5595,
   "divRendite": 3.54,
   "sektor": "Energie",
   "land": "Kanada"
  },
  {
   "id": "cnr",
   "art": "aktie",
   "name": "Canadian National Railway",
   "kuerzel": "CNR",
   "kurs": 111.19,
   "kursOriginal": 178.73,
   "waehrungOriginal": "CAD",
   "kgv": 22.94,
   "gewinnJeAktie": 4.847,
   "dividende": 2.2794,
   "divRendite": 2.05,
   "sektor": "Logistik",
   "land": "Kanada"
  },
  {
   "id": "cp",
   "art": "aktie",
   "name": "Canadian Pacific Kansas City",
   "kuerzel": "CP",
   "kurs": 82.7921,
   "kursOriginal": 133.08,
   "waehrungOriginal": "CAD",
   "kgv": 30.95,
   "gewinnJeAktie": 2.675,
   "dividende": 0.678895,
   "divRendite": 0.82,
   "sektor": "Logistik",
   "land": "Kanada"
  },
  {
   "id": "bce",
   "art": "aktie",
   "name": "BCE",
   "kuerzel": "BCE",
   "kurs": 20.3123,
   "kursOriginal": 32.65,
   "waehrungOriginal": "CAD",
   "kgv": 4.86,
   "gewinnJeAktie": 4.1795,
   "dividende": 1.0847,
   "divRendite": 5.34,
   "sektor": "Telekom",
   "land": "Kanada"
  },
  {
   "id": "bn1",
   "art": "aktie",
   "name": "Brookfield Corporation",
   "kuerzel": "BN1",
   "kurs": 35.7098,
   "kursOriginal": 57.4,
   "waehrungOriginal": "CAD",
   "kgv": 75.2,
   "gewinnJeAktie": 0.474864,
   "dividende": 0.239256,
   "divRendite": 0.67,
   "sektor": "Finanzen",
   "land": "Kanada"
  },
  {
   "id": "ba",
   "art": "aktie",
   "name": "Boeing",
   "kuerzel": "BA",
   "kurs": 183.09,
   "kursOriginal": 214.2,
   "waehrungOriginal": "USD",
   "kgv": 79.88,
   "gewinnJeAktie": 2.2921,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Luftfahrt",
   "land": "USA"
  },
  {
   "id": "dis",
   "art": "aktie",
   "name": "Walt Disney",
   "kuerzel": "DIS",
   "kurs": 92.1275,
   "kursOriginal": 107.78,
   "waehrungOriginal": "USD",
   "kgv": 22.28,
   "gewinnJeAktie": 4.135,
   "dividende": 1.2806,
   "divRendite": 1.39,
   "sektor": "Medien",
   "land": "USA"
  },
  {
   "id": "vz",
   "art": "aktie",
   "name": "Verizon Communications",
   "kuerzel": "VZ",
   "kurs": 42.2686,
   "kursOriginal": 49.45,
   "waehrungOriginal": "USD",
   "kgv": 12.88,
   "gewinnJeAktie": 3.2817,
   "dividende": 2.4178,
   "divRendite": 5.72,
   "sektor": "Telekom",
   "land": "USA"
  },
  {
   "id": "lmt",
   "art": "aktie",
   "name": "Lockheed Martin",
   "kuerzel": "LMT",
   "kurs": 481.72,
   "kursOriginal": 563.57,
   "waehrungOriginal": "USD",
   "kgv": 20.77,
   "gewinnJeAktie": 23.1931,
   "dividende": 11.8021,
   "divRendite": 2.45,
   "sektor": "Ruestung",
   "land": "USA"
  },
  {
   "id": "amt",
   "art": "aktie",
   "name": "American Tower",
   "kuerzel": "AMT",
   "kurs": 150.27,
   "kursOriginal": 175.8,
   "waehrungOriginal": "USD",
   "kgv": 24.18,
   "gewinnJeAktie": 6.2146,
   "dividende": 6.116,
   "divRendite": 4.07,
   "sektor": "Immobilien",
   "land": "USA"
  },
  {
   "id": "crm",
   "art": "aktie",
   "name": "Salesforce",
   "kuerzel": "CRM",
   "kurs": 178.79,
   "kursOriginal": 209.17,
   "waehrungOriginal": "USD",
   "kgv": 24.28,
   "gewinnJeAktie": 7.3637,
   "dividende": 1.5018,
   "divRendite": 0.84,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "adbe",
   "art": "aktie",
   "name": "Adobe",
   "kuerzel": "ADBE",
   "kurs": 235.32,
   "kursOriginal": 275.3,
   "waehrungOriginal": "USD",
   "kgv": 15.75,
   "gewinnJeAktie": 14.941,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "qcom",
   "art": "aktie",
   "name": "Qualcomm",
   "kuerzel": "QCOM",
   "kurs": 137.4,
   "kursOriginal": 160.75,
   "waehrungOriginal": "USD",
   "kgv": 18.7,
   "gewinnJeAktie": 7.3476,
   "dividende": 3.1465,
   "divRendite": 2.29,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "ibm",
   "art": "aktie",
   "name": "IBM",
   "kuerzel": "IBM",
   "kurs": 201.45,
   "kursOriginal": 235.68,
   "waehrungOriginal": "USD",
   "kgv": 20.96,
   "gewinnJeAktie": 9.6112,
   "dividende": 5.7816,
   "divRendite": 2.87,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "pfe",
   "art": "aktie",
   "name": "Pfizer",
   "kuerzel": "PFE",
   "kurs": 23.9935,
   "kursOriginal": 28.07,
   "waehrungOriginal": "USD",
   "kgv": 36.9,
   "gewinnJeAktie": 0.65023,
   "dividende": 1.4708,
   "divRendite": 6.13,
   "sektor": "Pharma",
   "land": "USA"
  },
  {
   "id": "abbv",
   "art": "aktie",
   "name": "AbbVie",
   "kuerzel": "ABBV",
   "kurs": 226.48,
   "kursOriginal": 264.96,
   "waehrungOriginal": "USD",
   "kgv": 74.85,
   "gewinnJeAktie": 3.0258,
   "dividende": 5.9111,
   "divRendite": 2.61,
   "sektor": "Pharma",
   "land": "USA"
  },
  {
   "id": "mcd",
   "art": "aktie",
   "name": "McDonald's",
   "kuerzel": "MCD",
   "kurs": 231.6,
   "kursOriginal": 270.95,
   "waehrungOriginal": "USD",
   "kgv": 22.01,
   "gewinnJeAktie": 10.5225,
   "dividende": 6.369,
   "divRendite": 2.75,
   "sektor": "Nahrung",
   "land": "USA"
  },
  {
   "id": "nke",
   "art": "aktie",
   "name": "Nike",
   "kuerzel": "NKE",
   "kurs": 34.8406,
   "kursOriginal": 40.76,
   "waehrungOriginal": "USD",
   "kgv": 19.41,
   "gewinnJeAktie": 1.795,
   "dividende": 1.4006,
   "divRendite": 4.02,
   "sektor": "Konsum",
   "land": "USA"
  },
  {
   "id": "pep",
   "art": "aktie",
   "name": "PepsiCo",
   "kuerzel": "PEP",
   "kurs": 122.64,
   "kursOriginal": 143.48,
   "waehrungOriginal": "USD",
   "kgv": 18.8,
   "gewinnJeAktie": 6.5234,
   "dividende": 5.065,
   "divRendite": 4.13,
   "sektor": "Nahrung",
   "land": "USA"
  },
  {
   "id": "coin",
   "art": "aktie",
   "name": "Coinbase",
   "kuerzel": "COIN",
   "kurs": 159.41,
   "kursOriginal": 186.49,
   "waehrungOriginal": "USD",
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Finanzen",
   "land": "USA"
  },
  {
   "id": "voo",
   "art": "etf",
   "name": "Vanguard S&P 500 ETF",
   "kuerzel": "VOO",
   "kurs": 601.51,
   "kursOriginal": 703.71,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 1030,
   "anzahlPositionen": 518,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "USA breit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "qqq",
   "art": "etf",
   "name": "Invesco QQQ Trust",
   "kuerzel": "QQQ",
   "kurs": 609.83,
   "kursOriginal": 713.44,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 488.9,
   "anzahlPositionen": 105,
   "ter": 0.18,
   "ausschuettend": true,
   "sektor": "USA Technologie",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vt",
   "art": "etf",
   "name": "Vanguard Total World Stock ETF",
   "kuerzel": "VT",
   "kurs": 137.42,
   "kursOriginal": 160.77,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 81,
   "anzahlPositionen": 10144,
   "ter": 0.06,
   "ausschuettend": true,
   "sektor": "Welt",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vea",
   "art": "etf",
   "name": "Vanguard FTSE Developed Markets ETF",
   "kuerzel": "VEA",
   "kurs": 62.7575,
   "kursOriginal": 73.42,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 235.4,
   "anzahlPositionen": 3877,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "Welt ohne USA",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vwo",
   "art": "etf",
   "name": "Vanguard FTSE Emerging Markets ETF",
   "kuerzel": "VWO",
   "kurs": 51.6711,
   "kursOriginal": 60.45,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 124.8,
   "anzahlPositionen": 5063,
   "ter": 0.06,
   "ausschuettend": true,
   "sektor": "Schwellenlaender",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "efa",
   "art": "etf",
   "name": "iShares MSCI EAFE ETF",
   "kuerzel": "EFA",
   "kurs": 92.5207,
   "kursOriginal": 108.24,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 79.2,
   "anzahlPositionen": 699,
   "ter": 0.32,
   "ausschuettend": true,
   "sektor": "Europa/Asien",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "iwm",
   "art": "etf",
   "name": "iShares Russell 2000 ETF",
   "kuerzel": "IWM",
   "kurs": 256.4,
   "kursOriginal": 299.96,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 82,
   "anzahlPositionen": 1971,
   "ter": 0.19,
   "ausschuettend": true,
   "sektor": "USA klein",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "ijh",
   "art": "etf",
   "name": "iShares Core S&P Mid-Cap ETF",
   "kuerzel": "IJH",
   "kurs": 65.621,
   "kursOriginal": 76.77,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 126.5,
   "anzahlPositionen": 414,
   "ter": 0.05,
   "ausschuettend": true,
   "sektor": "USA mittel",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "dia",
   "art": "etf",
   "name": "SPDR Dow Jones Industrial Average ETF",
   "kuerzel": "DIA",
   "kurs": 454.93,
   "kursOriginal": 532.22,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 46.4,
   "anzahlPositionen": 31,
   "ter": 0.16,
   "ausschuettend": true,
   "sektor": "USA Standard",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "rsp",
   "art": "etf",
   "name": "Invesco S&P 500 Equal Weight ETF",
   "kuerzel": "RSP",
   "kurs": 189.48,
   "kursOriginal": 221.67,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 99.5,
   "anzahlPositionen": 509,
   "ter": 0.2,
   "ausschuettend": true,
   "sektor": "USA breit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vug",
   "art": "etf",
   "name": "Vanguard Growth ETF",
   "kuerzel": "VUG",
   "kurs": 74.7927,
   "kursOriginal": 87.5,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 225.9,
   "anzahlPositionen": 151,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "USA Wachstum",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vtv",
   "art": "etf",
   "name": "Vanguard Value ETF",
   "kuerzel": "VTV",
   "kurs": 193.52,
   "kursOriginal": 226.4,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 193.6,
   "anzahlPositionen": 326,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "USA Substanz",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "schd",
   "art": "etf",
   "name": "Schwab US Dividend Equity ETF",
   "kuerzel": "SCHD",
   "kurs": 30.0111,
   "kursOriginal": 35.11,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 109.5,
   "anzahlPositionen": 103,
   "ter": 0.06,
   "ausschuettend": true,
   "sektor": "Dividenden",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vym",
   "art": "etf",
   "name": "Vanguard High Dividend Yield ETF",
   "kuerzel": "VYM",
   "kurs": 141.01,
   "kursOriginal": 164.97,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 83.8,
   "anzahlPositionen": 618,
   "ter": 0.04,
   "ausschuettend": true,
   "sektor": "Dividenden",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlk",
   "art": "etf",
   "name": "Technology Select Sector SPDR",
   "kuerzel": "XLK",
   "kurs": 156.69,
   "kursOriginal": 183.31,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 121.1,
   "anzahlPositionen": 76,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Technologie",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "soxx",
   "art": "etf",
   "name": "iShares Semiconductor ETF",
   "kuerzel": "SOXX",
   "kurs": 444.53,
   "kursOriginal": 520.05,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 41.4,
   "anzahlPositionen": 34,
   "ter": 0.33,
   "ausschuettend": true,
   "sektor": "Halbleiter",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlv",
   "art": "etf",
   "name": "Health Care Select Sector SPDR",
   "kuerzel": "XLV",
   "kurs": 149.26,
   "kursOriginal": 174.62,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 44.2,
   "anzahlPositionen": 63,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Gesundheit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlf",
   "art": "etf",
   "name": "Financial Select Sector SPDR",
   "kuerzel": "XLF",
   "kurs": 49.1324,
   "kursOriginal": 57.48,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 57.1,
   "anzahlPositionen": 80,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Finanzen",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xle",
   "art": "etf",
   "name": "Energy Select Sector SPDR",
   "kuerzel": "XLE",
   "kurs": 54.3978,
   "kursOriginal": 63.64,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 41.9,
   "anzahlPositionen": 24,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Energie",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vnq",
   "art": "etf",
   "name": "Vanguard Real Estate ETF",
   "kuerzel": "VNQ",
   "kurs": 84.1952,
   "kursOriginal": 98.5,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 38.6,
   "anzahlPositionen": 157,
   "ter": 0.13,
   "ausschuettend": true,
   "sektor": "Immobilien",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "gld",
   "art": "etf",
   "name": "SPDR Gold Shares",
   "kuerzel": "GLD",
   "kurs": 361.88,
   "kursOriginal": 423.36,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 145.1,
   "anzahlPositionen": 2,
   "ter": 0.4,
   "ausschuettend": true,
   "sektor": "Rohstoffe",
   "anlageklasse": "Rohstoff",
   "land": null
  },
  {
   "id": "agg",
   "art": "etf",
   "name": "iShares Core US Aggregate Bond ETF",
   "kuerzel": "AGG",
   "kurs": 83.2122,
   "kursOriginal": 97.35,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 138,
   "anzahlPositionen": 13371,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "Anleihen",
   "anlageklasse": "Anleihen",
   "land": null
  },
  {
   "id": "tlt",
   "art": "etf",
   "name": "iShares 20+ Year Treasury Bond ETF",
   "kuerzel": "TLT",
   "kurs": 70.1342,
   "kursOriginal": 82.05,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 46.1,
   "anzahlPositionen": 48,
   "ter": 0.15,
   "ausschuettend": true,
   "sektor": "Anleihen",
   "anlageklasse": "Anleihen",
   "land": null
  },
  {
   "id": "vcit",
   "art": "etf",
   "name": "Vanguard Interm.-Term Corp. Bond ETF",
   "kuerzel": "VCIT",
   "kurs": 69.2794,
   "kursOriginal": 81.05,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 68,
   "anzahlPositionen": 2268,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "Anleihen",
   "anlageklasse": "Anleihen",
   "land": null
  },
  {
   "id": "ibit",
   "art": "etf",
   "name": "iShares Bitcoin Trust",
   "kuerzel": "IBIT",
   "kurs": 37.3365,
   "kursOriginal": 43.68,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 48.4,
   "anzahlPositionen": 2,
   "ter": 0.25,
   "ausschuettend": true,
   "sektor": "Krypto",
   "anlageklasse": "Krypto",
   "land": null
  },
  {
   "id": "spy",
   "art": "etf",
   "name": "SPDR S&P 500 ETF Trust",
   "kuerzel": "SPY",
   "kurs": 654.52,
   "kursOriginal": 765.72,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 814.5,
   "anzahlPositionen": 505,
   "ter": 0.09,
   "ausschuettend": true,
   "sektor": "USA breit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "ivv",
   "art": "etf",
   "name": "iShares Core S&P 500 ETF",
   "kuerzel": "IVV",
   "kurs": 657.59,
   "kursOriginal": 769.31,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 894,
   "anzahlPositionen": 508,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "USA breit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vti",
   "art": "etf",
   "name": "Vanguard Total Stock Market ETF",
   "kuerzel": "VTI",
   "kurs": 323.31,
   "kursOriginal": 378.24,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 688.6,
   "anzahlPositionen": 3498,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "USA breit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "iefa",
   "art": "etf",
   "name": "iShares Core MSCI EAFE ETF",
   "kuerzel": "IEFA",
   "kurs": 86.2039,
   "kursOriginal": 100.85,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 193.2,
   "anzahlPositionen": 2641,
   "ter": 0.07,
   "ausschuettend": true,
   "sektor": "Europa/Asien",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "iemg",
   "art": "etf",
   "name": "iShares Core MSCI Emerging Markets ETF",
   "kuerzel": "IEMG",
   "kurs": 69.7239,
   "kursOriginal": 81.57,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 156.5,
   "anzahlPositionen": 2896,
   "ter": 0.09,
   "ausschuettend": true,
   "sektor": "Schwellenlaender",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "ewj",
   "art": "etf",
   "name": "iShares MSCI Japan ETF",
   "kuerzel": "EWJ",
   "kurs": 81.3574,
   "kursOriginal": 95.18,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 22.5,
   "anzahlPositionen": 174,
   "ter": 0.49,
   "ausschuettend": true,
   "sektor": "Japan",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "ezu",
   "art": "etf",
   "name": "iShares MSCI Eurozone ETF",
   "kuerzel": "EZU",
   "kurs": 61.1078,
   "kursOriginal": 71.49,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 9.9,
   "anzahlPositionen": 226,
   "ter": 0.5,
   "ausschuettend": true,
   "sektor": "Eurozone",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "fxi",
   "art": "etf",
   "name": "iShares China Large-Cap ETF",
   "kuerzel": "FXI",
   "kurs": 30.6522,
   "kursOriginal": 35.86,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 4.2,
   "anzahlPositionen": 59,
   "ter": 0.74,
   "ausschuettend": true,
   "sektor": "China",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "inda",
   "art": "etf",
   "name": "iShares MSCI India ETF",
   "kuerzel": "INDA",
   "kurs": 42.431,
   "kursOriginal": 49.64,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 6.6,
   "anzahlPositionen": 173,
   "ter": 0.61,
   "ausschuettend": true,
   "sektor": "Indien",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xli",
   "art": "etf",
   "name": "Industrial Select Sector SPDR",
   "kuerzel": "XLI",
   "kurs": 154.07,
   "kursOriginal": 180.25,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 34.2,
   "anzahlPositionen": 86,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Industrie",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xly",
   "art": "etf",
   "name": "Consumer Discretionary Select Sector SPDR",
   "kuerzel": "XLY",
   "kurs": 100.88,
   "kursOriginal": 118.02,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 23.1,
   "anzahlPositionen": 50,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Konsum",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlp",
   "art": "etf",
   "name": "Consumer Staples Select Sector SPDR",
   "kuerzel": "XLP",
   "kurs": 73.502,
   "kursOriginal": 85.99,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 14.8,
   "anzahlPositionen": 38,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Nahrung",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlu",
   "art": "etf",
   "name": "Utilities Select Sector SPDR",
   "kuerzel": "XLU",
   "kurs": 36.5587,
   "kursOriginal": 42.77,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 22.8,
   "anzahlPositionen": 34,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Versorger",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlc",
   "art": "etf",
   "name": "Communication Services Select Sector SPDR",
   "kuerzel": "XLC",
   "kurs": 95.2218,
   "kursOriginal": 111.4,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 22.3,
   "anzahlPositionen": 26,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Medien",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "slv",
   "art": "etf",
   "name": "iShares Silver Trust",
   "kuerzel": "SLV",
   "kurs": 53.6114,
   "kursOriginal": 62.72,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 32.1,
   "anzahlPositionen": 1,
   "ter": 0.5,
   "ausschuettend": true,
   "sektor": "Rohstoffe",
   "anlageklasse": "Rohstoff",
   "land": null
  },
  {
   "id": "dbc",
   "art": "etf",
   "name": "Invesco DB Commodity Index Tracking Fund",
   "kuerzel": "DBC",
   "kurs": 26.7202,
   "kursOriginal": 31.26,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 1.8,
   "anzahlPositionen": 41,
   "ter": 0.84,
   "ausschuettend": true,
   "sektor": "Rohstoffe",
   "anlageklasse": "Rohstoff",
   "land": null
  },
  {
   "id": "lqd",
   "art": "etf",
   "name": "iShares iBoxx Investment Grade Corporate Bond ETF",
   "kuerzel": "LQD",
   "kurs": 90.5377,
   "kursOriginal": 105.92,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 34,
   "anzahlPositionen": 3143,
   "ter": 0.14,
   "ausschuettend": true,
   "sektor": "Anleihen",
   "anlageklasse": "Anleihen",
   "land": null
  },
  {
   "id": "hyg",
   "art": "etf",
   "name": "iShares iBoxx High Yield Corporate Bond ETF",
   "kuerzel": "HYG",
   "kurs": 68.0486,
   "kursOriginal": 79.61,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 17.8,
   "anzahlPositionen": 1333,
   "ter": 0.49,
   "ausschuettend": true,
   "sektor": "Anleihen",
   "anlageklasse": "Anleihen",
   "land": null
  },
  {
   "id": "etha",
   "art": "etf",
   "name": "iShares Ethereum Trust",
   "kuerzel": "ETHA",
   "kurs": 15.5911,
   "kursOriginal": 18.24,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 5.8,
   "anzahlPositionen": 2,
   "ter": 0.25,
   "ausschuettend": true,
   "sektor": "Krypto",
   "anlageklasse": "Krypto",
   "land": null
  },
  {
   "id": "btc",
   "art": "krypto",
   "name": "Bitcoin",
   "kuerzel": "BTC",
   "kurs": 65948,
   "marktkapitalisierung": 1323977695414,
   "umlaufmenge": 20071518,
   "hoechstmenge": 21000000,
   "allzeithoch": 107662,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "eth",
   "art": "krypto",
   "name": "Ethereum",
   "kuerzel": "ETH",
   "kurs": 2070.8,
   "marktkapitalisierung": 250068454370,
   "umlaufmenge": 120681574,
   "hoechstmenge": null,
   "allzeithoch": 4229.76,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "xrp",
   "art": "krypto",
   "name": "XRP",
   "kuerzel": "XRP",
   "kurs": 1.27,
   "marktkapitalisierung": 79682388101,
   "umlaufmenge": 62744504852,
   "hoechstmenge": 100000000000,
   "allzeithoch": 3.28,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "sol",
   "art": "krypto",
   "name": "Solana",
   "kuerzel": "SOL",
   "kurs": 80.21,
   "marktkapitalisierung": 46809183027,
   "umlaufmenge": 583176988,
   "hoechstmenge": null,
   "allzeithoch": 285.6,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "doge",
   "art": "krypto",
   "name": "Dogecoin",
   "kuerzel": "DOGE",
   "kurs": 0.077305,
   "marktkapitalisierung": 12026887144,
   "umlaufmenge": 155598386384,
   "hoechstmenge": null,
   "allzeithoch": 0.601466,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "ada",
   "art": "krypto",
   "name": "Cardano",
   "kuerzel": "ADA",
   "kurs": 0.191627,
   "marktkapitalisierung": 7191248170,
   "umlaufmenge": 37486094748,
   "hoechstmenge": 45000000000,
   "allzeithoch": 2.61,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "link",
   "art": "krypto",
   "name": "Chainlink",
   "kuerzel": "LINK",
   "kurs": 10.02,
   "marktkapitalisierung": 7500454815,
   "umlaufmenge": 748099970,
   "hoechstmenge": 1000000000,
   "allzeithoch": 43.32,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "ltc",
   "art": "krypto",
   "name": "Litecoin",
   "kuerzel": "LTC",
   "kurs": 44.3,
   "marktkapitalisierung": 3437289555,
   "umlaufmenge": 77523073,
   "hoechstmenge": 84000000,
   "allzeithoch": 337.56,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "avax",
   "art": "krypto",
   "name": "Avalanche",
   "kuerzel": "AVAX",
   "kurs": 6.4,
   "marktkapitalisierung": 2765683069,
   "umlaufmenge": 431771961,
   "hoechstmenge": 720000000,
   "allzeithoch": 128.43,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "dot",
   "art": "krypto",
   "name": "Polkadot",
   "kuerzel": "DOT",
   "kurs": 0.790268,
   "marktkapitalisierung": 1344139402,
   "umlaufmenge": 1699205782,
   "hoechstmenge": 2100000000,
   "allzeithoch": 47.6,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "bnb",
   "art": "krypto",
   "name": "BNB",
   "kuerzel": "BNB",
   "kurs": 591.26,
   "marktkapitalisierung": 78828608224,
   "umlaufmenge": 133163134,
   "hoechstmenge": 200000000,
   "allzeithoch": 1182.86,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "trx",
   "art": "krypto",
   "name": "Tron",
   "kuerzel": "TRX",
   "kurs": 0.293974,
   "marktkapitalisierung": 27904282970,
   "umlaufmenge": 94912588660,
   "hoechstmenge": null,
   "allzeithoch": 0.410308,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "ton",
   "art": "krypto",
   "name": "Toncoin",
   "kuerzel": "TON",
   "kurs": 1.23,
   "marktkapitalisierung": 3392405643,
   "umlaufmenge": 2762567808,
   "hoechstmenge": null,
   "allzeithoch": 7.7,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "aave",
   "art": "krypto",
   "name": "Aave",
   "kuerzel": "AAVE",
   "kurs": 105.67,
   "marktkapitalisierung": 1632750725,
   "umlaufmenge": 15423210,
   "hoechstmenge": 16000000,
   "allzeithoch": 541.28,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "xlm",
   "art": "krypto",
   "name": "Stellar",
   "kuerzel": "XLM",
   "kurs": 0.170196,
   "marktkapitalisierung": 5887511712,
   "umlaufmenge": 34585312164,
   "hoechstmenge": null,
   "allzeithoch": 0.729104,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "bch",
   "art": "krypto",
   "name": "Bitcoin Cash",
   "kuerzel": "BCH",
   "kurs": 237.75,
   "marktkapitalisierung": 4781889784,
   "umlaufmenge": 20078741,
   "hoechstmenge": 21000000,
   "allzeithoch": 3187.12,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "xmr",
   "art": "krypto",
   "name": "Monero",
   "kuerzel": "XMR",
   "kurs": 365.48,
   "marktkapitalisierung": 6866020084,
   "umlaufmenge": 18794607,
   "hoechstmenge": null,
   "allzeithoch": 685.48,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "uni",
   "art": "krypto",
   "name": "Uniswap",
   "kuerzel": "UNI",
   "kurs": 3.64,
   "marktkapitalisierung": 2272162282,
   "umlaufmenge": 623546424,
   "hoechstmenge": 1000000000,
   "allzeithoch": 37.37,
   "sektor": "Krypto",
   "land": null
  }
 ]
};
